### ISSUE TITLE
Make JSON output adhere to schema.org

### ISSUE THREAD

**Issue by catherinedevlin** [18F/crime-data-api#10]
Using schema.org conventions for our output can make use by others easier.  

At first glance, it looks like crimes may be Actions (http://1.schemaorgae.appspot.com/Action) committed by Persons (http://1.schemaorgae.appspot.com/Person) against other Persons, reported by GovernmentOrganizations(http://1.schemaorgae.appspot.com/GovernmentOrganization) in Places (http://1.schemaorgae.appspot.com/Place).

Not sure yet how aggregation/summaries play into that.

**Comment by harrisj** [comment]
How do we feel about this? Is it important for initial work? And do we have versioning on the API so we could change formats in the future?

**Comment by harrisj** [comment]
I don't think the FBI data lends itself to this. So I'm going to close it
