### ISSUE TITLE
Refactoring: cdemodels.py

### ISSUE THREAD

**Issue by cacraig** [18F/crime-data-api#112]
Refactor cdemodels.py a bit. Improve naming conventions, clean up unused code, add documentation.

Some suggestions:

Catherine:   
(1) TableTrees rather than TableFamilies?  The idea is that it defines the relationships of the tables to each other.
Colin:   
 (1) Blast away the defunct Agencies code, and have it just be a map to /incidents with an extra parameter (ORI). OR make it give a list of all Agencies.  
(2) Document, and add unit tests.

**Comment by catherinedevlin** [comment]
I think a list of agencies (especially a filterable one) would have value.

Plot twist: the TableFamily for an Agency already exists, embedded within the IncidentTableFamily (in cdemodels.py).  That should probably be pulled out into an AgencyTableFamily, and then avoid duplication by having IncidentFamily copy and extend the list of AgencyTableFamily's list

**Comment by harrisj** [comment]
It sounds like some sort of document explaining the naming/structure will be necessary. Sorry

**Comment by harrisj** [comment]
I have been adding some unit tests for internal models, but this seems like something that would have to wait until after the MVP is delivered. Closing for now.
