### ISSUE TITLE
Pagination requests with page 0 should return a 400 error

### ISSUE THREAD

**Issue by jeremiak** [18F/crime-data-api#115]
Currently, making a request to the incidents endpoint with `per_page=100&page=0` results in a `500` error. This is because there isn't a page 0. However, I think this should return a `400` (Bad Request) instead.

**Comment by harrisj** [comment]
I'm not sure this is that much of a priority and how to do it yet.

**Comment by jeremiak** [comment]
I'm fine with closing this, but perhaps this is the sort of work we can achieve after shipping the MVP? I think the UX of the API is important, but I realize that this particular story is very low priority
