### ISSUE TITLE
Update navigation and filter names

### ISSUE THREAD

**Issue by nicoleslaw** [18F/crime-data-api#116]
I think we should put a spreadsheet together [like this one](https://docs.google.com/spreadsheets/d/1-LjKQy3dOJI9FJmrhNEfgsr-uD7HzzH0qf1zpo3azTE/edit) so we're all working from the same language/understanding of the filters. Thanks to Emileigh for sharing!

I am thinking we can start with a tab for the default table view, maybe then add/gray out certain things for specific crimes. Hate crime and LEOKA will have several additional filters, for example. This will need to grow/change over time.

**Comment by nicoleslaw** [comment]
cc @jeremiak @amberwreed — I am happy to work on this on Friday.

**Comment by nicoleslaw** [comment]
@jeremiak I took a pass at the filter labels here on the third tab: https://docs.google.com/spreadsheets/d/1dKhwXumQfVP48TmBJpHxv66ki7KMOcbsSU1nU6thzzo/edit

I don't think we need to add many more of these for our test, but wanted to share.

**Comment by nicoleslaw** [comment]
cc @amberwreed for review

**Comment by LarryBafundo** [comment]
we should convert this to an epic since we be returning to this topic

**Comment by nicoleslaw** [comment]
@LarryBafundo That sounds good—do you want me to put that in the backlog for another sprint?

**Comment by LarryBafundo** [comment]
lets put it in the new issues for now

**Comment by nicoleslaw** [comment]
These should be pretty close after syncing with Larry last sprint: https://docs.google.com/spreadsheets/d/1gRN0bjp-2D9OdXtsA53IZsM6inUjBBEzRYK2gbwgGtM/edit?pli=1#gid=901121743

cc @jeremiak

**Comment by jeremiak** [comment]
@nicoleslaw I think this is done/updated on the site (https://crime-data-explorer.fr.cloud.gov). We have yet to make the NIBRS based detail view or the hate crime view so those have yet to be incorporated.

**Comment by nicoleslaw** [comment]
@jeremiak Thanks—I will send a pull request with some edits on Monday.

**Comment by nicoleslaw** [comment]
Changing my mind: I am going to close this; I will do a copy editing pass on the entire /explore section later in the sprint.
