### ISSUE TITLE
Clarify testing approach

### ISSUE THREAD

**Issue by harrisj** [18F/crime-data-api#118]
Right now, we have very little test coverage for the application. This is totally to be expected since the app is still in a prototyping phase, but it is something we will have to fix before we get too far into active development so that we can use a test-driven approach to keep up code quality. It seems like we have several options:

1. Use the test database slice that Catherine has shared with developers for trying out the app locally. This has the advantage of mimicking what real data would look like in the system because it _is_ real data. The issue is that it's unclear that we can put this data in source control, since that would mean making it public, which means that we can't use CircleCI or any other CI backend to run our tests and validate pull requests (instead, developers would need to locally run tests before PR create and to review PRs and make sure any changes they make to the test DB are synced among all developers). I think this will negatively impact our velocity and we need some way to get an test dataset we can share publicly.

2. In many applications, tests will just start with empty database tables and use factories to create the data structures they need for the specific test and then tear down afterwards. Utilities like [FactoryBoy](https://factoryboy.readthedocs.io/en/latest/) can make this process easier, but it's still complex to set up factories when there are 127 related tables in the database. I think this will take a while to run.

3. A hybrid approach where we start the testing from a database that contains some data (ie, code lookup tables like `refCounty`, `weaponType`, etc.) and perhaps even 1 faked agency or such and then factories to create incidents. This would allow us to avoid recreating data for tables that can be public (ie, they contain values found in the NIBRS reference for instance) but to build specific incidents or such when we need to test certain features.

Just putting all this out here to start a discussion.

**Comment by harrisj** [comment]
So, it seems like #1 is the easiest option in the immediate future, but we might need to switch our CI backend. It looks like Travis CI supports the option to have encrypted files that are not in the repo that we can use to provide the sliced SQL to our tests https://docs.travis-ci.com/user/encrypting-files/ I will look into trying this out

**Comment by catherinedevlin** [comment]
I'm going to add option 1b., which is to find or make an anonymizer that can mangle that test database slice into something that *can* be added to source control.  It loses some of the realism of the actual data slice, and it assumes that such a thing exists or wouldn't be hard to make.

**Comment by harrisj** [comment]
I hear you on 1b. Devils advocate question: do you think we would be okay if we simply altered the names of agencies in `ref_agency` but kept other data relatively unchanged? It might also be good if we could limit to only a few agencies and their incidents?

**Comment by harrisj** [comment]
Okay, after spending some time trying to load the DB as a pre-test fixture, I think I am wasting time that would be better spent elsewhere. So I'm going to propose this:

1. Add instructions to the README on loading a test DB locally from a sample data slicke before you run the tests (going to do that myself). There will not be such a sample DB in the repo yet of course.
2. Look into loading the sample DB on a CI that supports encrypted file storage as part of the steps you run before executing the tests.

**Comment by catherinedevlin** [comment]
Maybe it would be worthwhile to make a task to basically audit the columns in the database, classifying them into

- Totally benign columns, no need to change
- Columns that should be munged/anonymized if they're going into version control
- Columns that are unneeded and problematic, and should simply be removed upon upload (as per #113)

I actually can't remember why we considered some columns dangerous, except for the ones mentioned in #113 - a full NIBRS incident even with agency name still doesn't seem personally identifying as far as I can tell.  How can we get a proper decision on what is and isn't safe to expose?

**Comment by harrisj** [comment]
I think at some point there was a concern that we would have extra information about raw NIBRS reports that would be personally revealing or enable some "mosaic effect" issues. Another fear I suppose is that we would leak numbers before they are official public or that this testing data could be seen as official and final data. But I don't think that was more a general fear than something that was specifically identified as a real problem, and I think the 2015 numbers are out now. I think this would be useful to confirm it is okay now, especially to see if there are concerns not about this specific data, but the API methods we are building to share such data won't be a problem for them in the future

**Comment by harrisj** [comment]
This was all resolved by @catherinedevlin in #125
