### ISSUE TITLE
Ask for CJIS to help with recruitment during the development phase 

### ISSUE THREAD

**Issue by LarryBafundo** [18F/crime-data-api#135]
This is a reminder to talk with Lori and Sammy at CJIS about how they can help us recruit test users during development. Some ideas: post a sign-up form on the FBI/UCR website, or in joint FBI/18F communications, and or ask the Xcelerate team to help provide a base of participants to draw from.

**Comment by LarryBafundo** [comment]
Updated tasks for this issue: 

- [ ]  create a google signup sheet to record the names and contact information of interested participants 
- [ ]  develop supporting text that explains what the project is about, who should sign-up, and how they can help

**Comment by amberwreed** [comment]
Lori suggested that they might provide us with names.
