### ISSUE TITLE
Make Pagination return counts.

### ISSUE THREAD

**Issue by cacraig** [18F/crime-data-api#141]
We need to return real query result counts. These counts can't be obtained easily using a second count query. Investigate other means to return these counts.

**Comment by catherinedevlin** [comment]
I'm thinking seriously now that a cache of count results according to (normalized) query parameters might be our best option there.  It will still have lousy performance the first time any specific combination of query parameters is tried, but should have no measurable impact after that.

My main question is how exactly such a count should be stored.  Some options:

- In a database table:
    - kind of complicating, b/c that makes our read-only DB into read-write for the first time
    - OTOH, since we're already using a DB, it seems weird to have a *second* means of data storage
- In a dict in the server's memory
- In a pickle
- Don't cache the counts separately at all, but do use Varnish immediately for the entire query results

**Comment by cacraig** [comment]
After some initial investigation, it would probably be worthwhile investigating using a WINDOW function to obtain counts.  
  
[over_ratio_limit.pdf](https://github.com/18F/crime-data-api/files/632412/over_ratio_limit.pdf)

The above image is a plot of the Ratio of the base /incidents query, along with the base query with count(*) OVER () -  The X-Axis is LIMIT (0...2700). 

The ratio appears to fit pretty well to log(n) line, suggesting that the impact of the count statement degrades with increasing N or LIMIT. 

[log_N.pdf](https://github.com/18F/crime-data-api/files/632444/log_N.pdf)

Here's the log_10 normalization of the ratio as well.

[over_limit_ratio_log.pdf](https://github.com/18F/crime-data-api/files/632446/over_limit_ratio_log.pdf)

**Comment by cacraig** [comment]
Ugh. Sorry for the PDFs. R defaults to them on export. Didn't realize till after the fact.
