### ISSUE TITLE
Investigate query caching methodologies/mechanisms

### ISSUE THREAD

**Issue by cacraig** [18F/crime-data-api#148]
Right now, queries are really super slow. In order to have a usable API, we need to implement a caching mechanism. Possible tools:

- **Varnish**
- **Redis**

**Comment by catherinedevlin** [comment]
Now that I think about it, I don't think an HTTP cache will solve our main problem.  The rowcount is still far and away the biggest part of most queries, and a query cache will think that `/incidents/` and `/incidents/?page=2` are completely different queries and will want to run the whole rowcount again.  To avoid that, we're going to need to embed some rowcount caching in the API itself.

It still may be worth adding for queries where even the non-rowcount part is slow, I'm just not sure how important that will end up being.

**Comment by harrisj** [comment]
I mean, we can tweak Varnish so it could handle that situation (it can even do CDN-style things where it caches most of the page and inserts a directive). But it does seem to me like Redis would make a little more sense here and I think there are some good examples of people doing DB caching with Redis. Of course, the funny thing about this DB is that you really only ever need to clear the cache when you load a new dataset, so even something with static files might work pretty well (although I guess with Redis you could better do a LRU cache)

**Comment by cacraig** [comment]
Spitballing here...

We can write a script to populate a key store where -> URI => returned JSON.

We could write a script to populate the cache, and run it whenever new data is uploaded to the DB. Then cache big /incidents? queries. Do pagination in the code with the full request (for cached requests only). 

Then for every request that results in a cache miss, populate cache[URI] = JSON. Cache Hit -> return cache[URI]. 

**Concerns:** 
- Given that Redis is an in-memory k-v store, we are limited by RAM. If we try to somehow cache a huge chunk of every possible query, then we are going to probably run into memory limitations.
- Persistence: We'll need to make sure that the cache is dumped to FS every once, and while.

**Comment by harrisj** [comment]
True, although if we are prebaking the cache, we might as well just write it all out to S3? In seriousness though, this is a good idea for when we do load a new dataset, look at the Redis to see what are the popular queries and repopulate those to mitigate a dogpile effect from clearing the cache

**Comment by catherinedevlin** [comment]
In the spirit of "simplest thing that could possibly work", we could cache rowcounts in the API server's memory for this week.  Then reduce cheesiness (and maybe add actual results, not just rowcounts) in future iterations.

**Comment by cacraig** [comment]
This was done in #212 - Aside from that, other caching mechanisms are not needed at this time.
