### ISSUE TITLE
Test Swagger schema generation for ArgumentsSchema

### ISSUE THREAD

**Issue by harrisj** [18F/crime-data-api#153]
This seems like a good test of how Swagger autogeneration tools would work

**Comment by harrisj** [comment]
Currently I am using the [flask-apispec](https://github.com/jmcarp/flask-apispec) package which seems to do an excellent job of both generating the Swagger and Swagger-UI for endpoints from only a few directives like so:

``` python
class IncidentsList(CdeResource):
    @use_args(marshmallow_schemas.ArgumentsSchema)
    @marshal_with(marshmallow_schemas.IncidentsListResponseSchema)
    def get(self, args):
```

This does mean defining some additional Marshmallow schema for return formats, but this seems to be more consistent than including YAML in the doc strings for methods like some other proposals. There are some things that would need to be settled down the road:

- [ ] Putting HTTP Auth in front of the Swagger UI (necessary to deploy before ATO?)
- [ ] Add support for `@use_args` or switch our methods to use `kwargs` (the tool doesn't support that)
- [ ] It would be good to be able to annotate fields with documentation in Marshmallow schemas that show up in Swagger JSON. Same with method descriptions.
- [ ] Styling Swagger UI to be more 508-compliant like FEC (this can be deferred until further down the road)

It might make sense to fork this library so we can make the modifications we need, but it's a promising start

**Comment by catherinedevlin** [comment]
The other trick here is that I think flask-apispec relies on all the possible arguments being in ArgumentsSchema, when in fact we support filtering on fields that are found dynamically in a cdemodels.TableFamily.map (and thus never present in a marshmallow schema)

**Comment by harrisj** [comment]
Hmm, that is a very good point. So it sounds like we would need to manually document the incoming arguments regardless

**Comment by catherinedevlin** [comment]
The idea behind the `.print_map()` method was to output those fields, so maybe they can be dynamically added to a Marshmallow schema before use_args is applied, or fed to flask-apispec some other way.

**Comment by harrisj** [comment]
So I have hacked a way to do this potentially, but it means there are often over 100 possible arguments listed for the endpoint. I would like to figure out a better way to handle this in the long run. In the short run, I just need to get an endpoint running so that the frontend team can test queries out so I will leave that for a future release

**Comment by harrisj** [comment]
This was merged
