### ISSUE TITLE
Add research sprints to wiki

### ISSUE THREAD

**Issue by amberwreed** [18F/crime-data-api#161]
- [ ] Discovery research learnings
- [ ] Prototyping sprint 1
- [ ] Prototyping sprint 2
- [ ] Prototyping sprint 3

**Comment by nicoleslaw** [comment]
As a sidenote, we should probably move our wiki to the new CDE repo since that is going to be the public-facing repo for the website. I can do that as part of this task.

**Comment by nicoleslaw** [comment]
@amberwreed  I moved the wiki to the CDE repo and added notes there. When you have time, please take a look at the Priorities and What we learned sections—and feel free to add anything else you want to include.

cc @LarryBafundo

**Comment by nicoleslaw** [comment]
@amberwreed Have you had a chance to look at this?

**Comment by amberwreed** [comment]
Nope but I'll take a look tomorrow. Thanks for the reminder.

**Comment by LarryBafundo** [comment]
@amberwreed, @nicoleslaw okay to finally close this?

**Comment by amberwreed** [comment]
This is still a goal that I hope to get to.

**Comment by LarryBafundo** [comment]
@amberwreed this seems like an ongoing task. should we just close this out and add a card to update the wiki with the latest documentation after each sprint?
