### ISSUE TITLE
Synthesize treejack results

### ISSUE THREAD

**Issue by amberwreed** [18F/crime-data-api#164]
Review results from treejack test, write a summary of findings, and create action items or recommended changes.

**Comment by nicoleslaw** [comment]
Quick summary:

* People don't understand the difference between trends and snapshots
* Several folks don't know what an API is, wanted more context around that
* We need to be clearer about documentation for this group of data sets v the program

Next steps:

* I will make a task to reorganize the IA as we need to do that anyway based on what we've learned from the last sprint
* We should continue researching what developers/data folks find useful as a signpost for API docs
