### ISSUE TITLE
Add bandit to testing

### ISSUE THREAD

**Issue by harrisj** [18F/crime-data-api#171]
Tool for doing static analysis of Python projects. See [website](https://github.com/openstack/bandit) for details

**Comment by cacraig** [comment]
We'll probably tack this on for the next sprint, it will be a pre-req for the ATO anyways. Thanks, @harrisj

**Comment by harrisj** [comment]
Here is an example of [integrating bandit into the CI](https://github.com/18F/calc/blob/develop/.travis.yml#L30)
