### ISSUE TITLE
Add stage label to any public views including API documentation

### ISSUE THREAD

**Issue by jeremiak** [18F/crime-data-api#187]
From the [ATO checklist](https://pages.18f.gov/before-you-ship/ato/checklist/):
> If this will be a new ATO, add a prominent [`Beta`](https://18f.gsa.gov/dashboard/stages/) label to any currently-running sites

**Comment by harrisj** [comment]
Currently, there are no publicly-accessible pages for the API besides the standard error pages for 404, 500 errors. The documentation is behind a HTTP Auth. Does this still apply? Is there a similar issue for the explorer?

**Comment by LarryBafundo** [comment]
I think this is something we'll have to come back to as we build out the CDE. I'll move it to the backlog since we can't complete it just yet.

**Comment by jeremiak** [comment]
To @harrisj's point, my understanding is that the banner is _NOT_ required for sites that are behind basic authentication. But when we want to get an ATO, and thus move out from behind the auth, we will need such a banner on all public views
