### ISSUE TITLE
Return precise counts if few estimated records

### ISSUE THREAD

**Issue by harrisj** [18F/crime-data-api#197]
Now when you do a search and there are no matches, you get a result like this

``` json
{
  "pagination": {
    "count": 56, 
    "page": 1, 
    "pages": 6, 
    "per_page": 10
  }, 
  "results": []
}
```

This is because the estimated counts are returning the number of rows scanned and the actual number of rows is smaller. We could consider a strategy where if the estimated_count is less than some threshold (perhaps around 1000), we then perform a precise `COUNT(*)` with the assumption it will be relatively fast in comparison

**Comment by cacraig** [comment]
Done in #204
