### ISSUE TITLE
Identify key components to design and build

### ISSUE THREAD

**Issue by amberwreed** [18F/crime-data-api#201]
Use wireframes as a way to identify page components that will need to be designed and built.

**Comment by nicoleslaw** [comment]
I started a doc here, updating based on your wireframes: https://docs.google.com/document/d/1dv6Gm4AGW9Khx4dGoKhiDZxUzeOBe0wqqVWBRl8NSEU/edit# — Feel free to change it, I am not sure what you have in mind but we talked about some of these names yesterday.

**Comment by nicoleslaw** [comment]
@amberwreed Ready to close this out?

**Comment by LarryBafundo** [comment]
let's close this out once we finish sprint 2 and have a better idea of the downloads experience. 

cc: @nicoleslaw, @amberwreed
