### ISSUE TITLE
Design and test downloads page

### ISSUE THREAD

**Issue by amberwreed** [18F/crime-data-api#203]
- [x] Wireframe page
- [x] Work with Nicole to fill in content
- [x] Design page
- [x] Identify questions to ask during research
- [x] Test

**Comment by nicoleslaw** [comment]
Here's a first shot for you:

# Downloads Overview

* Dataset List
  * Dataset Name
  * Dataset Description
  * Metadata
  * Download
  * Links: CSV, API, Documentation
* License
* Feedback/Contribute - GitHub Callout


# Download Detail
* Dataset Description
* Metadata
  * File Size
  * Years (e.g., 1975-2016)
  * Release Date
  * Tags
  * Publisher
  * License
* Links: CSV, API
* About the Data / Documentation

Consider looking at this sample with w3c standards (Dataset Info section): https://www.healthdata.gov/dataset/radon-test-results-county-beginning-1987 

Standard fields are here for more info, but I don't think all of these are required by any means: https://www.w3.org/TR/vocab-dcat/#class-dataset

**Comment by LarryBafundo** [comment]
<img width="677" alt="screen shot 2016-12-20 at 10 01 23 am" src="https://cloud.githubusercontent.com/assets/15899668/21355266/4fcd836a-c69b-11e6-8ab6-82212e1d3161.png">

**Comment by nicoleslaw** [comment]
@amberwreed I think we should include the subsequent page of an individual dataset—I think that will help you see all of the different components we'll aggregate on this view.

**Comment by LarryBafundo** [comment]
we need to think about how we will promote the searchability of the datasets we make available. current assumptions are that users will want to search available data by crime type, location (region, state, population, etc.), and timeframe (10 years).

**Comment by LarryBafundo** [comment]
per conversation with amber, considering 3 different approaches to explore: 

1) a list of the largest data sets (category A & B) organized by crime type & time period 
2) all offenses made organized by time (10 years) and location
3) all offense data shown as table, filterable by type, time, location & NIBRS dimensions

**Comment by nicoleslaw** [comment]
Relatedly, we are mapping out potential premade datasets/CSVs here: https://docs.google.com/spreadsheets/d/1gRN0bjp-2D9OdXtsA53IZsM6inUjBBEzRYK2gbwgGtM/edit?pli=1#gid=249246828

**Comment by nicoleslaw** [comment]
Amber outlined those here: https://docs.google.com/presentation/d/1ihO3gbYsPvpmaI088OlwXrTXkqWxFFZFAevG-wBqzbw/edit#slide=id.g167459c3ce_0_198
