### ISSUE TITLE
Design tables for testing in Sprints 2 & 3 

### ISSUE THREAD

**Issue by AvivaOskow** [18F/crime-data-api#205]
For instances when we don't have enough data to chart, but still should provide what we have. Also for "switch to table view" of charts (TBD if that will be a feature in the mvp)

**Comment by LarryBafundo** [comment]
@AvivaOskow: switch to table view as part of the explorer experience is not a priority for the MVP. but could be something we do later on.

**Comment by LarryBafundo** [comment]
@AvivaOskow: can we think of this ticket as the design work we want to do to ready tables for testing in sprint 3? that way we can create a new one if there are specific refinements we want to make and this ticket won't stay open forever.

**Comment by LarryBafundo** [comment]
@amberwreed okay to close this out ?
