### ISSUE TITLE
View UCR participation at the county-level 

### ISSUE THREAD

**Issue by harrisj** [18F/crime-data-api#211]
It's possible I am asking a dumb question here because I am new to the project but...

This was a map that has been in several prototypes as part of the overview of a state (I really like it!) But is that data provided to us in the DB already? Or is this something we would have to compute (by looking at ORIs mapped to a specific county and a window of time)? What is the window for computing participation against? (1 year, 5 year, 10 years)?

**Comment by LarryBafundo** [comment]
Not a dumb question at all. We've explored the value of such a map in our prototypes, but haven't figured out how to do it yet. I believe that we will need to "derive" this information from available data and come up with an estimate, as it's not something that is directly provided by UCR. 

@catherinedevlin, @cacraig: i believe we've talked about potential approaches for visualizing UCR participation on a map - we will schedule some time for S2 to dive into the details, but in the meanwhile, could we outline an approach here?

**Comment by LarryBafundo** [comment]
@catherinedevlin, @cacraig, @harrisj: related to this topic, do we also need to do research on how we'll visualize county boundaries within a state?

**Comment by harrisj** [comment]
Oops, I hit the wrong button!

**Comment by harrisj** [comment]
We can get [County shapefiles from the Census](https://www.census.gov/geo/maps-data/data/cbf/cbf_counties.html) (probably already part of whatever mapping framework we are using). The question of apportioning by population is a little more complicated, but now that I have some SQL sense in my head, let me see what I can do.

**Comment by harrisj** [comment]
Do you want me to add an endpoint for county level counts then? What should the data look like? Is there a prototype for the CDE that is a good start?

**Comment by harrisj** [comment]
Just to clarify scales, for the data year 2015, there are 23,293 agencies listed and 681 of them span multiple counties. So, this isn't something that applies for most agencies, but it is technically important for some that do. The problem is that the agencies that do span colonies are often city police departments, notably:

|-----------+---------------------------+--------------|
| ori       | ucr_agency_name           | state_abbr   |
|-----------+---------------------------+--------------|
| AL0310900 | ALTOONA                   | AL           |
| AL0010200 | BIRMINGHAM                | AL           |
| AL0500400 | BOAZ                      | AL           |
| AL0470100 | HUNTSVILLE                | AL           |
| AL0010600 | LEEDS                     | AL           |
| CO0010100 | AURORA                    | CO           |
| CO0030200 | LITTLETON                 | CO           |
| GAAPD0000 | ATLANTA                   | GA           |
| GA1380200 | VIDALIA                   | GA           |
| IA0770300 | DES MOINES                | IA           |
| IA0970100 | SIOUX CITY                | IA           |
| IL0849300 | IL DEPT OF NATURAL RESOU  | IL           |
| IL0844200 | ILL COMMERCE COMMISSION   | IL           |
| IL0849700 | ILLINOIS STATE POLICE     | IL           |
| IL0990700 | JOLIET                    | IL           |
| IL1010400 | ROCKFORD                  | IL           |
| LA0090100 | SHREVEPORT                | LA           |
| MI1831300 | CLARE                     | MI           |
| MI3351900 | LANSING                   | MI           |
| MO0260100 | JEFFERSON CITY            | MO           |
| MOKPD0000 | KANSAS CITY               | MO           |
| MS0250100 | JACKSON                   | MS           |
| NC0680100 | CHAPEL HILL               | NC           |
| NC0920100 | RALEIGH                   | NC           |
| NC0920700 | WAKE FOREST               | NC           |
| NV0131300 | STATE FIRE MARSHAL        | NV           |
| OHCOP0000 | COLUMBUS                  | OH           |
| OH0250300 | DUBLIN                    | OH           |
| OK0550600 | OKLAHOMA CITY             | OK           |
| OK0720500 | TULSA                     | OK           |
| OR0260200 | PORTLAND                  | OR           |
| OR0240200 | SALEM                     | OR           |
| SC0100100 | CHARLESTON                | SC           |
| SC0400100 | COLUMBIA                  | SC           |
| TN0010300 | OAK RIDGE                 | TN           |
| TX1880100 | AMARILLO                  | TX           |
| TX2270100 | AUSTIN                    | TX           |
| TXDPD0000 | DALLAS                    | TX           |
| TX2201200 | FORT WORTH                | TX           |
| TXHPD0000 | HOUSTON                   | TX           |
| TX0430600 | PLANO                     | TX           |
| TXSPD0000 | SAN ANTONIO               | TX           |
| UT0220500 | PARK CITY                 | UT           |
| WV0350100 | WHEELING                  | WV           |
|-----------|---------------------------|--------------|

That said, there are some things that make me a little concerned I am either querying wrong or the data is wrong. For starters, New York City spans 5 counties and it isn't in there. Also, is every police department in California neatly within county borders?

In other weirdness, I looked at the Chicago PD and from the year 2000 - 2009, it was listed as spanning both Cook County as well as Dupage County, IL. In 2000, the covered population in Cook County was 2,896,014; the covered population in Dupage was 2. After 2009, it's been entirely within Cook County again

**Comment by cacraig** [comment]
@harrisj 2-3% of the agencies may be significant enough to pursue this now. - However, my one concern is that we are not the authoritative source on this data. We should make sure we use the exact method that the FBI uses to derive county by county counts when agencies span mult. counties.

**Comment by harrisj** [comment]
Agreed. In my ideal world, the FBI would just give us a table that would basically be keyed by `county_id, offense_subcat_id, month, year` with a count and we could just query that to get what we need and they would do the computation. I get the sense that they don't have that table derived anywhere yet.

So, one thing I also wanted to note is that I think we decided that county-level statistics would be derived from the RET A (aka SRS) data and not NIBRS data like I suggested above

**Comment by jeremiak** [comment]
Could we provide county level data for both SRS and NIBRS data?

**Comment by harrisj** [comment]
I believe so. The mapping is done at the agency level rather than the incidents (hence our consternation about the right way to split it), and both the ret_a and nibrs incidents use the same `ref_agency` table

**Comment by harrisj** [comment]
Okay, here is the plan. The idea is to create a county multiplier table `cde_county_multiplier` that can be used for multiplying the crime counts for a given agency in a county. So the table would be these columns

- agency_id
- data_year
- county_id
- multiplier (a float between 1 and 0)

To keep it smaller, there would not be a multiplier for agencies that aren't split.

For a given data year, we can find the agencies that are split between counties with the following SQL

``` sql
SELECT ref_agency.agency_id
FROM ref_agency
JOIN ref_agency_county a1 ON a1.agency_id = ref_agency.agency_id
JOIN ref_agency_county a2 ON a1.agency_id = a2.agency_id AND a1.data_year = a2.data_year
WHERE a1.data_year = YEAR
AND a1.population > 0
AND a2.population > 0
AND a1.county_id <> a2.county_id
```

The population check is because sometimes agencies are mapped to special UNASSIGNED COUNTY districts with a population of 0 on the mapping so we should ignore them.

Once we have this list of agencies in a given year, we can get the county totals like so

``` sql
SELECT ref_agency.agency_id, a1.data_year, SUM(a1.population)
FROM ref_agency
JOIN ref_agency_county a1 ON a1.agency_id = ref_agency.agency_id
JOIN ref_agency_county a2 ON a1.agency_id = a2.agency_id AND a1.data_year = a2.data_year
AND a1.population > 0
AND a2.population > 0
AND a1.county_id <> a2.county_id
GROUP BY(ref_agency.agency_id, a1.data_year)
```

Then transform into the final table

```sql
SELECT a.agency_id, a1.data_year, a1.county_id, a1.population, SUM(a1.population)
FROM ref_agency a
JOIN ref_agency_county a1 ON a1.agency_id = a.agency_id
JOIN ref_agency_county a2 ON a1.agency_id = a2.agency_id AND a1.data_year = a2.data_year
AND a1.population > 0
AND a2.population > 0
AND a1.county_id <> a2.county_id
AND a1.data_year=2015
GROUP BY(a.agency_id, a1.data_year)
```

but it turns out there is something called window functions and we can use them to just build the whole table

``` sql
SELECT a.agency_id, ac.data_year, ac.county_id, ac.population, ac.population/sum(ac.population)
OVER (PARTITION BY a.agency_id, ac.data_year)
FROM ref_agency a
JOIN ref_agency_county ac ON ac.agency_id = a.agency_id
AND ac.population > 0
```

Sample output

|   agency_id |   data_year |   county_id |   population |    scale_factor |
|-------------|-------------|-------------|--------------|-------------|
|           1 |       2,015 |           5 |      301,239 | 1           |
|           2 |       2,015 |          10 |       32,677 | 1           |
|           3 |       2,015 |          13 |       32,482 | 1           |
|           4 |       2,015 |          15 |        8,286 | 1           |
|          50 |       2,015 |          71 |       26,828 | 1           |
|          51 |       2,015 |          71 |      210,515 | 0.991634    |
|          51 |       2,015 |          92 |        1,776 | 0.00836588  |
|          52 |       2,015 |          71 |       20,801 | 1           |
|          55 |       2,015 |          93 |        1,981 | 0.165428    |
|          55 |       2,015 |          71 |        9,884 | 0.825386    |
|          55 |       2,015 |          92 |          110 | 0.0091858   |
|          56 |       2,015 |          71 |        5,240 | 1           |

Or we could build a subset on demand if we want to scale offenses for a given query

**Comment by LarryBafundo** [comment]
@harrisj we are deferring the county-level perspective for later releases; it will not be part of the MVP. in that case, should we move this issue to the backlog for future consideration? we still need to figure out how compute participation rate, but for individual states and more broadly at the national level. i know you're looking into that, but is that task better represented as a separate issue?

**Comment by harrisj** [comment]
We should move it to the backlog.

This issue actually covers three different problems as far as I can tell:

1. How do we calculate NIBRS participation (now handled by #291)
2. How do we scale crimes proportionally when agencies are in multiple counties?
3. How do we render county borders on the map?

I still have some interest in #2, but it's not needed now of course

**Comment by LarryBafundo** [comment]
moved to the backlog

**Comment by LarryBafundo** [comment]
hey @harrisj can we close this out?

**Comment by harrisj** [comment]
Yes, will close.

**Comment by crossonrose** [comment]
I don't know how to.
