### ISSUE TITLE
Cache JSON for incidents

### ISSUE THREAD

**Issue by catherinedevlin** [18F/crime-data-api#212]
Whereas 

- a large amount of database time is spent on all the joins necessary to assemble a deeply nested incident record
- Marshmallow is taking a while to render the records as JSON
- The JSON for each incident is the same every time

*Be it resolved* this sixteenth day of December that we try caching the JSON for each NIBRS_INCIDENT record in a 1:1 database table.  Hopefully that will provide a big performance improvement.

**Comment by catherinedevlin** [comment]
If this succeeds, together with #214, they may remove the need for #148, #149, #150, #151.

**Comment by LarryBafundo** [comment]
@catherinedevlin can we get an update on this one too please?

**Comment by cacraig** [comment]
@LarryBafundo - This is working, and good to go. We have to merge it in. However, we're holding off on that until we can switch the DB over because it depends on that.
