### ISSUE TITLE
Try analytic cubes for summary tables

### ISSUE THREAD

**Issue by catherinedevlin** [18F/crime-data-api#213]
Performance is poor on summary tables (RETA, arson, etc.) because each request requires summing over large numbers of rows.  Storing cubes (https://www.postgresql.org/docs/9.5/static/cube.html) may be an excellent alternative.

If this succeeds, together with #212, they may remove the need for #148, #149, #150, #151.

**Comment by cacraig** [comment]
Interesting. I've never used cubes - What are the dimensions here? Are there any examples of this being used for counts?

**Comment by cacraig** [comment]
Done.
