### ISSUE TITLE
Add a system security plan to the repo

### ISSUE THREAD

**Issue by LarryBafundo** [18F/crime-data-api#227]
The system security plan (SSP) is one of the key artifacts we should submit by the end of the year in order to stay on pace for a March ATO. The SSP provides an overview of the security requirements of the system and describes the controls in place or planned for meeting requirements.

We may be able to use the architectural diagrams that we've already created in earlier presentations (see deliverables: https://drive.google.com/drive/u/1/folders/0Bzo0lr4igOKWMFQ1M1ExR2ZwOEk); otherwise, infrastructure recommends a tool called Compliance Masonry. 

For more information on SSPs please see: https://pages.18f.gov/before-you-ship/ato/ssp/#template

**Comment by LarryBafundo** [comment]
@cacraig okay to close this?

**Comment by cacraig** [comment]
Yep!
