### ISSUE TITLE
Setup compliance masonary documentation

### ISSUE THREAD

**Issue by LarryBafundo** [18F/crime-data-api#229]
This tasks involves the following: 

- [ ]  install compliance masonry CLI
- [ ]  create an opencontrol.yaml based on the data below: 

schema_version: "1.0.0"
name: Your_Application_Name # Name of the project
metadata:
  description: "A description of the application"
  maintainers:
    - maintainer_email@email.com
components: # A list of paths to components written in the opencontrol format for more information view: https://github.com/opencontrol/schemas
  - ./your_app_component
dependencies:
  systems:
    - url: https://github.com/18F/cg-compliance
      revision: master

- [ ]  create component documentation using the opencontrol schema and update the components object in the opencontrol.yaml with the documentation path.
- [ ] import the cloud.gov dependencies

For more information please view: https://github.com/18F/cg-compliance#starting-ato-documentation-for-cloudgov-applications

**Comment by LarryBafundo** [comment]
@cacraig can you add a note here (at least for my benefit) that explains when we'll be in a position to tackle this? 

in the meanwhile, i'm moving it back to the backlog.

**Comment by cacraig** [comment]
We are in pretty good shape now. So we can tackle this anytime really. I'd like some clarification as to whether we need to do with for just the consumer facing stuff or the back end (API) or both.

**Comment by LarryBafundo** [comment]
okay thanks. let's ask during the meeting with holly and jez later today

**Comment by LarryBafundo** [comment]
this is no longer applicable
