### ISSUE TITLE
Map out the MVP premade datasets for download view 

### ISSUE THREAD

**Issue by nicoleslaw** [18F/crime-data-api#233]
initial thoughts here are that we want to provide larger datasets for download that would take time to generate on the fly, as well as secondary data sets that aren't highlighted in the core explorer experience.

**Comment by LarryBafundo** [comment]
working file here: https://docs.google.com/spreadsheets/d/1gRN0bjp-2D9OdXtsA53IZsM6inUjBBEzRYK2gbwgGtM/edit#gid=249246828

**Comment by harrisj** [comment]
What else do you need me to do for this one?

**Comment by LarryBafundo** [comment]
let's revisit this - moving out of the current sprint and into the backlog.
