### ISSUE TITLE
Define key queries and desired threshholds

### ISSUE THREAD

**Issue by catherinedevlin** [18F/crime-data-api#239]
List queries we want to prioritize, as the app's most important expected queries, and quantify how fast we need each one to return to consider it "acceptable performance".

**Comment by jeremiak** [comment]
From looking at the designs (such as #248), and thinking through the front end app more, I know that we'll need to make the following queries for both SRS and NIBRS based data:

* the place - this is a US state to start with
* a time range - Using `incident_date` on `/incidents`, for instance
* a crime - all group A offenses in addition to some of the special flags, such as hate crime
  - All violent crime
  - Murder
  - Rape
  - Robbery
  - Aggravated assault
  - All property crime
  - Arson
  - Burglary
  - Theft
  - Larceny Theft
  - Motor Vehicle Theft
  - Hate Crime
  - Human Trafficking
  - Law Enforcement Officers Killed and Assaulted (LEOKA)

Some questions I have about the current endpoints:
0. How can I filter with date parameters on the summary data endpoint (`/incidents/count`)?
0. How would I get data based on incident level flags aggregated by year? For example, if I wanted to get all the data for hate crime or cargo theft would I just use the `/incidents` endpoint with the `hc_flag=Y` parameter and then do a by year aggregation on the client?

**Comment by jeremiak** [comment]
This seems like a very low priority at this point. @LarryBafundo what would you like to do with this issue? We can move it back or we can just close it and open a new one when we have very specific API performance improvements?

**Comment by LarryBafundo** [comment]
I think i would like us to create an epic for API optimizations that we can assign issues against and prioritize for sprints. so i'll move this to the backog and we can rope it in later.
