### ISSUE TITLE
Return schema are not being put in the Swagger definitions section

### ISSUE THREAD

**Issue by harrisj** [18F/crime-data-api#240]
This is not something that has to be fixed before the MVP

I noticed that the `flask-apispec` library is inlining all the Marshmallow schema within the API responses rather than defining them as named schema within the `definitions` section of the swagger JSON file. Not sure why, but this isn't really the best way to do it and should be fixed if possible

**Comment by LarryBafundo** [comment]
@harrisj is this still an issue?

**Comment by harrisj** [comment]
Yes, it seems like upgrading the library didn't make any difference. I think I would fix this if we switched to a hand-edited Swagger JSON

**Comment by harrisj** [comment]
Fixed by https://github.com/18F/crime-data-api/pull/435
