### ISSUE TITLE
Explore - navigate to state data by selecting a state on the map 

### ISSUE THREAD

**Issue by LarryBafundo** [18F/crime-data-api#241]
As a user, I want to view a map of the United States and navigate to a specific state’s crime data by clicking on it.

**Comment by amberwreed** [comment]
[https://drive.google.com/open?id=0B5cw7Ca2CjsyeUtDYno0czRGdms](url)

**Comment by amberwreed** [comment]
![left hand filter navigation](https://cloud.githubusercontent.com/assets/13576520/21669507/24a8f458-d2c1-11e6-9ff9-a422d8d79da8.png)
