### ISSUE TITLE
View crime data for counties (epic: place holder) 

### ISSUE THREAD

**Issue by LarryBafundo** [18F/crime-data-api#242]
As a user, I want to view a county-based map of the state I am viewing and navigate to a specific county’s crime data by clicking on it.

**Comment by harrisj** [comment]
The question is, do we need this to include functionality for #211? Or can we just ignore agencies that span multiple counties for now?

**Comment by LarryBafundo** [comment]
TO DO: will break this concept into specific user stories based on the finalized design
