### ISSUE TITLE
Search by city from the homepage

### ISSUE THREAD

**Issue by LarryBafundo** [18F/crime-data-api#244]
As a user, I want to view crime data for a specific location by entering the name of the state, city, or county I want to view

question: we heard during user testing that some people find searching by city-name more intuitive than county. can we show results for cities by associating them with counties? if so, how will we handle cases where a city spans multiple counties?

**Comment by harrisj** [comment]
Just wanted to note here the FBI supports two other different levels of granularity on location independent of the state-county-city most people are familiar with:

- Many urban agencies are mapped to a `ref_metro_division` that represents the specific urban area they are located in. Note that a metro division might span multiple real cities or states. For instance, NYC is part of the `New York-Jersey City-White Plains, NY-NJ` metro division which includes White Plains and parts of New Jersey as well (410 total agencies in all). The ref_metro_division does give us a way to identify _important_ cities with a specific state or county I suppose, but metro divisions are fuzzier than city boundaries (the DC one includes neighboring counties for instance)
- Metro divisions in turn are mapped into larger [Metropolitan Statistical Areas](https://en.wikipedia.org/wiki/Metropolitan_statistical_area) which can be quite large. The NYC MSA is made up of 4 metro divisions for instance: `Dutchess County-Putnam County, NY, Nassau County-Suffolk County, NY, New York-Jersey City-White Plains, NY-NJ, Newark, NJ-PA` and constitutes 735 distinct agencies.

I'm not sure if any of these categories matters except to people who are interested in contrasting urban regions with each other, but I just wanted to note them for completeness.

**Comment by harrisj** [comment]
So, how do we want to implement this? Do we need a `location` search API method? Should it accept some level of scoping or such?

**Comment by LarryBafundo** [comment]
While we know that prospective users are interested in as much granularity of the data as possible, we haven't yet committed to delivering anything lower than a state perspective for the MVP. For now, let's scope this task as being able to search by state name and the District of Columbia. 

However, we should this implement this in a way that allows us to scale the solution in future iterations and accommodate more granular searches, like county and city names. 

cc: @amberwreed, @harrisj

**Comment by jeremiak** [comment]
I think we should close this. We have agreed that states are the geographical entity that we will use for the MVP and that a `<select>` implementation is sufficient to start.

**Comment by LarryBafundo** [comment]
reopened this as we may need to incorporate a search function for reporting entities other than states. will also rename as such.

**Comment by LarryBafundo** [comment]
it doesn't seem like this issue will ever be relevant.

**Comment by jeremiak** [comment]
In that case, @LarryBafundo, it seems like we should close it
