### ISSUE TITLE
Explore - search by available crime type 

### ISSUE THREAD

**Issue by LarryBafundo** [18F/crime-data-api#246]
As a user, I want to view data for a specific type of crime by selecting from a list of available crime types and offenses.  

Within the explorer view, this means summary category A offenses only.

**Comment by harrisj** [comment]
Once #160 is merged, the frontend should be able to do a call to `/codes/reta_offense` on the API to get a list of all the RET A offenses and their codes

**Comment by jeremiak** [comment]
Trying to use the API endpoint from above, but getting two different types of errors (API key withheld)

* https://crime-data-api.fr.cloud.gov/codes/reta_offense/ returns a 404 error
* https://crime-data-api.fr.cloud.gov/codes/reta_offense returns a 500/Server error

**Comment by harrisj** [comment]
Oops, this needs #260 to be merged

**Comment by jeremiak** [comment]
This is done, with any remaining styling to be done represented by [crime-data-explorer#105](https://github.com/18F/crime-data-explorer/issues/105)
