### ISSUE TITLE
Explore - view a title and description for the location or crime type I am viewing 

### ISSUE THREAD

**Issue by LarryBafundo** [18F/crime-data-api#247]
As a user, I want to read a short description of the location or crime type I am viewing so that I can more easily interpret the contents of the page.  

This pertains to the introductory text we are planning to show at the top of the page that would provide context around the location or type of crime the user is viewing.

**Comment by amberwreed** [comment]
![crime collection](https://cloud.githubusercontent.com/assets/13576520/21668746/94509444-d2b9-11e6-8961-6d2cbb200ab2.jpg)

**Comment by amberwreed** [comment]
[https://drive.google.com/open?id=0B5cw7Ca2CjsyQXBzUEQzM3Fhcjg](url)

**Comment by LarryBafundo** [comment]
i'm closing this due to the existence of https://github.com/18F/crime-data-explorer/issues/97
