### ISSUE TITLE
Explore - style census component to match design

### ISSUE THREAD

**Issue by LarryBafundo** [18F/crime-data-api#248]
As a user, I want view related census data for the location I am viewing.

**Comment by jeremiak** [comment]
@amberwreed could you post the design for the census block from the mobile display for now?

**Comment by amberwreed** [comment]
![crime collection](https://cloud.githubusercontent.com/assets/13576520/21668712/581c5fda-d2b9-11e6-9f9a-4346e3d897eb.jpg)

**Comment by amberwreed** [comment]
@nicoleslaw @LarryBafundo I think this can be closed based integrating census data into the overview.

**Comment by jeremiak** [comment]
Closing per ^^
