### ISSUE TITLE
Explore - trends chart 

### ISSUE THREAD

**Issue by LarryBafundo** [18F/crime-data-api#249]
As a user, I want to view a chart that shows the overview or trend for the location and crime type I am viewing.

**Comment by amberwreed** [comment]
![trend_chart_1 4 16](https://cloud.githubusercontent.com/assets/13576520/21658891/25f434c4-d27d-11e6-8fe1-cef314ccf37c.png)

**Comment by amberwreed** [comment]
![option 1](https://cloud.githubusercontent.com/assets/13576520/21668647/ae958b58-d2b8-11e6-93b9-781827ce542a.png)

**Comment by amberwreed** [comment]
[https://drive.google.com/open?id=0B5cw7Ca2CjsyZ19mUGxuSFFXLXM](url)

**Comment by jeremiak** [comment]
@brendansudol what do you think about closing this and opening more discrete bits of work as they are required? I think you already did most of this implementation
