### ISSUE TITLE
18F api-standards compliance

### ISSUE THREAD

**Issue by catherinedevlin** [18F/crime-data-api#25]
https://github.com/18F/api-standards

_Partial_ task list (more in the standards: 
- [ ] Support bulk downloads (without pagination?)
- [ ] Support incremental download ("records added or changed since...")
- [ ] Records in consistent order
- [x] Responses should be a JSON object (not an array) with metadata
- [ ] ISO 8601 date format, like 2013-02-27T10:00:00Z.
- [ ] Use consistent case for keys
- [ ] Errors handled and return data structure
- [ ] HTTPS
- [ ] UTF-8

**Comment by LarryBafundo** [comment]
@catherinedevlin: could you please update the checklist, in the event that we've made progress on some of these items?

**Comment by LarryBafundo** [comment]
@cacraig can you please update this list to reflect our level conformance with 18F's standards?
