### ISSUE TITLE
Explore - view incident detail charts 

### ISSUE THREAD

**Issue by LarryBafundo** [18F/crime-data-api#252]
As a user, I want to view selected incident details for the crime type and location I am viewing.

**Comment by amberwreed** [comment]
![offense](https://cloud.githubusercontent.com/assets/13576520/21668683/f210da90-d2b8-11e6-84e1-1f0aa1297d7e.jpg)

**Comment by amberwreed** [comment]
Offense with no trend chart:
![hate crime_nibrs only](https://cloud.githubusercontent.com/assets/13576520/21668691/0f3be8d0-d2b9-11e6-94ed-faded6c8148d.jpg)

**Comment by amberwreed** [comment]
^^ Still working on table design.

**Comment by jeremiak** [comment]
What should we show if there isn't any or nearly enough (exactly what means is still to be determined) NIBRS data? Do we have a sense of what we want to show in its place?

**Comment by amberwreed** [comment]
Here's a link to the possible NIBRS attributes by summary crime: https://docs.google.com/spreadsheets/d/1gRN0bjp-2D9OdXtsA53IZsM6inUjBBEzRYK2gbwgGtM/edit#gid=908372027

**Comment by AvivaOskow** [comment]
![page view_1 11 17](https://cloud.githubusercontent.com/assets/21244661/21855457/a3f72a38-d7ec-11e6-86ef-848e719375ba.jpg)

**Comment by AvivaOskow** [comment]
![nibrs chart](https://cloud.githubusercontent.com/assets/21244661/21865178/03155262-d813-11e6-8986-c47fff1e987c.jpg)

**Comment by AvivaOskow** [comment]
![nibrs chart_1 11 17](https://cloud.githubusercontent.com/assets/21244661/21870921/0580c3a0-d82d-11e6-90f6-045066cb3a52.jpg)

**Comment by AvivaOskow** [comment]
<img width="448" alt="screen shot 2017-01-11 at 6 37 19 pm" src="https://cloud.githubusercontent.com/assets/21244661/21870936/0e667e4c-d82d-11e6-9da8-06ceac2be1a9.png">

**Comment by jeremiak** [comment]
I believe this is done. Right now there is no y axis on the chart, and I have opened a new issue for that [18f/crime-data-explorer#134](https://github.com/18F/crime-data-explorer/issues/134)
