### ISSUE TITLE
Estimate file size for likely data sets made available for download  

### ISSUE THREAD

**Issue by LarryBafundo** [18F/crime-data-api#261]
As we design the data download experience, we need to better understand the file size of potential data sets we would like to make available. For example, is it feasible for us to make all of violent crime available for download as a CSV, or do we need to segment violent crime by specific offense and or timeframe. 

Nicole has listed the data sets we may want to make available in this spreadsheet here: https://docs.google.com/spreadsheets/d/1gRN0bjp-2D9OdXtsA53IZsM6inUjBBEzRYK2gbwgGtM/edit?pli=1#gid=249246828

We should estimate the number of counts/rows for each data set to get a sense of potential file size.

**Comment by LarryBafundo** [comment]
We can math it out to figure out how many rows to limit requests to.

[11:11]  
(255 max rows) * (30 chars) * (1 byte/char) = 7650 bytes per row

[11:11]  
That's an upper bounds

**Comment by LarryBafundo** [comment]
working file here: https://docs.google.com/spreadsheets/d/1gRN0bjp-2D9OdXtsA53IZsM6inUjBBEzRYK2gbwgGtM/edit#gid=249246828

**Comment by harrisj** [comment]
I'm not sure if this should still be open or not
