### ISSUE TITLE
Clarify discrepancies between the ct_incident and nibrs_incident table

### ISSUE THREAD

**Issue by harrisj** [18F/crime-data-api#266]
So, it seems like the `ct_incident` table is supposed to be details about cargo thefts in the `nibrs_incident` table if I understand correctly, but there are some discrepancies in the counts

|Query|Rows|
|------|-----|
|ct_incident count|4052|
|nibrs_incident cargo_theft_flag='Y'|7859|

There is a `nibrs_incident_id` column on the `ct_incident` table, but when I attempt to join the two, it returns 0 results, because it seems like it's set to NULL in the table. Not sure if that is how they provided the data to us or we had NULLed it out as a precaution. In any event, that is a pretty wide discrepancy between the two counts, and I would like to clarify which we are supposed to use. Are the `ct_incident` incidents the verified and documented cargo thefts and the flagged `nibrs_incidents` might include incidents that are disqualified as cargo theft?

**Comment by catherinedevlin** [comment]
Clarifying info from Justin's email of 12/22:

> some states submit HC and CT outside of NIBRS.

That would certainly explain having more CT_INCIDENT than NIBRS_INCIDENT.  I don't exactly understand the reverse... I'm afraid all four options are available to agencies: report cargo theft via both NIBRS and CT, report only via CT, only via NIBRS, or don't report it at all.

> For CT and HC, the ORI and Incident Number should be the same between NIBRS and Summary.  SHR Incident Numbers are only sequence numbers.

I think that means ORI+Incident Number is our only available "foreign key" between CT or HC and NIBRS.  And that there's no way to join a SHR record to NIBRS.  That seems wrong.  I'll ask him to clarify.

> The NIBRS_INCIDENT_ID fields in the summary tables are artifact from the NIBRS to Summary conversion. You don’t have any populated for 2 reasons:

> 1 – It only gets populated when NIBRS to Summary is run converting all of the data. The dump you have was converted on the mainframe.

> 2 – <Insert Conspiracy Theory here>!

So we should ignore the presence of those fields; they're not going to contain any useful info.

**Comment by harrisj** [comment]
Thank you for reminding of the email I read too but I obviously did not comprehend. It does seem like we are going to need some means to join on the two like you say, if we are to avoid duplicates for situations where some states submit both. Data is fun, isn't it?

**Comment by LarryBafundo** [comment]
@harrisj is this still a question?

**Comment by harrisj** [comment]
I think this remains an open question since one is so far off from the other. I think we will be using ct_incident, but I do wonder why it's so far off from the other table.

**Comment by LarryBafundo** [comment]
@harrisj okay to close this item based on our conversation about cargo theft with CJIS earlier today?

**Comment by harrisj** [comment]
Agreed to close.

To recap the discussion, some agencies have their NIBRS submissions set so that every offense that could potentially be a NIBRS offense (there is a `ct_flag` on the `nibrs_offense_type` to indicate that it's a potential cargo theft) is accidentally counted as an actual offense. Many of these are not, so the `ct_incident` table is what we should use if we wanted to derive cargo theft counts.

**Comment by harrisj** [comment]
To further clarify, the ct_incident table was also overreported and the FBI has instead provided us with some manual files to load for cargo theft data. The issue was that some agencies were misconfigured so that if a type of offense involved a property type with a flag indicating it could potentially be part of a cargo theft it was counted as a cargo theft whether it met the criteria or not.
