### ISSUE TITLE
The `/incidents/<nibrs:id>` endpoint doesn't seem to be working

### ISSUE THREAD

**Issue by harrisj** [18F/crime-data-api#267]
Doing a query like `http://localhost:5000/incidents/?incident_id=73973062` works but doing `http://localhost:5000/incidents/73973062/` returns nothing. Do we still want the latter to be an API endpoint? I suppose this isn't really needed until the Explorer lets you look at a specific NIBRS incident though.

**Comment by LarryBafundo** [comment]
i thought we got rid of the NIBRS IDs?

**Comment by harrisj** [comment]
The `nibrs_incident` column is a DB-only index number that is necessary for joining several tables together. We did scrub the following fields that are part of the NIBRS reporting system (independent of the DB index):

- did
- ddocname
- ff_line_number

The `did` is a Document ID and I think that is the true NIBRS numbers of the case and that is what we are scrubbing.

**Comment by catherinedevlin** [comment]
Thanks, @harrisj - https://github.com/18F/crime-data-api/pull/268 fixed this.

**Comment by harrisj** [comment]
This was fixed. Closing
