### ISSUE TITLE
Prepare for & conduct content workshop

### ISSUE THREAD

**Issue by amberwreed** [18F/crime-data-api#272]

**Comment by nicoleslaw** [comment]
Ideas for topics:

- Activities so far
- Goals, audiences, and principles
- Voice and tone (Madlibs exercise)
- Web style basics
- Key caveats (cardsorting exercise) 
- Pair writing exercises
  - Descriptions
  - About page

**Comment by nicoleslaw** [comment]
Slides in progress: https://docs.google.com/presentation/d/14AZZTSrbGRhkw-hS3VogJaM2CfgDicVQmB65hSfm5j8/edit#slide=id.p

Outline: https://docs.google.com/document/d/1nfZclLeVs9EIn2xWpwNLRn0Fa1_Zzyh9KE7x9zK31Ws/edit#
