### ISSUE TITLE
CSV Output Improvements + Pre-Generated reports.

### ISSUE THREAD

**Issue by cacraig** [18F/crime-data-api#274]
Based on the feedback about the CSV downloads, we need to investigate the following:

- Offload really large reports to S3. Include links on a download (directly to the S3 bucket) for these files. We have discussed creating a file for each State. Which would yield ~50 <1GB CSV downloads. 

- Include an option in the API to Inner join tables, rather than outer join. This is because a data analyst would throw away fields with missing categorical data. We can save them a step. 
    - For example: &clean_asr = True would inner join ASR tables. 

- CSV output modifications:
    - (1) Remove blank, or non-useful columns.
    - (2) Reorder columns by segment: 
<img width="669" alt="screen shot 2016-11-10 at 11 52 58 am" src="https://cloud.githubusercontent.com/assets/3621157/21570056/7665b676-ce90-11e6-9902-63c6855912cb.png">

    - (3) Re-Name columns following some heuristic like -> Offense_0 Name.

**Comment by LarryBafundo** [comment]
@cacraig let's use this issue to document the likely infrastructure costs of hosting pre-prepared statewide incident reports on S3. 

Per slack: 

https://aws.amazon.com/govcloud-us/pricing/s3/
If we had 20 GB, and ~2000 download requests per month -> ~$5-10 a month

**Comment by LarryBafundo** [comment]
this issue appears to be out of date with the latest information (storage costs aside) so closing for now
