### ISSUE TITLE
Census data endpoint

### ISSUE THREAD

**Issue by jeremiak** [18F/crime-data-api#279]
We'll need a new endpoint to get census data about a location (#248). @brendansudol and I will come up with some JSON we want based on the design.

**Comment by harrisj** [comment]
So, it looks like the "census" data we need is actually already within the FBI database. Based on a mockup I've seen the following fields for a county:

- agency participation rate within state/county
- # agencies
- # residents
- # police officers
- # peace officers

The FBI CDE includes several `ref_` tables with basic information. Agencies are mapped directly to counties for a given data year (and thus also to states through counties, so we can figure the count pretty easily). I still have to identify the proper way to indicate participation, but that should be doable too.

The `ref_county_population` table contains the population for a specific county in a given year. Similarly, the `ref_state_population` returns the population for a specific state.

The `pe_employee_data` table reports the number of male and female civilians and police officers employed by a given agency in a data year. We can sum up the counts for all agencies in a state or county to get the total number of police officers. We should clarify that this police number is for actual police officers and not general peace officers. I'm not sure yet how to get peace officers though.

**Comment by harrisj** [comment]
Peace officers is a general term for various law-enforcement roles that aren't necessarily police (ie, this might include corrections officers, arson inspectors, tax and fraud investigators, etc.). What bothers me is that [the definition seems to vary from state to state](https://en.wikipedia.org/wiki/Law_enforcement_officer). It looks like [we could get this information from other places](https://www.bjs.gov/content/pub/pdf/csllea08.pdf), but it might lag the other figures by several years (the CSSLEA is more accurate but only conducted once every 4 years)

**Comment by harrisj** [comment]
See #291 for questions about participation rates

**Comment by LarryBafundo** [comment]
within the explorer view we're going to refer to these fine folks, police/peace officers, as simply "officers."

**Comment by nicoleslaw** [comment]
re ^ https://github.com/18F/crime-data-explorer/pull/123

**Comment by jeremiak** [comment]
Which endpoint is this data returned in? Making a request to `https://crime-data-api.fr.cloud.gov/incidents/count/?state=OH` does not return data with population counts

**Comment by harrisj** [comment]
I have added some endpoints `/geo/states/OH` and `/geo/counties/` too that has that information, but it's not in the /incidents/count endpoint yet. I suppose it could be added to that endpoint too. I still need to do the population like in #290
