### ISSUE TITLE
Incorporate data.gov API key?

### ISSUE THREAD

**Issue by catherinedevlin** [18F/crime-data-api#28]
Right now an "API key" is enforced very cheesily by checking against an environment variable.  (See verify_api_key in crime_data/common/base.py).  Supporting proper data.gov API keys would be far better.

**Comment by harrisj** [comment]
I have emailed the api.data.gov team about seeing how we could use them for API keys. Will update details here when I receive them.

**Comment by harrisj** [comment]
Here are the directions for setting up a new API https://github.com/18F/api.data.gov/wiki/User-Manual:-Agencies#configuring-your-first-api-backend

**Comment by harrisj** [comment]
Is the goal here to front the crime-data-api with an api.data.gov URL? Or just to use it for key generation/management/etc? Is the latter even supported by api.data.gov?

**Comment by harrisj** [comment]
I have generated config and have a special group so that only specific users can use the API via data.gov, but I was wondering how much a priority this is and how we expect this to look

**Comment by harrisj** [comment]
This is partially completed, but I could get it done within a sprint if it's a priority. It would mean generating a new API key for the app and changing the endpoints that are called

**Comment by harrisj** [comment]
This issue has been deprecated in favor of https://github.com/18F/crime-data-explorer/issues/351
