### ISSUE TITLE
Consider new names for /incidents/count endpoint?

### ISSUE THREAD

**Issue by jeremiak** [18F/crime-data-api#281]
When using the API, it is a bit confusing when I would be getting data from a Return A/summary source and when the API response is based on NIBRS data. I think the reason is that the URL structure tries to obscure the difference between summary and NIBRS from the user (which I support!) but `/count` doesn't really resonate with me.

Would you all consider changing the name of this endpoint? I'm not quite sure what the URL should be, but here is an idea:

`/trends` - The API user still passes in a location/state and could use the same `incident_date` filter (though maybe for this endpoint it should just be `date`) pattern such as `incident_date>2005&incident_date<2015` to get the year range.

**Comment by LarryBafundo** [comment]
@cacraig, what do you think about @jeremiak's suggestion here?
