### ISSUE TITLE
Include rates in API responses when appropriate

### ISSUE THREAD

**Issue by jeremiak** [18F/crime-data-api#286]
I think that the API should return crime rates (probably with a common unit of per 100,000 people) or a population count along with actual crime counts. We want to show both the actual count and the rate in the explorer interface (#249) since both numbers are valuable to understanding the nature of the crime in a place.

For example, I made a request of `/incidents/count/?by=year` and I got this response:

```
  "results": [
    {
      "actual_count": 1310,
      "cleared_count": 541,
      "juvenile_cleared_count": 37,
      "reported_count": 1384,
      "unfounded_count": 74,
      "year": 2013
    },
   ...
```

It would be helpful to my use case if the API could return calculated rates or a population count for the place in the year so that the client could easily do rate calculation.

**Comment by harrisj** [comment]
So the idea is that it would calculate the rate depending on if you are grouping by a specific locality or not?

- default: national population
- by=state: state population for that year
- by=county: county population for that year

or such?

**Comment by jeremiak** [comment]
Exactly!

I think it would be sufficient to just include the population in each response for that place in that year to start, that way the user can calculate the rate to whatever unit they want?

**Comment by harrisj** [comment]
So, this is something we probably could include as part of the estimated data endpoint and maybe is something we could compute for agencies, but the issue here was for adding to the `reta_month_offense_subcat_summary` table which we will eventually be deprecating. So I'm going to close this issue now.
