### ISSUE TITLE
Clarify best way to identify if an agency has reported in a given year

### ISSUE THREAD

**Issue by harrisj** [18F/crime-data-api#291]
**[UPDATED 1/12/2017 with response from FBI]**

We want to be able to know if an agency has reported in a given year for SRS and/or NIBRS. This is so we can calculate what percentage of agencies are reporting for a year in the crime explorer presenter. Potentially if we have this data at the month level, we could also show areas of non-reporting on graphs for a specific agency or such (or show that a dip is really related to missing reports)

There seem to be several tables that look like they have information about reporting. 

The first of these is `ref_agency_data_content` which is mapped to a specific agency for a given data year. It has a few code columns that seem to indicate types of data:

- reporting_type: possible values of `S` (for summary?), `I` (for incident?) and `?` (for shruggie). There is at most one row per year for a given agency. 
- nibrs_ct_flag: `Y` if the agency reported cargo thefts
- nibrs_hc_flag: `Y` if the agency reported hate crimes
- nibrs_leoka_flag: `Y` if the agency reported LEOKA
- nibrs_arson_flag: `Y` if the agency filed an arson report?
- summary_rape_def: Can be `L` (legacy?), `R` (post-2013?)` or null
- nibrs_ht_flag: `Y` for whatever the ht reports are

It seems like this would give us an answer for if an agency has reported in general, but it seems like there are a few other questions to be explored (through DB queries):

1. If an agency is not in this table for a given year, does it mean they haven't reported for the entire year? **REF_AGENCY_DATA_CONTENT is used mostly for NIBRS to Summary conversion.  If there is a  NIBRS agency missing from it, we will need to add it.  It keeps track of what kinds of data is supposed to be converted.  For example an agency may send arson, but the state fire marshal sends it too and more completely so do not convert this agency’s arson data**
2. For agencies that report both types of data, do they indicate them with I an disregard the summary data? **If they submit both types, SRS and NIBRS, they do not indicate it, and generally speaking SRS wins out for reporting purposes and not the converted NIBRS.  The agencies are not supposed to be submitting both, and hopefully the duplicates you are seeing are converted from NIBRS to Summary, but some agencies do submit both at times.  New UCR stores both**
3. If an agency has `I` does that mean they have computed summary data for them in the RET A tables as well **I assume you are asking that if an agency submits incidents (I) in NIBRS, the corresponding records in summary came from NIBRS to Summary, Yes.  Legacy handled NIBRS to Summary differently.  New UCR converts but stores the submitted value AND the converted value.  We store the converted NIBRS numbers with a data_home of ‘X’.**

It looks like we can also get a bit more granular if we want to look at SRS (aka Ret A) reporting and NIBRS reporting. For RET A reports, there is a table called `reta_month` which is information about a specific agency for a given month/year. It has the following useful columns:

- `reported_flag` (can be `Y` or `N`)
- `source_flag` (right now this is only `R`, but we should ask if this will change and this table will include NIBRS data converted to SRS)

It looks like we could use this to get SRS participation stats for a given month or year. We do have to answer two questions though:

1. If an agency does not report, are they still in here with a flag of `N`? I'd honestly prefer that to having no records, because then I get paranoid about missing data. **Yes, A job is run annually to create the next year of months as unreported based on the previous year’s presence in the table.  This applies to both NIBRS and Summary.  You should ask Catherine about the Conspiracy Theories she is collecting…**
2. If an agency has no crimes for a given month, are they still listed as reporting here? **For Summary, if they have no crime, they can submit a zero report which fills in 0s for their submitted date.  NIBRS can send in a zero report, but this is tracked using the Z flag for reported status.  Same with summary hate crime and cargo theft.**

Similarly, for NIBRS, there is a table `nibrs_month` that is also linked to a specific agency in a given month and has the following useful column:

- `reported_status` can be `U` (unreported?), `I` (incidents?) or `Z` (no idea). 

So, that leaves a few other questions to be resolved for this table:

1. What do the `reported_status` values mean? **The Flags for Reported Status are
I = Incident; U = Unreported; Z = Zero Report (we have nothing to report and are reporting that as such.  Previously, it has been questioned how an agency can have no crime e.g. Mayberry, but a growing number of agencies are task forces or special crime units that may not have incidents every month)**
2. If an agency isn't reporting NIBRS, are they in this table? Or is this just for NIBRS reports? If an agency reports NIBRS but has no crimes, are they in here? **Only NIBRS reporting agencies SHOULD be in that table.  That being said, NIBRS submissions are sometimes fluid, meaning they will revert to summary.  In addition, once you are able to go NIBRS in the legacy system, it sets a flag on the agency allowing them to submit NIBRS based on a start date.**

I can figure out most of these through database queries, but it would be useful to get a list of small codes that don't have external lookup tables like that

**Comment by harrisj** [comment]
Some numbers! I looked at how many unique agencies are in each type of table for the year 2014

|Table|Agencies|Note|
|------|---------|-----|
|Ref_agency_data_content|23,467||
|RET A|22,332|Y=16593, N=7034|
|NIBRS|22,451|(U=16702,I=6420,Z=1090)|

So, I personally find it a little maddening that these tables seem to be redundant and yet have different totals, but it looks like I should use ref_agency_data_content for now

**Comment by harrisj** [comment]
On further reflection, this data suggests that ref_agency is populated only with agencies that have reported for something. So, I don't know if I can calculate the participation rate accurately.
There is a [census of law enforcement agencies that last updated in 2008](17,985), but it has a smaller count of agencies and it's unclear if agencies are counted the same in both systems

**Comment by jeremiak** [comment]
Cool analysis! Perhaps we could ask the FBI how they know it _isn't_ near 100% participation? Also, does this [ORI crosswalk](http://www.icpsr.umich.edu/icpsrweb/NACJD/studies/35158) help to establish the list of known law enforcement agencies in the country?

**Comment by harrisj** [comment]
That is a good point. The Codebook for that crosswalk (aka the LEAIC)  does say this:

> Most, but not all, law enforcement agencies report crime data to the FBI either directly or through state agencies. In addition to providing the crosswalk function described above, the LEAIC attempts to include all law enforcement agencies in the United States. The records in the LEAIC come from three main sources: the Census of State and Local Law Enforcement Agencies (most recently 2008); the FBI's Uniform Crime Reporting Program: Offenses Known and Clearances by Arrest, 2012; and an extract file supplied by the National Crime Information Center (NCIC). In addition a vendor-supplied list of police agencies was used for supplemental verification.

So that sounds like it could work, but there might be some issues with using it to count all agencies in a given state since each system has different ways of defining what an agency is:

> Records from the different source files represent different units of analysis. CSLLEA source records represent law enforcement agencies as defined by the CSLLEA. UCR source records may represent law enforcement agencies, similar to the CSLLEA, or law enforcement reporting entities contained within a larger related agency. For example the CSLLEA will contain one record for the MICHIGAN STATE POLICE. The UCR will contain a record for the MICHIGAN STATE POLICE overall and additional records for every state police post that has a separate ORI code. Consequently the UCR has more records than the CSLLEA. Records originating from the CSLLEA represent law enforcement entities, while records originating from the UCR represent both law enforcement agencies and law enforcement reporting entities.
>
> The NCIC source file includes other types of records. These records represent reporting entities, both active and retired, and entities having access to the NCIC system. For example, records for the WASHINGTON [DC] METROPOLITAN POLICE DEPARTMENT are contained in all three source files (CSLLEA, UCR and NCIC). The NCIC file has an additional record for the [WASHINGTON, DC] METROPOLITAN POLICE DEPT RECRUITING DIVISION (ORI code DCMPD0100). A review of reported crime since 1985 shows no crime reported with this ORI. Most likely the ORI is/was used simply to access to the NCIC. This represents a third type of record in the LEAIC - access to the NCIC.

So I think we'd have to look into this further before we load the external crosswalk. But maybe let's wait to see what the FBI has to say first

**Comment by harrisj** [comment]
So, we have answers thanks to our friends at the FBI. Basically, we should use `reta_month` as a general way to figure out if an agency has reported in a given month, since it will include both agencies that report SRS statistics only as well as NIBRS-reporting agencies whose data has been backconverted into SRS.

Furthermore, we can use ref_agency_county to derive a "covered" population of how many people are in a given state or county within the jurisdictions of agencies reporting for that year, since they generally do not double-count populations within the `ref_agency_county` table).

Since the questions have been resolved, I am closing this issue
