### ISSUE TITLE
Consolidate & refine design direction (Homepage) 

### ISSUE THREAD

**Issue by LarryBafundo** [18F/crime-data-api#300]
We need to incorporate the feedback we received from Tuesday's testing (notes here: https://docs.google.com/document/d/1LVenQsdnvDu3AP8PHQjCHZb7sYhiAgT7h7C-fMongk4/edit) advance the design for the homepage. 

@amberwreed this issue is a place-holder of sorts and may need a checklist of design tasks once we've settled on a direction for the homepage.

**Comment by jeremiak** [comment]
Issue moved to [18F/crime-data-explorer #144](https://github.com/18F/crime-data-explorer/issues/144) via [**ZenHub**](https://www.zenhub.com/)
