### ISSUE TITLE
Navigate to a state or crime type (homepage) 

### ISSUE THREAD

**Issue by LarryBafundo** [18F/crime-data-api#302]
As a user, I want to view crime data by selecting a state or crime type from the homepage

**Comment by LarryBafundo** [comment]
@brendansudol I assigned this to you because you took ownership of https://github.com/18F/crime-data-explorer/issues/144. this just pertains to being able to select a state and crime type from the UI. 

however, we should also remember that we need to provide access to locations other than the 50 US states which we have UCR data for - locations like Puerto Rico and the tribal territories. I think it's fine to leave those out for this sprint, but we should factor this into our implementation and design. I'm not sure how much coordination with the backend team this requires, but copying the relevant folks here for visibility: 

@jeremiak, @harrisj

**Comment by jeremiak** [comment]
I think this is done. We should open a new issue to add areas like PR and tribal nations when we want to account/plan for that work
