### ISSUE TITLE
Left hand navigation refinement

### ISSUE THREAD

**Issue by amberwreed** [18F/crime-data-api#306]
- [x] Refine visual / interaction design based on research findings
- [x] Create production ready annotated sketch files for FE
- [x] Walk-through sketch designs with FE team
- [ ] FE design implement trend chart per annotated sketch file
- [ ] Visual design review for design consistency

**Comment by LarryBafundo** [comment]
closing as we will create a new issue to track prioritized design refinements for sprint 5
