### ISSUE TITLE
Explorer page view refinements

### ISSUE THREAD

**Issue by amberwreed** [18F/crime-data-api#307]
- [x] Refine page design based on research findings
- [x] Work with @nicoleslaw to integrate content needs to the design
- [x] Create a production ready sketch file
- [x] Walk through designs with FE design team
- [ ] FE design implement trend chart per annotated sketch file
- [ ] Visual design review for design consistency

**Comment by amberwreed** [comment]
@jeremiak We have new designs for the type sizes in the overview based on research and testing. I'll ping you when the files are updated.

**Comment by jeremiak** [comment]
Sounds good, thanks @amberwreed

**Comment by amberwreed** [comment]
@jeremiak Here's the latest explorer view page. https://drive.google.com/open?id=0B5cw7Ca2CjsyMDJMMy1TNVhjWDQ

We should discuss the merits of using pink for no data available. I like that it draws attention to the fact but don't want to feel like the site is broken. We may need to adjust based on how often it shows up.

**Comment by amberwreed** [comment]
@jeremiak Pls download new file: https://drive.google.com/open?id=0B5cw7Ca2CjsycVY2S0otdF9PMzg

**Comment by LarryBafundo** [comment]
I'm going to close this issue - we will have new cards for refinements that have been prioritized for the next sprint.
