### ISSUE TITLE
Incident details refinement

### ISSUE THREAD

**Issue by amberwreed** [18F/crime-data-api#309]
- [x] Refine charts based on user testing
- [x] Create production ready sketch files
- [x] Walk FE team through designs
- [x] FE design implement trend chart per annotated sketch file
- [ ] Visual design review for design consistency

**Comment by jeremiak** [comment]
Not sure what this card refers to, or if it should have ever been in progress. @AvivaOskow is still (to my knowledge) working on the improvement designs for the incident details, so I'm moving this out of in-progress

**Comment by jeremiak** [comment]
Unless this card refers to the design work. I think we should document/agree upon a process for issues/labels/columns during the sprint retro for work that is shared amongst the design and dev folks

**Comment by LarryBafundo** [comment]
@jeremiak it's mainly design oriented tasks, but you're right, we should split out the implementation aspects, or talk about how we can more clearly differentiate between work streams.

**Comment by LarryBafundo** [comment]
i have a new task for the implementation of the new incident detail charts: https://github.com/18F/crime-data-api/issues/348

unless this issue speaks to something different we should close it.

**Comment by amberwreed** [comment]
I'm happy to split out design and implementation tasks. Let's keep this open because @AvivaOskow is still working on design refinements and annotating the NIBRS charts. There will be small changes based on the testing in Sprint 4.

**Comment by LarryBafundo** [comment]
@AvivaOskow can we enumerate what adjustments you're making here?

**Comment by amberwreed** [comment]
NIBRS/hate crime annotations are up:
https://drive.google.com/open?id=0B9bDBpzeNNaXYTZfbU1TUzF3dWs

plus an updated style guide

**Comment by amberwreed** [comment]
The NIBRS has the annotations for the different charts, as well as a layout of the page. One thing to note about the page is that the units of space between the cards are 20px—not a multiple of 8. That’s because it was originally based off my 60px col., 20px gutter, 16 col. layout, so…not sure what that should be. But I trust you @bren @jeremiak to make them evenly spaced and beautiful :slightly_smiling_face:

^^from @AvivaOskow

**Comment by amberwreed** [comment]
I think the Explorer page annotations call for 24px between cards—just to keep you on your toes!

**Comment by AvivaOskow** [comment]
NIBRS and hate crime files annotated here:

https://drive.google.com/open?id=0B9bDBpzeNNaXYTZfbU1TUzF3dWs
