### ISSUE TITLE
Make the "in beta" banner more pronounced 

### ISSUE THREAD

**Issue by LarryBafundo** [18F/crime-data-api#323]
The FBI security team has asked us to make the banner that says the site is in beta testing to be more pronounced so that nobody mistakes the site for a complete system. 

@amberwreed has started to explore different ways of making this change, but it would be ideal if we could fit this into the current sprint. 

![screen shot 2017-01-25 at 10 25 11 am](https://cloud.githubusercontent.com/assets/15899668/22312062/377fd89e-e30b-11e6-910c-655736f20d59.png)

**Comment by amberwreed** [comment]
Please implement a option 1. Option 2 which was implemented was implemented but doesn't call enough attention to the beta site status or the opportunity to provide feedback. Thanks.

**Comment by brendansudol** [comment]
we should try to add issues like this to the crime-data-explorer repo (vs. the api one)

**Comment by brendansudol** [comment]
done via https://github.com/18F/crime-data-explorer/pull/165

**Comment by amberwreed** [comment]
Thanks for the heads up. I didn't realize I was adding all issues I create to the API repo. Do you want me to go through the board move issues into different repos?
