### ISSUE TITLE
Implement header and footer design

### ISSUE THREAD

**Issue by amberwreed** [18F/crime-data-api#324]
- [x] FE design implement trend chart per annotated sketch file
- [x] Visual design review for design consistency
- [ ] Add FBI/CDE logos 
- [ ] View related links from footer

**Comment by jeremiak** [comment]
As far as I can tell, this is mostly done. There is remaining work to add the social icons into the footer

**Comment by jeremiak** [comment]
Issue moved to [18F/crime-data-explorer #207](https://github.com/18F/crime-data-explorer/issues/207) via [**ZenHub**](https://www.zenhub.com/)
