### ISSUE TITLE
Mobile designs of key screens

### ISSUE THREAD

**Issue by amberwreed** [18F/crime-data-api#325]
- [ ] Navigation
- [ ] Trend chart
- [ ] Explorer page
- [x] Homepage
- [ ] Table

**Comment by amberwreed** [comment]
@AvivaOskow the initial designs are complete but we need to divide an conquer for the annotating and updating the style guide with new mobile type sizes.

**Comment by AvivaOskow** [comment]
**Homepage mobile**

![homepage mobile](https://cloud.githubusercontent.com/assets/21244661/22669741/0a4e93fa-ec94-11e6-817a-0b68cfcae514.jpg)

**Homepage mobile menu dropdown**

![homepage mobile menu](https://cloud.githubusercontent.com/assets/21244661/22669751/133118bc-ec94-11e6-9d3e-5544ba3c15c6.jpg)

**Comment by jeremiak** [comment]
@AvivaOskow @amberwreed This is ready for your acceptance/disapproval

**Comment by amberwreed** [comment]
@jeremiak Thanks! Here are prioritized lists for items to fix before launch.

High priority:

- [ ] Trend chart isn't scaling to time period. For example, if I'm looking at a 10 year period, all years should be visible. It is currently impossible to see or scroll to all the years in mobile or ipad views.
- [ ] 
- [ ] Double check that the margin on the homepage and the explorer page match. I prefer the explorer page.
- [ ] From the homepage, the view results should be disabled until a location and crime are selected. Error msgs should display if a user hits the button without selecting.
- [ ] Button text for large and small buttons should not be the same size. Text in small buttons is too big. Pls see design.

Lower priority:

- [ ] Placement of the closed filter button is on the wrong side of the screen. See designs.

**Comment by LarryBafundo** [comment]
@jeremiak, @amberwreed i'm going to close this out and create new issues so we can more easily prioritize between issues for the next sprint.

**Comment by amberwreed** [comment]
@jeremiak I'm not sure what's been done on this. My top priorities, that I can break out into issues are: 

- [ ] Trend chart isn't scaling to time period. For example, if I'm looking at a 10 year period, all years should be visible. It is currently impossible to see or scroll to all the years in mobile or ipad views.

- [ ] Beta bar missing on mobile version. Can provide file or suggest stacking above government site.

**Comment by jeremiak** [comment]
Thanks @amberwreed. Issue #326 captures the broken trend chart on mobile and I opened #378 for the beta banner. I also opened [an issue](https://github.com/18F/crime-data-explorer/issues/339) for the list of other improvements here so I'm going to close this issue now.
