### ISSUE TITLE
Verify how routes are being parsed in Chrome and possibly Firefox 

### ISSUE THREAD

**Issue by LarryBafundo** [18F/crime-data-api#333]
Verify how routes like `crime-data-explorer.fr.cloud.gov/#/explorer/arizona%11/` are being parsed in Chrome, possibly firefox as well.

Noah: any string after the state is getting appended in the title on the page. We don’t want that to happen, it makes it look like real data.

**Comment by cacraig** [comment]
This came out of the security assessment - Can you guys take care of this? @jeremiak @brendansudol

**Comment by brendansudol** [comment]
yes -- is there a date it's needed by?

for the record, here's what he means: https://crime-data-explorer.fr.cloud.gov/#/explorer/arizona/big+smiles

**Comment by cacraig** [comment]
ASAP. - It's high priority because it's required to get the initial ATO - Thanks @brendansudol !

**Comment by brendansudol** [comment]
roger that

**Comment by brendansudol** [comment]
this is now resolved

**Comment by LarryBafundo** [comment]
@brendansudol okay to close, right?
