### ISSUE TITLE
Valid API key doesn't work from Swagger UI  

### ISSUE THREAD

**Issue by LarryBafundo** [18F/crime-data-api#335]

**Comment by cacraig** [comment]
Where should we put this information @LarryBafundo  ?

**Comment by harrisj** [comment]
I just tried this with one endpoint in the Swagger UI and the API key and it worked. Do they have a specific example?

**Comment by cacraig** [comment]
^ It just doesn't work for urlencoded api_keys. I don't think it's a bug, but more of a usability issue?

**Comment by afeld** [comment]
A workaround is to not put any characters in API keys that would require encoding. Not sure how SecOps would feel about narrowing the character set...

**Comment by LarryBafundo** [comment]
have we identified a path forward for this yet? @cacraig @harrisj

**Comment by harrisj** [comment]
We could do a uudecode on the API key checking step. I'll take this
