### ISSUE TITLE
Pagination parameters can exceed total page values.

### ISSUE THREAD

**Issue by cacraig** [18F/crime-data-api#336]
This is a usability issue (No security issue - as the input is filtered/escaped properly). The pagination parameter is currently read, and given back to the client as-is. We should be range checking this value with the counts or count estimates for queries.

**Comment by harrisj** [comment]
I guess theoretically this would mean that you might miss some results for large queries (ie, more than 1000 results) if we underestimated the total count, but this is probably not an issue in practice

**Comment by LarryBafundo** [comment]
@cacraig moving this to in progress. can you provide an update?
