### ISSUE TITLE
Disable /arson, incident, and /arrests endpoints.

### ISSUE THREAD

**Issue by cacraig** [18F/crime-data-api#337]
We need to rethink the implementation of these two endpoints. They do not scale with the size of the queries they are running, and they are actually bringing down our production environment when called. - Since they are not critical for the MVP, they should be disabled.

**Comment by LarryBafundo** [comment]
@cacraig during our grooming session tomorrow let's also talk about the /incident endpoint and whether or not we should prioritize work on it for the next sprint.

**Comment by cacraig** [comment]
@LarryBafundo I will get to this today.

**Comment by harrisj** [comment]
I can also do this if you are swamped

**Comment by LarryBafundo** [comment]
@cacraig okay to close this?

**Comment by harrisj** [comment]
This was merged, so I am going to close it.
