### ISSUE TITLE
Assert 501/404's for certain non-implemented endpoints

### ISSUE THREAD

**Issue by cacraig** [18F/crime-data-api#338]
Add 501/404 for non-implemented API endpoints. See: https://crime-data-api.fr.cloud.gov/codes/ref_s

Should give HTTP 501: Not implemented, or 404: Not found.

**Comment by harrisj** [comment]
Well, that is an implemented endpoint (the `ref_s` is being passed to the CodesDetail endpoint, but we can tweak that definitely

**Comment by harrisj** [comment]
Is this still a priority?

**Comment by LarryBafundo** [comment]
@harrisj are you asking in terms of the MVP, or the ATO?

**Comment by harrisj** [comment]
Either, really?

**Comment by LarryBafundo** [comment]
i think we should have 404s for endpoints that aren't implemented. otherwise, how do we message that these requests aren't available to the user?

**Comment by harrisj** [comment]
This is actually a case where the `ref_s` is an argument to the `/codes` endpoint, but fair enough. I will just fix this now
