### ISSUE TITLE
Denormalize incident and arrest data 

### ISSUE THREAD

**Issue by LarryBafundo** [18F/crime-data-api#347]
@cacraig we should denormalize the incident and arrest data so we can support the download of archived NIBRS datasets, per our earlier conversation.

**Comment by cacraig** [comment]
This is happening as we speak!

**Comment by LarryBafundo** [comment]
yes, thanks. when you have a chance, can you please elaborate on the technical approach we discussed earlier that this will support?

**Comment by cacraig** [comment]
https://github.com/18F/crime-data-api/pull/355  

Basically, we need to denormalize the nibrs_incident, nibrs_property, and nibrs_arrestee tables.

After this, we will run a big script to generate an archive containing 8 CSV files (Agencies, Counties, Incidents, Property-Incidents, Offenses, Offenders, Victims, and Arrestee). Each row will contain either an ORI or ORI + Incident ID to allow for linking of data. ->  For each year, and state.

We will then push all of this to s3, and allow public access + downloading.

**Comment by cacraig** [comment]
This is basically done, just fixing an issue with the denormalized victims tables age_num field atm.

**Comment by LarryBafundo** [comment]
@cacraig does this issue pertain to the denormalizing of incident and arrest data AS WELL AS the generation of the archived files?

**Comment by cacraig** [comment]
No, we can close this one. - We'll create another issue for the s3 + download generation.
