### ISSUE TITLE
Implement new incident detail chart designs 

### ISSUE THREAD

**Issue by LarryBafundo** [18F/crime-data-api#348]
This task relates to the implementation of the new incident detail chart designs: 

- [ ] donut chart for demographics 
- [ ] histogram for age distribution 
- [ ] vertical bar chart for other details 
- [ ] robo text for interactive charts 

cc: @amberwreed, @AvivaOskow

**Comment by LarryBafundo** [comment]
this issue also involves: https://github.com/18F/crime-data-explorer/issues/134

**Comment by jeremiak** [comment]
Issue moved to [18F/crime-data-explorer #204](https://github.com/18F/crime-data-explorer/issues/204) via [**ZenHub**](https://www.zenhub.com/)
