### ISSUE TITLE
View national trends by crime type 

### ISSUE THREAD

**Issue by LarryBafundo** [18F/crime-data-api#351]
As a user, I want to be able to view national trends by crime type and location from the homepage and the explorer view.

**Comment by LarryBafundo** [comment]
cc: @amberwreed

**Comment by jeremiak** [comment]
Issue moved to [18F/crime-data-explorer #205](https://github.com/18F/crime-data-explorer/issues/205) via [**ZenHub**](https://www.zenhub.com/)
