### ISSUE TITLE
Update: Add link to data dictionary to the downloads view 

### ISSUE THREAD

**Issue by LarryBafundo** [18F/crime-data-api#353]
As a user, I want to view a data dictionary, or list of terms, that is included along with the SRS or NIBRS data that I've downloaded. 

This issue covers the following tasks: 

- [x] developing the data dictionary content: https://docs.google.com/spreadsheets/d/19EFBe2bpv2RfJ4IuaDvtUbenN8yFnSyh7cXV-1IUces/edit#gid=0
- [x] reviewing/finalizing it with CJIS
- [x] linking to it from the CDE

**Comment by amberwreed** [comment]
https://github.com/18F/crime-data-explorer/issues/203

**Comment by amberwreed** [comment]
#203

**Comment by LarryBafundo** [comment]
@RyanSibley assigning this to you to continue refining the data descriptions per our convo with Evan today.

**Comment by jeremiak** [comment]
Is it accurate that the data dictionary is complete and we now need to just figure out where to link to it from on the explorer application?

If so, is there an initial idea on where we should put it?

**Comment by LarryBafundo** [comment]
@harrisj originally, the intent was to include it in the bulk NIBRS downloads. but we are going to hold off on doing that for now. 

in the meanwhile, i propose adding a link to the data dictionary here, along with the links we currently have in place for the readme and NIBRS diagram.

<img width="971" alt="screen shot 2017-03-30 at 3 39 09 pm" src="https://cloud.githubusercontent.com/assets/15899668/24529191/25c12550-155f-11e7-9fea-c1f3a17c4cd9.png">

@RyanSibley any concerns with this? If not, we can simply add a link to the dictionary and close this.
