### ISSUE TITLE
Homepage refinements 

### ISSUE THREAD

**Issue by LarryBafundo** [18F/crime-data-api#354]
A collection of tasks related to refinement of the homepage: 

- [ ]  add an error prompt for when a location or crime type isn't selected prior to viewing results
- [ ]  add rollover states for selected states on the map
- [ ]  view the name of states upon rollover (to make it easier to identify smaller states)

**Comment by LarryBafundo** [comment]
@amberwreed this is designated for sprint 6, but please revise the to do list as you see fit.

**Comment by jeremiak** [comment]
Issue moved to [18F/crime-data-explorer #208](https://github.com/18F/crime-data-explorer/issues/208) via [**ZenHub**](https://www.zenhub.com/)
