### ISSUE TITLE
Selected explorer view refinements (sprint 5) 

### ISSUE THREAD

**Issue by LarryBafundo** [18F/crime-data-api#356]
A collection of prioritized tasks related to refinement of the homepage:  

- [ ]  freeze placement of the lefthand navigational bar while scrolling vertically up or down the page.

**Comment by jeremiak** [comment]
Issue moved to [18F/crime-data-explorer #206](https://github.com/18F/crime-data-explorer/issues/206) via [**ZenHub**](https://www.zenhub.com/)
