### ISSUE TITLE
Do we want to slice participation rates by population type?

### ISSUE THREAD

**Issue by harrisj** [18F/crime-data-api#361]
I think one of the questions we have generally is how different classes of agencies report. There is a table `ref_population_group` that ties into the `ref_agency` via the `ref_agency_population` table. Here's a rough breakdown of where all the agencies were in 2014:

| population_group_code   | population_group_desc                                                           |   count |
|-------------------------|---------------------------------------------------------------------------------|---------|
| 7                       | Cities under 2,500                                                              |   7,718 |
| 8C                      | Non-MSA counties from 10,000 thru 24,999                                        |     669 |
| 8B                      | Non-MSA counties from 25,000 thru 99,999                                        |     294 |
| 1B                      | Cities from 500,000 thru 999,999                                                |      24 |
| 6                       | Cities from 2,500 thru 9,999                                                    |   4,370 |
| 9D                      | MSA counties under 10,000                                                       |   2,161 |
| 4                       | Cities from 25,000 thru 49,999                                                  |     918 |
| 1A                      | Cities 1,000,000 or over                                                        |      11 |
| 5                       | Cities from 10,000 thru 24,999                                                  |   1,981 |
| 8D                      | Non-MSA counties under 10,000                                                   |   2,433 |
| 0                       | Possessions (Puerto Rico, Guam, Canal Zone, Virgin Islands, and American Samoa) |       5 |
| 9B                      | MSA counties from 25,000 thru 99,999                                            |     495 |
| 8A                      | Non-MSA counties 100,000 or over                                                |       4 |
| 9A                      | MSA counties 100,000 or over                                                    |     174 |
| 9C                      | MSA counties from 10,000 thru 24,999                                            |     289 |
| 8E                      | Non-MSA State Police                                                            |     108 |
| 1C                      | Cities from 250,000 thru 499,999                                                |      50 |
| 3                       | Cities from 50,000 thru 99,000                                                  |     502 |
| 2                       | Cities from 100,000 thru 249,000                                                |     221 |
| 9E                      | MSA State Police                                                                |     123 |

I don't know if this is useful, specifically if you were curious about national participation rates, so I'm just making a note of it here in case you want to know this for national statistics or as a sub-grouping for each state.

**Comment by LarryBafundo** [comment]
@harrisj thanks for this. we might want to come back to this in future iterations. we could do interesting things with cities/crime by population size.

**Comment by LarryBafundo** [comment]
this is not something that we're going to tackle prior to launch, but it deserves consideration for the roadmap
