### ISSUE TITLE
Explorer - Loading state

### ISSUE THREAD

**Issue by AvivaOskow** [18F/crime-data-api#362]
Design for view of explorer when data is loading

- [ ] Design loading state

- [ ] Dev implementation

**Comment by LarryBafundo** [comment]
hey @AvivaOskow i was talking with @amberwreed and we had some questions about what exactly was being planned for these loading states. do we need to design something from scratch in light of our other priorities, or can we reuse something that already exists and is readily available?

**Comment by AvivaOskow** [comment]
@LarryBafundo This came out of a conversation with @jeremiak about whether we should have each element have it's own individual loading state, or if we should have one for the whole page until everything is ready to be viewed. I don't believe @amberwreed or I have had time to get to it yet, but I would like to try it out, unless Amber has a design she has done that could work for it in the meantime?

**Comment by LarryBafundo** [comment]
I agree with having a loading state for each component, just asking if there is reusable code out there that we can use instead of designing from scratch. however, i defer to you both.

**Comment by jeremiak** [comment]
Yup, we're building a loading component that we can reuse in any panel or even as a big page wide element if we wanted. Right now it is some really ugly red text that says "Loading" but once we get a design we can change that

**Comment by amberwreed** [comment]
@jeremiak can you provide a little more detail about what you are imagining or an example of something you've seen in use.

**Comment by jeremiak** [comment]
Sure. I imagine that we want the loading state to work a little bit like Facebook's news feed, which is to say that the broad elements of the page show up but individual elements are shown as "loading" until the data arrives. The alternative here is something more akin to having almost nothing show up on the page (beyond the Loading component) until all the data has arrived. This might look more like https://code.gov.

The way the prototype works right now is a lot more like the first option than the second. There are two loading components, each shown in place of either the trend chart or the NIBRS dimension. They do not coordinate with each other, so as soon as the trend data arrives, that loading component is replaced with the trend chart and as soon as the NIBRS data arrives, that loading component is replaced with the proper elements

Currently, the presentation of that individual loading component is pretty ugly:
![feb-08-2017 16-10-27](https://cloud.githubusercontent.com/assets/780941/22757516/29ba19b8-ee19-11e6-9150-97dca177f219.gif)

**Comment by amberwreed** [comment]
I agree that the current solution could be easy to improve. I'd like to try a spinner (like either pictured below) in a shade of blue grey. I think the spinner should sit on the background color and not have the white box appear until there is content.

<img width="527" alt="screen shot 2017-02-08 at 8 59 19 pm" src="https://cloud.githubusercontent.com/assets/13576520/22770029/d863c824-ee41-11e6-95b1-2be9e6de41b4.png">

Here are some options for us to chat about tomorrow.
<img width="598" alt="screen shot 2017-02-08 at 9 14 27 pm" src="https://cloud.githubusercontent.com/assets/13576520/22770225/b104c880-ee43-11e6-9d61-4cb80e59770e.png">
<img width="621" alt="screen shot 2017-02-08 at 9 11 34 pm" src="https://cloud.githubusercontent.com/assets/13576520/22770226/b1059d50-ee43-11e6-98e6-1d479f33d3dd.png">
<img width="625" alt="screen shot 2017-02-08 at 9 10 46 pm" src="https://cloud.githubusercontent.com/assets/13576520/22770227/b1064282-ee43-11e6-883d-d995d36962ce.png">
<img width="621" alt="screen shot 2017-02-08 at 9 10 30 pm" src="https://cloud.githubusercontent.com/assets/13576520/22770228/b1078840-ee43-11e6-88fe-f8c65db3a890.png">

**Comment by amberwreed** [comment]
Thoughts @AvivaOskow ?

**Comment by AvivaOskow** [comment]
I like #1 and #4. I think #4 the best because it's loading where the actual content will be.

**Comment by jeremiak** [comment]
We're going to go with the fourth loading indicator option because it is cheap to implement and we'll revisit this with a potentially more visually designed option in the next sprint or after shipping the MVP

**Comment by jeremiak** [comment]
Closed in favor of [crime-data-explorer#273](/18F/crime-data-explorer/issues/273)
