### ISSUE TITLE
Add Arson statistics to reta_month_offense_subcat_summary table

### ISSUE THREAD

**Issue by harrisj** [18F/crime-data-api#364]
To support the functionality requested in https://github.com/18F/crime-data-explorer/issues/235, we need to add Arson statistics to the `reta_month_offense_subcat_summary` table. These are not normally stored within the `reta_month` table family, but in separate arson reports. There is a similar structure though with `arson_month` and multiple `arson_month_subcat` records, so it should be relatively straightforward to write these counts into the table.

1. Group the counts directly into the `reta_month_offense_subcat_summary` tables using similar groupings. Remember to tag all these counts with `Property` as a classification.
2. Increment the counts for `Property` classification to include the Arson counts.

We'll want to test this out, and it will require a little bit of doublechecking before we run on production, but it's doable. 

Question: do we want to support counts by the `arson_subcategory` field? Unlike the regular ret A subcategories, these are not suboffenses like "Homicide by Knife" but rather the types of structures affected like "Single Occupancy Residential." I think we can pass on that level of granularity, but I wanted to note it.

cc @LarryBafundo @cacraig

**Comment by LarryBafundo** [comment]
@harrisj i think we can pass on supporting counts by subcategory for the MVP. But let's note it for the future.

**Comment by LarryBafundo** [comment]
@harrisj if this isn't client-facing and isn't waiting for a code review we can close it out.

**Comment by harrisj** [comment]
I still need to merge the PR, but yes, we can when that is done
