### ISSUE TITLE
Create new endpoint for downloading agency participation  

### ISSUE THREAD

**Issue by LarryBafundo** [18F/crime-data-api#367]
This task supports being able to download a list of participating agencies for a given query in the Explorer View & from the "other datasets" section of the downloads and documentation view. This data would include annual participation rates by agency and be joined against the ref_agency and state tables. 

Related to this, we also need to figure out what the likely size of these CSVs will be - does it fit into a single report, or will we need to break it up by state?

**Comment by harrisj** [comment]
So, I need a little more clarification of what I am supposed to be building here. There are several ways we could represent this data (in these examples `agency_information` would be 1 or more columns of detail about that specific agency):

One row per participation year:

|agency information|year|participated|
|-|-|-|
|agency info|1960|1|
|agency info|1961|1|
|agency info|1962|1|

A collapsed view:

|agency information|years participating|
|-|-|
|agency 1 info|1960,1961,1962,1963|
|agency 2 info|1973,1974|

A table view that would be hard for machines to grok:

|fields|1960|1961|1962|1963|...|2014|
|-|-|-|-|-|-|-|
|agency 1|1|1|0|0|...|1|
|agency 2|0|0|0|0|..|1|

**Comment by LarryBafundo** [comment]
@harrisj which is easier to work with? my first inclination is to go with the first option since it seems easiest for conducting analysis, but will also probably result in the largest CSV sizes.

**Comment by harrisj** [comment]
Okay, I will proceed with the first option for now and yes, let's move it into In Progress
