### ISSUE TITLE
The beta banner is not visible on mobile devices

### ISSUE THREAD

**Issue by jeremiak** [18F/crime-data-api#378]
The beta banner is not displayed on screens that are 640px wide or smaller.

![mobile-beta-banner](https://cloud.githubusercontent.com/assets/780941/23004064/899e6a6a-f3c2-11e6-8462-09b77e3fbc5d.gif)

**Comment by LarryBafundo** [comment]
FYI - per the FBI, we need to redesign the banner to make it more prominent. so we may want to hold off on this fix until the new one is designed and added. 

cc: @amberwreed, @jeremiak

**Comment by LarryBafundo** [comment]
relates to: https://github.com/18F/crime-data-api/issues/377

**Comment by amberwreed** [comment]
@AvivaOskow please attached annotated sketch file for mobile beta banner here.

**Comment by LarryBafundo** [comment]
related to: https://github.com/18F/crime-data-api/issues/377
