### ISSUE TITLE
Fix bad state codes in the `reta_month_offense_subcat_summary` table 

### ISSUE THREAD

**Issue by harrisj** [18F/crime-data-api#379]
So, the original table construction uses `ref_state.state_abbr` and not `ref_state.state_postal_abbr` like we might expect. The two are mostly identical, except for Nebraska and Guam. To fix, we need to run the two queries in production:

``` sql
UPDATE reta_month_offense_subcat_summary SET state='NE' where state='NB';
UPDATE reta_month_offense_subcat_summary SET state='GU' where state='GM';
```

**Comment by cacraig** [comment]
Done 👍
