### ISSUE TITLE
Weird dip for aggravated assault in South Carolina

### ISSUE THREAD

**Issue by harrisj** [18F/crime-data-api#380]
This quite likely is just something in the data, but I figure I'll record it just in case and get back to it

![crime_data_explorer](https://cloud.githubusercontent.com/assets/2044/23032424/50cec06a-f442-11e6-8f73-e67a15acbfd0.jpg)

**Comment by jeremiak** [comment]
A weird, and large, dip for Delaware violent crime as well 

![](https://d3vv6lp55qjaqc.cloudfront.net/items/1I0f0r0f2Z0J1P172C2q/Screen%20Shot%202017-02-16%20at%204.50.43%20PM.png?X-CloudApp-Visitor-Id=586613&v=66c510ad)

**Comment by harrisj** [comment]
For Alabama, I don't see a dip in the total crimes in 1991

|   year | offense   |   reported |   unfounded |    actual |   cleared |
|--------|-----------|------------|-------------|-----------|-----------|
| 1960   | Assault   |      6,683 |           0 |     6,683 |         0 |
| 1961   | Assault   |      6,459 |           0 |     6,459 |         0 |
| 1962   | Assault   |      6,671 |           0 |     6,671 |         0 |
| 1963   | Assault   |      6,786 |           0 |     6,786 |         0 |
| 1964   | Assault   |      8,464 |           0 |     8,464 |     6,685 |
| 1965   | Assault   |      8,679 |           0 |     8,679 |     6,873 |
| 1966   | Assault   |      9,395 |           0 |     9,395 |     7,082 |
| 1967   | Assault   |     10,418 |           0 |    10,418 |     7,479 |
| 1968   | Assault   |     11,783 |           0 |    11,783 |     9,032 |
| 1969   | Assault   |     11,501 |           0 |    11,501 |     8,780 |
| 1970   | Assault   |     11,080 |           0 |    11,080 |     8,277 |
| 1971   | Assault   |     11,905 |           0 |    11,905 |     8,873 |
| 1973   | Assault   |     16,700 |           0 |    16,700 |    13,388 |
| 1974   | Assault   |     35,052 |           0 |    35,052 |    28,158 |
| 1975   | Assault   |     34,340 |           0 |    34,340 |    28,700 |
| 1976   | Assault   |     32,340 |           0 |    32,340 |    27,203 |
| 1977   | Assault   |     33,772 |           0 |    33,772 |    27,997 |
| 1978   | Assault   |     33,478 |           0 |    33,478 |    27,463 |
| 1979   | Assault   |     35,572 |           0 |    35,572 |    29,233 |
| 1980   | Assault   |     37,979 |           0 |    37,979 |    31,472 |
| 1981   | Assault   |     36,283 |           0 |    36,283 |    29,214 |
| 1982   | Assault   |     39,256 |           0 |    39,256 |    31,689 |
| 1983   | Assault   |     37,127 |         481 |    36,646 |    30,062 |
| 1984   | Assault   |     39,190 |         533 |    38,657 |    30,809 |
| 1985   | Assault   |     43,992 |         524 |    43,468 |    33,453 |
| 1986   | Assault   |     48,821 |         590 |    48,231 |    35,085 |
| 1987   | Assault   |     49,911 |         753 |    49,158 |    35,939 |
| 1988   | Assault   |     52,806 |         740 |    52,066 |    37,671 |
| 1989   | Assault   |     54,976 |         658 |    54,318 |    37,604 |
| 1990   | Assault   |     62,551 |         800 |    61,751 |    41,276 |
| 1991   | Assault   |     65,136 |         767 |    64,369 |    42,445 |
| 1992   | Assault   |     72,155 |         852 |    71,303 |    45,694 |
| 1993   | Assault   |     79,265 |       1,284 |    77,981 |    47,692 |
| 1994   | Assault   |     86,428 |       1,908 |    84,520 |    51,191 |
| 1995   | Assault   |     93,665 |       2,466 |    91,199 |    55,002 |
| 1996   | Assault   |     94,146 |       2,620 |    91,526 |    54,858 |
| 1997   | Assault   |    101,594 |       3,046 |    98,548 |    62,155 |
| 1998   | Assault   |    102,304 |       2,961 |    99,343 |    60,575 |
| 1999   | Assault   |     99,585 |       2,582 |    97,003 |    57,203 |
| 2000   | Assault   |     99,509 |       3,059 |    96,450 |    57,954 |
| 2001   | Assault   |    101,872 |       3,435 |    98,437 |    60,410 |
| 2002   | Assault   |    100,014 |       3,867 |    96,147 |    59,657 |
| 2003   | Assault   |     99,010 |       3,983 |    95,027 |    62,462 |
| 2004   | Assault   |    103,149 |       4,147 |    99,002 |    59,800 |
| 2005   | Assault   |    111,607 |       4,183 |   107,424 |    71,215 |
| 2006   | Assault   |    116,833 |       3,919 |   112,914 |    75,540 |
| 2007   | Assault   |    117,077 |       4,349 |   112,728 |    74,223 |
| 2008   | Assault   |    120,034 |       4,262 |   115,772 |    77,008 |
| 2009   | Assault   |    119,108 |       5,170 |   113,938 |    77,352 |
| 2010   | Assault   |    117,625 |       5,057 |   112,568 |    77,982 |
| 2011   | Assault   |    120,675 |       5,324 |   115,351 |    80,758 |
| 2012   | Assault   |    125,077 |       5,760 |   119,317 |    81,810 |
| 2013   | Assault   |    114,598 |       4,831 |   109,767 |    76,900 |
| 2014   | Assault   |    114,175 |       4,900 |   109,275 |    74,240 |

The issue does not seem to be a dip in the population total either

| data_year   |   reporting_rate |   total_population |
|-------------|------------------|--------------------|
| 1960        |         0.889423 |          4,541,781 |
| 1961        |         0.807692 |          4,541,781 |
| 1962        |         0.779904 |          4,715,715 |
| 1963        |         0.819048 |          4,748,593 |
| 1964        |         0.726415 |          4,840,183 |
| 1965        |         0.698113 |          4,791,348 |
| 1966        |         0.674528 |          4,902,756 |
| 1967        |         0.693396 |          5,033,679 |
| 1968        |         0.683962 |          5,143,384 |
| 1969        |         0.646226 |          5,217,063 |
| 1970        |         0.660377 |          5,092,905 |
| 1971        |         0.665138 |          5,156,978 |
| 1973        |         0.948187 |          5,273,000 |
| 1974        |         0.621441 |          5,363,000 |
| 1975        |         0.620232 |          5,451,000 |
| 1976        |         0.630719 |          5,469,000 |
| 1977        |         0.6352   |          5,529,116 |
| 1978        |         0.632558 |          5,581,116 |
| 1979        |         0.62844  |          5,610,154 |
| 1980        |         0.630699 |          5,848,092 |
| 1981        |         0.628959 |          5,956,122 |
| 1982        |         0.621502 |          6,024,181 |
| 1983        |         0.597059 |          6,087,858 |
| 1984        |         0.597668 |          6,170,971 |
| 1985        |         0.588663 |          6,271,897 |
| 1986        |         0.588406 |          6,347,911 |
| 1987        |         0.573699 |          6,438,075 |
| 1988        |         0.580966 |          6,551,413 |
| 1989        |         0.57969  |          6,603,111 |
| 1990        |         0.614856 |          6,656,486 |
| 1991        |         0.604027 |          6,761,034 |
| 1992        |         0.600267 |          6,867,397 |
| 1993        |         0.614474 |          6,969,481 |
| 1994        |         0.615085 |          7,095,681 |
| 1995        |         0.629534 |          7,218,489 |
| 1996        |         0.618065 |          7,347,575 |
| 1997        |         0.627297 |          7,449,904 |
| 1998        |         0.639257 |          7,565,697 |
| 1999        |         0.618543 |          7,671,532 |
| 2000        |         0.543257 |          8,084,417 |
| 2001        |         0.567807 |          8,221,148 |
| 2002        |         0.56147  |          8,347,250 |
| 2003        |         0.56962  |          8,433,301 |
| 2004        |         0.562579 |          8,568,209 |
| 2005        |         0.563843 |          8,710,624 |
| 2006        |         0.557233 |          8,889,498 |
| 2007        |         0.541353 |          9,095,201 |
| 2008        |         0.536341 |          9,257,073 |
| 2009        |         0.534332 |          9,421,855 |
| 2010        |         0.528536 |          9,580,821 |
| 2011        |         0.533499 |          9,699,207 |
| 2012        |         0.540173 |          9,794,736 |
| 2013        |         0.515451 |          9,793,114 |
| 2014        |         0.512346 |          9,791,602 |

**Comment by harrisj** [comment]
Oh wait, I was looking at the wrong state! **SOUTH** Carolina!

**Comment by harrisj** [comment]
South Carolina assault totals
| year   | offense   |   reported |   unfounded |   actual |   cleared |
|--------|-----------|------------|-------------|----------|-----------|
| 1986   | Assault   |     48,172 |         285 |   47,887 |    35,540 |
| 1987   | Assault   |     43,332 |         270 |   43,062 |    30,604 |
| 1988   | Assault   |     53,669 |         324 |   53,345 |    36,123 |
| 1989   | Assault   |     59,243 |         344 |   58,899 |    38,072 |
| 1990   | Assault   |     62,719 |         352 |   62,367 |    39,656 |
| 1991   | Assault   |     25,996 |           0 |   25,996 |         0 |
| 1992   | Assault   |     75,929 |           0 |   75,929 |    31,204 |
| 1993   | Assault   |     83,355 |           0 |   83,355 |    43,535 |
| 1994   | Assault   |     93,097 |           0 |   93,097 |    50,269 |
| 1995   | Assault   |     97,182 |           0 |   97,182 |    45,028 |
| 1996   | Assault   |    104,280 |           0 |  104,280 |    57,323 |
| 1997   | Assault   |    110,497 |           0 |  110,497 |    59,904 |

South Carolina population
| data_year   |   reporting_rate |   total_population |
|-------------|------------------|--------------------|
| 1986        |         0.650794 |          3,443,321 |
| 1987        |         0.648903 |          3,492,186 |
| 1988        |         0.634375 |          3,561,276 |
| 1989        |         0.64486  |          3,580,250 |
| 1990        |         0.64526  |          3,555,097 |
| 1991        |         0.619048 |          3,617,018 |
| 1992        |         0.689474 |          3,656,971 |
| 1993        |         0.665789 |          3,698,868 |
| 1994        |         0.666667 |          3,724,575 |
| 1995        |         0.646597 |          3,730,957 |
| 1996        |         0.671835 |          3,755,337 |
| 1997        |         0.676845 |          3,815,949 |

There is indeed a dip. Next step will be looking at the records in the DB

**Comment by harrisj** [comment]
The problem seems to be bad data in the database. 

``` sql
SELECT rm.data_year::text, rm.month_num, count(*) AS reports, SUM(rmos.reported_count)
FROM reta_month_offense_subcat rmos
JOIN reta_month rm ON rm.reta_month_id = rmos.reta_month_id
JOIN ref_agency ra ON ra.agency_id = rm.agency_id
JOIN ref_state rs ON rs.state_id = ra.state_id
JOIN reta_offense_subcat ros ON ros.offense_subcat_id = rmos.offense_subcat_id
JOIN reta_offense ro ON ro.offense_id = ros.offense_id
WHERE rs.state_postal_abbr = 'SC'
AND ro.offense_name = 'Assault'
AND rm.data_year >= 1990
AND rm.data_year <= 1992
GROUP BY rm.data_year, rm.month_num
ORDER by rm.data_year, rm.month_num;
```

returns the following table of monthly totals

| data_year   |   month_num |   # reports |    reported | actual |
|-------------|-------------|-----------|--------|-----|
| 1990        |           1 |     1,962 |      5,320 |    5,285 |
| 1990        |           2 |     1,962 |      4,619 |    4,590 |
| 1990        |           3 |     1,962 |      5,410 |    5,380 |
| 1990        |           4 |     1,962 |      5,731 |    5,699 |
| 1990        |           5 |     1,962 |      6,223 |    6,185 |
| 1990        |           6 |     1,962 |      6,351 |    6,312 |
| 1990        |           7 |     1,962 |      6,558 |    6,506 |
| 1990        |           8 |     1,962 |      6,101 |    6,072 |
| 1990        |           9 |     1,962 |      5,832 |    5,805 |
| 1990        |          10 |     1,962 |      4,250 |    4,227 |
| 1990        |          11 |     1,962 |      3,257 |    3,243 |
| 1990        |          12 |     1,962 |      3,067 |    3,063 |
| 1991        |           1 |     2,268 |          0 |        0 |
| 1991        |           2 |     2,268 |          0 |        0 |
| 1991        |           3 |     2,268 |          0 |        0 |
| 1991        |           4 |     2,268 |          0 |        0 |
| 1991        |           5 |     2,268 |          0 |        0 |
| 1991        |           6 |     2,268 |          0 |        0 |
| 1991        |           7 |     2,268 |          0 |        0 |
| 1991        |           8 |     2,268 |          0 |        0 |
| 1991        |           9 |     2,268 |          0 |        0 |
| 1991        |          10 |     2,268 |          0 |        0 |
| 1991        |          11 |     2,268 |          0 |        0 |
| 1991        |          12 |     2,268 |     25,996 |   25,996 |
| 1992        |           1 |     2,280 |      5,638 |    5,638 |
| 1992        |           2 |     2,280 |      5,465 |    5,465 |
| 1992        |           3 |     2,280 |      6,144 |    6,144 |
| 1992        |           4 |     2,280 |      6,465 |    6,465 |
| 1992        |           5 |     2,280 |      6,859 |    6,859 |
| 1992        |           6 |     2,280 |      6,567 |    6,567 |
| 1992        |           7 |     2,280 |      7,042 |    7,042 |
| 1992        |           8 |     2,280 |      6,799 |    6,799 |
| 1992        |           9 |     2,280 |      6,441 |    6,441 |
| 1992        |          10 |     2,280 |      6,396 |    6,396 |
| 1992        |          11 |     2,280 |      6,072 |    6,072 |
| 1992        |          12 |     2,280 |      6,041 |    6,041 |

Notice how they just put a single report with a bunch of crimes in it for December but nothing else. Also, the number of reports goes up by a big amount and the actual count is the same as reported after 1991.

**Comment by harrisj** [comment]
From the FBI:

> 1991 was the first year for NIBRS submissions in the great state of SC.  All of their data for all of their incidents weren’t here. So, they hand keyed in the full year counts for that year in December. 
>  
> You should see similar “dips” with Alabama around the same time as well.

I wonder if we can get a good listing from the FBI of such dips for each state and why they occurred.  This would be useful to present alongside the trends for that state.

**Comment by harrisj** [comment]
Okay, I did a little digging and here are cases where it looks like states had 0 crimes reported:

- Alabama: 1991, 1992 (0s for Jan-November, amounts entered for December
- DC: no reports on 2/93, 10/93, 2/96
- Florida: no data for 1988, (0s for most of 1989-2014 with annual data entered for one month)
- Iowa: no data at all for 1991
- Kentucky: no data from 7/1987 - 12/1998, 0s for most of 1991-1992 with a single month record)
- Montana: no data for 1994, 1996
- Rhode Island: mostly 0s with 1 month record for 2003 - 2004
- South Carolina: mostly 0s with 1 month record for 1991
- Vermont: no data for 2/93, 4/93, 5/93; no data for 1997

In the annual view, some states compensate with a single record that contains all the counts for the year, but these sort of outages would be more visible if we went to a monthly view for the annual trends

**Comment by LarryBafundo** [comment]
@harrisj, @jeremiak what do we want to do with this issue as it doesn't seem to be a "bug" but a data quality issue?

**Comment by harrisj** [comment]
I don't think it's a "bug" on our part (although I could look into Delaware), but I feel like it's something we should discuss about annotating, since it's something that will likely come up again and again. Basically, I would like that whenever there is a significant factor that is outside the data that affects the data (like these reporting gaps or the change in the rape definition) that we can explain it.

**Comment by jeremiak** [comment]
Let's use a different github label, so that we can easily keep track of all these questions. How about "data quality"?

**Comment by harrisj** [comment]
From the FBI:

> Looked into the South Carolina issue at the end.  The NIBRS data was deemed to be unacceptable and so data was placed into South Carolina December Record to represent the full year. 
The reason that it is lowers is that your other counts include Simple Assault which is not part of aggravated assault.

So, this sounds like it's a bug on our part? Will investigate

**Comment by harrisj** [comment]
Okay, I am a little confused by this one still and will likely need to email the FBI back. If I understand the sentence above, the reason why the count for that year is low because the other SRS or NIBRS-derived data included counts for "Simple Assault" within the RET A "Aggravated Assault" category. But that doesn't quite make sense to me, since UCR's offense is called "Aggravated Assault" too and future NIBRS-derived figures would be low. But this seems to be an artifact of the reporting workflow rather than a bug in our code. Since we are switching to estimated data, this will likely be handled in the new data.
