### ISSUE TITLE
Use FEC-forked version of the swagger-ui JS

### ISSUE THREAD

**Issue by harrisj** [18F/crime-data-api#383]
The [FEC forked Swagger-UI to be more 508-compliant](https://github.com/18F/swagger-ui) which seems like something we should use, but it is also now far behind the Swagger UI codebase so we might need to rebase

**Comment by harrisj** [comment]
So, the current standard Swagger UI has only two major issues for 508 compliance according to a a11y check I ran on https://crime-data-api.fr.cloud.gov/ (both are related to nesting of header fields). It's still pretty terrible on WCAG compliance, but this might be enough to go for now?

**Comment by LarryBafundo** [comment]
@harrisj what do you recommend? Should we close this out and add a separate issue to the backlog for improving WCAG compliance? We can also bring in an outside perspective to evaluate.

**Comment by harrisj** [comment]
Well, I think we are actually okay on 508 Compliance, so if that's the minimum bar, then we can probably let it slide. I know that 18F generally goes for the more strict standard of WCAG2AA compliance and the FEC fork is more like that, but I've found it simply does not display some API responses and doesn't quite work for API requests probably because it's so old. There are a few things we could consider:

1. Make a few simple style tweaks to CSS and page structure to fix the few 508 compliance issues and leave it at that.
2. Try to fix the WCAG2AA issues while preserving the Swagger API's support for running queries by tweaking the default Swagger-UI theme. This might be rather difficult to unpack.
3. Abandon the interactive components and change the documentation to be statically generated from Swagger. This is [what I did for Micropurchase](https://micropurchase.18f.gov/api) for instance. This would remove all of the JS and such that lets users enter their own API key and call the API directly

**Comment by LarryBafundo** [comment]
@harrisj let's go with option #1. what do you think?

**Comment by LarryBafundo** [comment]
related to https://github.com/18F/crime-data-api/issues/443

**Comment by harrisj** [comment]
I think we go with #1 for now. Looks like the main issues are:

1. It uses `<h2>` and `<h4>` instead of `h1/h2/h3` hierarchy. So rename those and restyle sizing as appropriate.
2. Some colors could be adjusted to have better contrast ratios

Both of these should be doable to fix within a day or so of work.

**Comment by LarryBafundo** [comment]
@harrisj, @jeremiak are we still thinking of doing this? if not, let's close this.

**Comment by jeremiak** [comment]
Let's close it and re-open if we decide we need it.
