### ISSUE TITLE
Document reasoning & cost estimate for increasing DB resources 

### ISSUE THREAD

**Issue by LarryBafundo** [18F/crime-data-api#387]
Need to document reasoning and likely cost estimate for upgrading to an SQL-XL AWS instance.

**Comment by LarryBafundo** [comment]
@cacraig moving this into in progress

**Comment by cacraig** [comment]
Here is the working doc for this. - Still working on it.

https://docs.google.com/document/d/1Xu65gsDJHUJqaQLT1n60f7GZbnB7Al0WCnImjaxkNEw

**Comment by harrisj** [comment]
Did you need me to do anything on this?

**Comment by LarryBafundo** [comment]
I don't think so. I just need to work with Alex Bisker to close this out. Will try to do that today.
