### ISSUE TITLE
Add link to README to the downloads and documentation view

### ISSUE THREAD

**Issue by nicoleslaw** [18F/crime-data-api#394]
This issue relates to developing content for the README as well as adding links to the file from the CDE.

---

As a user I want to view a README (accessible via a link) as I am downloading bulk incident data.

This readme should explain the following: 

- [x] This is raw data without estimates
- [x] These files can be joined together by ORI or Incident ID# 

And include: 

- [x] Link to [NIBRS manual] (https://ucr.fbi.gov/nibrs/nibrs-user-manual)

**Comment by LarryBafundo** [comment]
Re: data dictionary, good examples here https://openjustice.doj.ca.gov/data

**Comment by LarryBafundo** [comment]
@cacraig to link the files, will people use the ORI #s, or the incident IDs?

**Comment by LarryBafundo** [comment]
@nicoleslaw thoughts on there being just a single document to include with the download package and the readme also containing the data dictionary?

**Comment by cacraig** [comment]
@LarryBafundo - They can use either. ORI links all the data. Incident ID links to Incident, Offense, Victim, and Offense.

**Comment by nicoleslaw** [comment]
Personally, I think it would be easier to maintain as two separate files, but I defer to our engineering team on this one. The data dictionary may vary based on the data you're downloading. The readme info is generally the same across the project, but is more licensing, how-to info, links to UCR documentation, etc.

**Comment by LarryBafundo** [comment]
okay @nicoleslaw, makes sense. but let's prioritize the readme then over the data dictionary (hopefully we can get them both in during the next sprint). 

@cacraig developing the content for these assets is one thing, but can you tell me how we would include them in the download package? is this something that we could add at the front end? want to understand if we need to group this issue with some of the others that we have planned for the files on S3, like renaming the bulk downloads as "state_NIBRS_and year"

**Comment by nicoleslaw** [comment]
I started a draft here: https://docs.google.com/document/d/1WMZvUOj_EyHc_RvKcCg_XR_Zc03it9JUnjQzbk35qns/edit#

Would love some input from, well, everyone really! @LarryBafundo @RyanSibley @harrisj @jeremiak @brendansudol @cacraig @amberwreed @AvivaOskow ❤️

**Comment by nicoleslaw** [comment]
This is getting pretty close. I will try to wrap up all of the edits on Monday morning after y'all take another look. @LarryBafundo When this v1 draft is ready, should I pass it to someone to implement or add it to To Do?

**Comment by LarryBafundo** [comment]
@nicoleslaw for tasks like this, where the issue refers to both design/content and implementation, let's use the appropriate tag (either "design" or "content") to indicate what stage it's in and then remove it once it's ready for implementation. 

cc: @amberwreed, @AvivaOskow, @RyanSibley

**Comment by nicoleslaw** [comment]
@jeremiak @cacraig @harrisj I have a few remaining questions in the draft. Would you mind taking a look before I wrap up this round? Happy to chat during standup time if that's easiest. https://docs.google.com/document/d/1WMZvUOj_EyHc_RvKcCg_XR_Zc03it9JUnjQzbk35qns/edit#

**Comment by nicoleslaw** [comment]
It looks like we're all set on the content for this round. @LarryBafundo, this is in the api repo — how should we assign it now?

**Comment by LarryBafundo** [comment]
@nicoleslaw i'm going to close this as we linked to the readme on Friday from the downloads and documentation view. its not an ideal location, but at least its accessible now.
