### ISSUE TITLE
Remove redundant `as_csv_response` in base.py

### ISSUE THREAD

**Issue by harrisj** [18F/crime-data-api#397]
This code seems to be only used by the `/codes` API endpoints

**Comment by harrisj** [comment]
I've created a new "code quality" label for flagging this and other cases where code quality issues could be addressed

**Comment by harrisj** [comment]
Will likely be removed/fixed as part of #554

**Comment by LarryBafundo** [comment]
hey @harrisj where do we stand with this?

**Comment by harrisj** [comment]
I'd like to clean this up but in general all of this needs to be simplified. But I haven't gotten it resolved yet

**Comment by LarryBafundo** [comment]
closing as we are going to focus this board on tasks related to the discovery effort; enhancements and new feature work will be tracked on the Jira board managed by CJIS
