### ISSUE TITLE
Arson trend chart includes months in between years along the X axis 

### ISSUE THREAD

**Issue by LarryBafundo** [18F/crime-data-api#399]
When viewing trend data for arson, the chart displays months in between years along the X axis. It looks like no data is associated with these months and so the trend line becomes skewed. 

Here's an example: 

<img width="899" alt="screen shot 2017-02-26 at 12 55 05 pm" src="https://cloud.githubusercontent.com/assets/15899668/23344215/4b1036de-fc2d-11e6-8370-6597af1c8b00.png">

**Comment by jeremiak** [comment]
It looks like we are getting monthly data from the API, any idea why this endpoint is behaving differently?

For reference, here is the API URL that the app uses to get arson data for the trend chart:
`/incidents/count?explorer_offense=arson&per_page=11&year>=2004&year<=2014&state=mi`

**Comment by LarryBafundo** [comment]
@harrisj  ^^^

**Comment by harrisj** [comment]
Yes, I will guess this is my bug. I will look into it

**Comment by harrisj** [comment]
We aren't getting monthly data. Instead it looks like the process of inserting the Arson records was run multiple times and insert multiple records for the same groupings (so it ran 8 times in 1979). We had been getting some errors, and I think these errors were actually writing things to the database. I have run the query that would put things in the table, and there are no duplicates in that.

To fix this, we will need to remove all records where offense="Arson" and rerun the query to add Arson records back. I don't know how much this has affected the Classification counts for Property Crime at well so we might want to just regenerate the whole table when we have a moment. What a mess. Sorry.

**Comment by LarryBafundo** [comment]
ouch. @harrisj we should probably start on this right away then.

**Comment by harrisj** [comment]
I want to wait until after the user interviews are done today. Let me see how bad the issue is

**Comment by LarryBafundo** [comment]
@harrisj, i'm going to move this back into in progress, okay? let me know how it goes.
