### ISSUE TITLE
Standardize API endpoints on postal abbreviations when state parameters are needed

### ISSUE THREAD

**Issue by jeremiak** [18F/crime-data-api#403]
The data set refers to states in different ways depending on what we're looking at ([4 different ways as @harrisj points out](https://github.com/18F/crime-data-explorer/issues/410#issuecomment-282845598)). For the API user, this creates some confusion and uncertainty about what to use and when.

We should standardize on postal abbreviations as they're the most commonly known.

**Comment by harrisj** [comment]
I actually have a few related issues I'd like to create about refactoring the API if we reach a sprint where we feel ready for them.

**Comment by LarryBafundo** [comment]
hey @harrisj is this issue a duplicate? we seem to have a couple others floating around this same idea, although maybe I'm missing the differences.

**Comment by jeremiak** [comment]
@LarryBafundo The explorer card is meant to represent the front end app work to be done to stop using state codes when requesting data from the API. This issues is for those API changes

**Comment by jeremiak** [comment]
This looks great on the currently deployed app. Closing
