### ISSUE TITLE
Update: Replace state_id with the state_postal_abb

### ISSUE THREAD

**Issue by harrisj** [18F/crime-data-api#406]
I think it would be good to clean up a few inconsistencies with the API as part of this sprint or in the next phase:

- [x] Replace `state_id` with the `state_postal_abbr` as a parameter for selecting states. All states have postal abbrs, so this should work. The parameter should be accepted if uppercase or lowercase (see also #403)
- [x] See if we can use `fips` for identifying counties in county-specific API requests. Note that [some counties in the DB are not real](https://github.com/18F/crime-data-api/issues/386) and thus might not have FIPS codes. Will we ever need to request them.
- [ ] Rename the `../offenses` endpoints that show counts of a variable within a specific offense to be `../offense_types/<offense>` rather than having `offense` be a query parameter (but I guess how do we denote diff between an `explorer_offense` or `nibrs_offense`? Might be two different types of URL)
- [x] Move the `/geo/states/<state>/participation` endpoint to `/participation/states/<state>`
- [x] Move the `/agencies/participation` endpoint to `/participation/agencies`
- [x] Check that various endpoints create an appropriate CSV filename when passed `output=csv`
- [x] Revert the change I made to `agencies/participation` to accept a range. It should be able to just take `year>=X&year<=Y` arguments like other endpoints.

The big thing I would like to do is to switch Swagger to being manually edited and use that as a basis for testing that API responses match what the Swagger specification says they should.

**Comment by harrisj** [comment]
I think the other long-term goal we might consider is to limit the API requests to only use basic or denormalized views tailored to their responses. This could then mean that "production" databases would be a smaller subset of the full DB we need to creating such views (although I have no idea what fraction of size they would be and they would still get large once we start including NIBRS single incidents again)

**Comment by harrisj** [comment]
cc @brendansudol and @jeremiak since they will be using the API changes

**Comment by harrisj** [comment]
One question: should we also rename `/incidents/count` to something more descriptive?

**Comment by jeremiak** [comment]
Yes please, since it does also sometimes return SRS data as well, right?

**Comment by harrisj** [comment]
Well, it's always SRS data, it's just some was reported that way originally and some was converted from NIBRS

**Comment by harrisj** [comment]
So, this might be something for another PR, but I think we need to go back and reexamine the `/agencies' endpoints for getting a list of agencies or looking at a specific agency. I would like to recommend that we denormalize this as well into a single table or view (I think all the associations are essentially 1-1). Then we could also more easily inline participation data or such for that agency. Is anything in the CDE using those endpoints currently?

**Comment by LarryBafundo** [comment]
@harrisj can we please get an update on this issue prior to the end of the sprint (tomorrow)? if there are items that we want to defer to the next sprint we should break them out into a separate issue, or create a new issue or epic to track future work. i believe @jeremiak will also be adding tasks for API cleanup based on the results of last week's testing. thanks!

**Comment by harrisj** [comment]
So, I think @cacraig was doing some of the reorganization (but I can pick up some of these). I do have a PR pending review that is for the new API documentation that will allow me to close out many of the issues linked in https://github.com/18F/crime-data-explorer/issues/314

**Comment by harrisj** [comment]
Do we have any API endpoints that require you to use the state_id and not the state postal?

**Comment by harrisj** [comment]
Also, I was thinking of renaming the `*/count/...` offenses to be more like `/nibrs/counts/offenses/...` and `/nibrs/counts/victims`. This would mean we might have URLS that look like `/nibrs/counts/offenses/states/OH/race_code/offense_types/homicide` or such. What do you all think? @jeremiak @cacraig

**Comment by jeremiak** [comment]
I like that approach. I like including "nibrs" as that makes it clear what the source is and by having `states/:state/` URL parameter it seems logical that we could also include `agencies/:ORI/` endpoint.

**Comment by LarryBafundo** [comment]
@harrisj looks like you've made more progress with this than what the checklist shows. Can you please update this issue? Depending on where you're at, we may close this issue out and create a new one for what's not finished.

**Comment by LarryBafundo** [comment]
@jeremiak what do you think about retiring this issue as well and adding new ones to account for changing state_id with state_postal_abbr and renaming the offense endpoints. seems like we would want to hold off on exploring if we can use fips for identifying counties for now.

**Comment by LarryBafundo** [comment]
Prioritizing replacing state_id with the state_postal_abbr in the short-term for this sprint.

**Comment by LarryBafundo** [comment]
moving this back to ready since nobody seems to be owning it while in progress.

**Comment by harrisj** [comment]
I think this is done. Closing
