### ISSUE TITLE
R and U offender relationships in victim counts

### ISSUE THREAD

**Issue by harrisj** [18F/crime-data-api#408]
For instance, see https://crime-data-explorer.fr.cloud.gov/#/explorer/arkansas/aggravated-assault and there are weird realtionship types in there
 
![crime_data_explorer](https://cloud.githubusercontent.com/assets/2044/23526319/a566a624-ff5f-11e6-804e-6ce1e86082f2.jpg)

I'm a little perplexed since this seems to be coming from the API. But these values only exist in the `offense_victims_table`

``` sql
select distinct offender_relationship from offense_victim_counts where state_id IS NULL;
```

* Victim Was Spouse
* Victim Was Grandparent
* Victim Was Babysittee
* Victim Was Stepparent
* Victim Was Stepsibling
* Victim Was Stranger
* Victim was Employer
* Victim was Ex-Spouse
* Victim Was Stepchild
* N
* Victim Was Child
* R
* Victim Was Boyfriend/Girlfriend
* Victim Was Grandchild
* Victim Was In-law
* Victim Was Common-Law Spouse
* Victim Was Sibling
* Homosexual Relationship
* U
* Victim Was Other Family Member
* Relationship Unknown
* Victim Was Acquaintance
* Victim was Employee
* Victim Was Offender
* Victim Was Neighbor
* Victim Was Child of Boyfriend or Girlfriend
* Victim Was Friend
* Victim Was Parent
* Victim was Otherwise Known
(30 rows)

But when I looked at the `victim_counts` table (not scoped to offense they aren't there)

``` sql
select distinct offender_relationship from victim_counts where state_id IS NULL and county_id IS NULL;
```
(this returns 43 rows)

and when I look at the `nibrs_victim_denorm` table from which these are derived they aren't there

``` sql
select distinct offender_relationship from nibrs_victim_denorm order by offender_relationship;
```

And it only returns 27 rows

* Homosexual Relationship
* Relationship Unknown
* Victim Was Acquaintance
* Victim Was Babysittee
* Victim Was Boyfriend/Girlfriend
* Victim Was Child
* Victim Was Child of Boyfriend or Girlfriend
* Victim Was Common-Law Spouse
* Victim was Employee
* Victim was Employer
* Victim was Ex-Spouse
* Victim Was Friend
* Victim Was Grandchild
* Victim Was Grandparent
* Victim Was In-law
* Victim Was Neighbor
* Victim Was Offender
* Victim Was Other Family Member
* Victim was Otherwise Known
* Victim Was Parent
* Victim Was Sibling
* Victim Was Spouse
* Victim Was Stepchild
* Victim Was Stepparent
* Victim Was Stepsibling
* Victim Was Stranger

I'm not sure what is going one here. Here is the code that creates the `offense_victims_count_2011` table for instance (where these values are spotted among others):

``` sql
create materialized view offense_victim_counts_2011 as select count(victim_id),ethnicity,resident_status_code,offender_relationship,circumstance_name,offense_name, state_id, race_code, age_num, sex_code 
from ( SELECT DISTINCT(victim_id), ethnicity, age_num,race_code,resident_status_code,offender_relationship,circumstance_name,year,offense_name, sex_code, state_id from nibrs_victim_denorm where year = '2011' and state_id is not null) as temp
GROUP BY GROUPING SETS (
    (year, offense_name, race_code),
    (year, offense_name, sex_code),
    (year, offense_name, age_num),
    (year, offense_name, ethnicity),
    (year, offense_name, resident_status_code),
    (year, offense_name, offender_relationship),
    (year, offense_name, circumstance_name),
    
    (year, state_id, offense_name, race_code),
    (year, state_id, offense_name, sex_code),
    (year, state_id, offense_name, age_num),
    (year, state_id, offense_name, ethnicity),
    (year, state_id, offense_name, resident_status_code),
    (year, state_id, offense_name, offender_relationship),
    (year, state_id, offense_name, circumstance_name)
);
```

Not sure how those code values get in there if they aren't in `nibrs_victim_denorm` Is this a DB error?

**Comment by LarryBafundo** [comment]
Let me share with CJIS and see if they have any insights.

**Comment by harrisj** [comment]
Just to clarify, this was a bug in how the `offense_victim_counts` table was assembled from sub-aggregations (not an issue with data provided to us). We have corrected the code and are regenerating the table.

**Comment by LarryBafundo** [comment]
@harrisj been reading the NIBRS spec and came across some of the weird classifications mentioned by this issue. see below: 

<img width="660" alt="screen shot 2017-03-03 at 3 54 23 pm" src="https://cloud.githubusercontent.com/assets/15899668/23573326/fdc2f4c4-0029-11e7-8ba4-b524644f8828.png">

**Comment by cacraig** [comment]
^ This was a bug, we rebuilt the dataset, and it should be fixed now.

**Comment by LarryBafundo** [comment]
verified on master, great work.
