### ISSUE TITLE
Add victim/offender ethnicity data to NIBRS dimensions

### ISSUE THREAD

**Issue by LarryBafundo** [18F/crime-data-api#410]

**Comment by LarryBafundo** [comment]
@cacraig moving this into in progress, per our earlier convo.

**Comment by cacraig** [comment]
This one is on hold because it's going to have to bring down the victims/offenders endpoints. Probably best to wait until we know we can withstand some downtime.

**Comment by LarryBafundo** [comment]
update: we are holding off on this until we finalize our demo schedule with the FBI.

**Comment by LarryBafundo** [comment]
closing this as it now covered by other tasks.
