### ISSUE TITLE
Map "location type" to selected offense within the explorer view 

### ISSUE THREAD

**Issue by LarryBafundo** [18F/crime-data-api#416]
Currently, when we show the breakdown of NIBRS data by "location type", we aggregate location data for all offenses within that location, rather than the specific offense selected. For example, rather than showing where all "arson" offenses occurred within Ohio, we are showing where all offenses within Ohio occurred. 

We should update the API endpoint to show only the location type for the offense selected. 

![crime_data_explorer](https://cloud.githubusercontent.com/assets/15899668/23778163/84696928-04ed-11e7-8681-68a1ce4f8ed1.jpg)

**Comment by LarryBafundo** [comment]
@jeremiak is this ready for review?

**Comment by jeremiak** [comment]
It is, apologies for not applying the label

**Comment by LarryBafundo** [comment]
looks good
