### ISSUE TITLE
Rebuilding the participation table should use same rename strategy as reta_month_offense_subcat_summary

### ISSUE THREAD

**Issue by harrisj** [18F/crime-data-api#417]
Instead of a drop and then generate, build with a different name and rename the original table

**Comment by jeremiak** [comment]
Per [this comment from #422](https://github.com/18F/crime-data-api/pull/422#issuecomment-286467623), this seems like it should be done.

Is this ready to be closed @harrisj or @cacraig?

**Comment by harrisj** [comment]
Yes, this should be closed.
