### ISSUE TITLE
Reta_month_offense_subcat_summary should ignore the records with actual_status=3

### ISSUE THREAD

**Issue by harrisj** [18F/crime-data-api#418]
Every counted field in `reta_month_offense_subcat` has a corresponding `_status` equivalent. In the comment for `actual_status` I see this message

> 0 is for considering data completely, 2 for dont calculate, but do publish, 3 for dont calculate and dont publish, 4 for legacy rape data submitted by an agency that reports using the new rape definitions, 6 for legacy rape data for reporting but not calculation, 7 for legacy rape data not for reporting or calculation

We use the `reta_month_offense_subcat` table to assemble the counts within the `reta_month_offense_subcat_summary` table (hence the name). It seems like we should not include any records where `actual_status IN (2, 3)` when we are building those counts. I looked at 2014, and approximately 1/3 of the records had `actual_status=3.` They all had 0 counts, so their effect on the final scores were negligible, but it seems like something we should change.

**Comment by harrisj** [comment]
This might be a moot point, because we are are going to be using estimated trends in the future, making the specific construction of this table now largely irrelevant. But there are some cases where we might still need to care about this:

1. When reporting trends for specific agencies, those would still be derived from the reta_month tables if I understand it correctly.
2. We still need to see if arson will be included in the estimated data they provide. If not, we will still have to be wary of this status when merging.

**Comment by LarryBafundo** [comment]
keeping this issue in the backlog per the points made by @harrisj. also checking with Loretta to see if arson data will be included in the estimates CJIS is providing.

**Comment by LarryBafundo** [comment]
@harrisj confirming that arson will not be included in the estimates Loretta is providing. How does that affect the path forward with this issue?

**Comment by harrisj** [comment]
We can do the computation to count in Arson. In the case here, we probably need to clarify a few things first though:

1. Is there an objection from the FBI to adding in raw counts for arson to a table that is nothing but estimated data that would stop us from doing this at all?
2. Are there other rules we should follow besides checking `actual_count==0` I seem to recall seeing something about not counting arson unless the agency reports for 12 months of arson data (not the same as 12 months of SRS necessarily), but that might be about how it gets into the CDE in the first place
3. Should we add the arson counts to the `property crimes` total? This would make them deviate from the counts in Crime in the US though.

**Comment by LarryBafundo** [comment]
@harrisj I'll ask them about this today and copy you.

**Comment by LarryBafundo** [comment]
answers from Loretta: 

1. I cannot speak for management but I’m going to say yes there is an objection.  My opinion:  adding actuals in with estimated will led to confusion with the data and the counts could possibly be significantly lower than an estimation would.  Arson is difficult to estimate because of the offense and the way it is reported.

2. Not sure I follow this.

3. No, do not add the arson counts to the property crime.  The Program has not made that change yet. 

4. Tribal agencies are included with state estimates (covered within the state’s population).  Territories are not estimated.  We are currently in the process of re-evaluating our estimation procedures and will address the Arson and territories in that process.

**Comment by LarryBafundo** [comment]
so, to recap, sounds like they dont want us to combine estimated and actuals, they dont want us to combine arson to the property crime totals, and they might either come up with a new way to estimate arson, or they may ask us to drop it from the CDE.

**Comment by harrisj** [comment]
Welp, better to figure this out now than after we build it I guess

**Comment by harrisj** [comment]
This change was made in #519
