### ISSUE TITLE
National participation endpoint is returning data for Alabama (JSON & CSV)

### ISSUE THREAD

**Issue by jeremiak** [18F/crime-data-api#420]
The following two requests return data that should be for the national perspective, but come with `state` set to "Alabama":

* `/participation/national`
* `/participation/national?output=csv`

State endpoints (like `/geo/states/AK/participation`) seem to be returning the proper data

**Comment by harrisj** [comment]
I was told it should return participation data for all states (and what you are seeing is Alabama because per_page is not being set so it's defaulting to the first 10 rows?) Am I wrong about what the data should be, @LarryBafundo?

**Comment by LarryBafundo** [comment]
the national participation endpoint should provide participation data for all states.

**Comment by jeremiak** [comment]
Oh, got it and now I understand why you had put the `count` in previously.

@LarryBafundo that statement is ambiguous to me. Let me try and ask it a different way.

Should the API endpoint look like this:

```
{
  "results": [
    {
      "covered_population": 4657443,
      "nibrs_reporting_agencies": 1,
      "nibrs_reporting_rate": 0.00210526315789474,
      "reporting_agencies": 372,
      "reporting_rate": 0.783157894736842,
      "state_name": "Alabama",
      "total_agencies": 475,
      "total_population": 4861676,
      "year": 2014
    },
    ... with a similar object for every state and every year
  ]
}
```

Or should it just return the data calculated for the entire nation, meaning there would not be a `state_name` field and all of the numbers would be aggregates from across the country?

I thought we would do the second one, so that the front end does minimal calculations and aggregations (also a nice benefit of transferring less data over the wire). It also lines up with the rest of the behavior as all the numbers shown are aggregates.

On the other hand, I see the appeal of not having to make 50+ API requests to get all of this data broken out at the state level.
