### ISSUE TITLE
DC reports a single homicide for 2004 through 2014

### ISSUE THREAD

**Issue by jeremiak** [18F/crime-data-api#427]
<img width="809" alt="screen shot 2017-03-15 at 11 52 54 am" src="https://cloud.githubusercontent.com/assets/780941/23957527/f9a43a92-0975-11e7-8362-917d995d81ac.png">

Explorer url:
https://crime-data-explorer.fr.cloud.gov/explorer/district-of-columbia/homicide

**Comment by harrisj** [comment]
This is because the only agency in DC to report to NIBRS is the Metro Transit Police, and there was one homicide on Metro I guess.
