### ISSUE TITLE
Use postal abbreviations instead of state_code in LEOKA CSV

### ISSUE THREAD

**Issue by jeremiak** [18F/crime-data-api#430]
The LEOKA CSV download from the Downloads and Documentation page uses `state_code` which is ambiguous because the FBI uses a few different state codes and they're hard to keep track of. We use postal abbreviations else where, so let's use them here too since they're easy to define.

data_year|state_code|leoka_assault|leoka_felony|leoka_accident
---|---|---|---|---|
1960|17|0|0|0
1960|39|0|0|0
1960|34|0|0|0
1960|35|0|0|0
...

**Comment by LarryBafundo** [comment]
FYI - @RyanSibley

**Comment by RyanSibley** [comment]
got it. thanks.

**Comment by RyanSibley** [comment]
Is the field name changing as well? Or just the values?

**Comment by jeremiak** [comment]
In other CSVs I've seen from our site it has used `state_postal_abbr` as the column heading. I think we should use the consistent heading and then change the values

**Comment by LarryBafundo** [comment]
@cacraig can you make this change to the update script for our LEOKA dataset? We should use postal abbreviations for the state rather than state_code.

**Comment by cacraig** [comment]
This is done, and has been pushed to: s3://${BUCKET_NAME}/leoka.csv
