### ISSUE TITLE
Identify & document the key constraints, in terms of data quality and availability, for reporting areas below the state-level

### ISSUE THREAD

**Issue by LarryBafundo** [18F/crime-data-api#431]
This issue is aimed at understanding the key constraints we need to consider when developing solutions around granularity. 

@harrisj has already started a great write-up on this here: https://docs.google.com/document/d/1y16IT_age4UWeLnYsnzNg01FQG6bfuS_h3mbGPe1wlk/edit

And has provided the following reports: 

county level participation: https://docs.google.com/spreadsheets/d/1-HWNX_EcUU1DlfZ5WUMEbagncbZtY3b-H50CKMt2gAI/edit#gid=0

city participation: https://docs.google.com/spreadsheets/d/1njYfDT1m9TTDeoXOz_2eblQGReF2s9NNRd75pnU_wi4/edit#gid=0

**Comment by harrisj** [comment]
Curious to hear about where we are now on this after today's meeting
