### ISSUE TITLE
Police employee download has same population for every year of a state

### ISSUE THREAD

**Issue by jeremiak** [18F/crime-data-api#433]
All rows for a given state in the `pe_employment.csv` download have the same population value. For example, all California years have a population value of 16190816.

**Comment by harrisj** [comment]
I had fixed this in the past I thought. It was a caching bug, but let me check it out.

**Comment by harrisj** [comment]
Looping in @cacraig, did we build these by running some SQL queries or by calling a specific API endpoint?

**Comment by harrisj** [comment]
So, the internal SQL needs to be tweaked a little. It was calling `ref_state_population` with a LIMIT 1 which returned only the most recent population for a given state. Going to suggest that we not use `ref_state_population` and instead use what's computed in `cde_participation_rates`. This is the modified internal SQL

``` SQL
(SELECT q.state_postal_abbr as state_postal_abbr, q.data_year as data_year, q.officer_count as officer_count, round( ( (q.officer_count / population) * 1000)::numeric, 2) as officer_rate_per_1000, q.civilian_count as civilian_count, round( ( (q.civilian_count / population) * 1000)::numeric, 2) as civilian_rate_per_1000, population from (SELECT (SELECT state_postal_abbr from ref_state where ref_agency.state_id = ref_state.state_id limit 1) as state_postal_abbr, (SELECT total_population from cde_participation_rates where ref_agency.state_id = cde_participation_rates.state_id AND cde_participation_rates.data_year = pe_employee_data.data_year limit 1) as population, pe_employee_data.data_year, SUM(COALESCE(male_officer) + COALESCE(female_officer)) as officer_count, SUM( COALESCE(female_civilian) + COALESCE(male_civilian) ) as civilian_count from pe_employee_data JOIN ref_agency ON (pe_employee_data.agency_id = ref_agency.agency_id) GROUP BY ref_agency.state_id, pe_employee_data.data_year) q where q.population > 0 AND q.state_postal_abbr='CA' order by q.data_year, q.state_postal_abbr desc);
```

@cacraig, do you mind looking it over and seeing if it's good to regenerate that CSV?

**Comment by LarryBafundo** [comment]
@cacraig, @harrisj how are we coming along with this one?

**Comment by cacraig** [comment]
This has been pushed to s3://${BUCKET_NAME}/pe_employee_data.csv
