### ISSUE TITLE
Validate data dictionary

### ISSUE THREAD

**Issue by RyanSibley** [18F/crime-data-api#436]
Please review the dictionary and make sure the definitions are correct. Keep an eye out for the following things:

- [ ] Identify places where we can provide values and we don't already

- [ ] Make sure the descriptions accurately describe the data and locationspecific to a value, if relevant. 

- [ ] Give the trafficking section some love -- I feel like I was guessing  with a lot of that. 

- [ ] If you see TKTK, it means I'm still looking for the info. If you happen to know where I can find it, let me know!

Also, check out this issue for notes I've been making along the way: https://github.com/18F/crime-data-explorer/issues/575

**Comment by cacraig** [comment]
One note -> For offense_name, we have that mapping to the NIBRS offense_code. Which isn't quite right. More accurately, it's the value of the NIBRS code, or just that: The NIIBRS Offense Name.

**Comment by LarryBafundo** [comment]
@RyanSibley okay to close this out?

**Comment by RyanSibley** [comment]
yes!
