### ISSUE TITLE
Some agencies have abandoned NIBRS

### ISSUE THREAD

**Issue by harrisj** [18F/crime-data-api#437]
One of our general assumptions is that once you go NIBRS, you don't go back. However, while debugging #426, I discovered it was due to a single agency that had reported NIBRS for a while and then switched back to just SRS. I did a little more digging and discovered with this query

```sql
select DISTINCT ra.agency_id::text, rs.state_name, MIN(cap.data_year)::text AS nibrs_start, MAX(cap.data_year)::text AS nibrs_end, ra.ori, ra.pub_agency_name from cde_annual_participation cap
JOIN cde_annual_participation cap2 ON cap.agency_id = cap2.agency_id
JOIN ref_agency ra ON ra.agency_id = cap.agency_id
JOIN ref_state rs ON rs.state_id = ra.state_id
WHERE cap2.data_year > cap.data_year
AND cap.reported_nibrs = 1
AND cap2.reported_nibrs = 0 
GROUP BY rs.state_name, ra.agency_id::text, ra.ori, ra.pub_agency_name
ORDER by ra.ori;
```

There are some 2847 agencies that reported NIBRS in one year and abandoned in a later year. IN some cases it was immediate (there are lot in Alabama who reported NIBRS in 1991 and immediately stopped in 1992), but there are some other cases where they tried for longer. [See the Google sheet for details](https://docs.google.com/a/gsa.gov/spreadsheets/d/1ovyAt2iSKRXVHuvxb2gVAp6aKkRCQPWabF6IedDeeXk/edit?usp=sharing)

**Comment by harrisj** [comment]
From the FBI:
> Some agencies have abandoned NIBRS and some have been “decertified”.  Regardless of the reason, agencies do submit summary instead of NIBRS and this can happen month to month.

**Comment by harrisj** [comment]
Going to close this, since it isn't an open issue, but it's something to be aware of

**Comment by LarryBafundo** [comment]
@harrisj is there anyway to know how extensive this problem is? during the meeting on tuesday i mentioned this, and people seemed to be surprised that it happened.

**Comment by harrisj** [comment]
Yep, the spreadsheet I have linked above seems to be all of the examples I found. I was rather surprised by it too, that's why I wanted to explore it.
