### ISSUE TITLE
Make Swagger-UI WCAG2AA-compliant

### ISSUE THREAD

**Issue by harrisj** [18F/crime-data-api#443]
This looks bad at first sight

![swagger_ui](https://cloud.githubusercontent.com/assets/2044/24470924/824619d8-148e-11e7-83d6-8a1a95a8f07e.jpg)

But given how the page is dynamically generated, this might be just the same few errors repeating over and over.

**Comment by LarryBafundo** [comment]
@harrisj is this still an issue for us?
