### ISSUE TITLE
Swagger API documentation needs some help

### ISSUE THREAD

**Issue by harrisj** [18F/crime-data-api#444]
For starters, it needs a good introduction text on what the API is and how to use it. In addition, methods can be grouped into one or more tagged sections that have their own optional introductory text.

See https://crime-data-api.fr.cloud.gov/ for documentation

**Comment by LarryBafundo** [comment]
relates to #314

**Comment by LarryBafundo** [comment]
closing in favor of https://github.com/18F/crime-data-explorer/issues/314
