### ISSUE TITLE
Develop ORI endpoint

### ISSUE THREAD

**Issue by LarryBafundo** [18F/crime-data-api#447]
The purpose of this effort is to enable an ORI-specific view of the data, which in turn may be aggregated in order to represent a single agency with multiple ORIs associated with it.

**Comment by LarryBafundo** [comment]
@jeremiak let me know if i've described this adequately, or if more direction is needed.

**Comment by harrisj** [comment]
So, we have had a prior `/agencies` endpoint that could probably be retooled

**Comment by jeremiak** [comment]
Yup, maybe something like `/agencies/:ORI/counts` to match the structure of requests you had proposed [in #406](https://github.com/18F/crime-data-api/issues/406#issuecomment-290187122)?

I expect that the data should be returned in a similar structure to the current summary related endpoints:

```
"results": [
    {
      "actual": 660,
      "classification": "Property",
      "offense_code": "X_ARS",
      "offense": "Arson",
      "ORI": "NVXXXXXXX",
     "agency_name": "Las Vegas Police Department",
      "state": "NV",
      "year": 1979,
      "offense_category": "Arson",
      "unfounded": 6, // not sure that we have this for agencies
      "reported": 666, // // not sure that we have this for agencies
      "cleared": 113, // // not sure that we have this for agencies
      "juvenile_cleared": 50, // not sure that we have this for agencies
  },
  ...other similar objects for each year in the requested range or for all time with no range selected
```

Thoughts?

**Comment by harrisj** [comment]
We could look to add this. This would require us to set up the necessary backend table for offenses summarized by agency in #448

**Comment by LarryBafundo** [comment]
@harrisj, @cacraig who should be assigned this? seems like @cacraig is more likely?

**Comment by harrisj** [comment]
We are still working on the backend data table in #448 but have made some real strides in optimizing the creation of that table

**Comment by LarryBafundo** [comment]
@harrisj, @cacraig hey folks, can we update larger issues like this every few days with where we're at?

**Comment by cacraig** [comment]
@LarryBafundo - Sure thing. See #478  - Still working on this implementation.
