### ISSUE TITLE
Make a denormalized table for ref_agency 

### ISSUE THREAD

**Issue by LarryBafundo** [18F/crime-data-api#449]

**Comment by harrisj** [comment]
I figure this might potentially include the following columns. Should we call it `agencies` or `cde_agencies` or such?

|column|notes|
|-|-|
|ori||
|legacy_ori||
|name|(we actually have 3 names fields to choose from here)|
|city||
|state_id||
|state_abbr||
|metro_division_id|joined from ref_population|
|msa_id|joined from ref_population|
|start_year|when first reported|
|end_year|when stopped reporting (should be NULL for active|
|agency_status||
|tribe_id|(if agency is a tribe, will have to join against ref_tribe to see)|
|campus_id|(if agency is a campus)|
|current_year|the last year we have on record for them for population, etc.|
|population|joined from ref_agency_population for current_year|
|population_group_code|joined from ref_population_group for current_year|
|population_group_name|joined from ref_population_group|
|months_reported|how many months the agency reported in the current_year|
|nibrs_months_reported|how many months the agency filed NIBRS in the current_year|
|submitting_agency_id|the ID of the submitting agency|
|submitting_sai|the SAI for the submitting agency|
|covered_by_id|the agency_id of the agency who covered it in current_year|
|covered_by_ori|the ORI of the covering agency|
|covered_by_name|should I bring in population group for covered_by?|
|total_police|joined from pe_employee_data|
|total_civilians|joined from pe_employee_data|
|staffing_year|the most recent year they reported staffing in pe_employee_data|
|lat/lng|if we can join from a crosswalk for geocoded search|

**Comment by harrisj** [comment]
I can start on this if you want, since I know these tables pretty well
