### ISSUE TITLE
Explore how we can programmatically show agencies that have reported sufficient data

### ISSUE THREAD

**Issue by LarryBafundo** [18F/crime-data-api#451]
The FBI has asked us to only show agency data when that agency has reported 12 months worth of data. How will we do this programmatically and how will we know when to show an agency that has reported a full year's worth of data, but over the course of a single month or so?

**Comment by LarryBafundo** [comment]
@harrisj cynthia is going to help us figure out an approach for this; but can I tag you as the lead for this particular issue?

**Comment by harrisj** [comment]
Yes, please do!

**Comment by harrisj** [comment]
We sent this to the FBI for comment next week and are waiting on their feedback

**Comment by LarryBafundo** [comment]
understanding how we can definitively know when an agency has reported 12 month worth of data is still an open question. working with cynthia and CJIS to clarify an approach.

**Comment by LarryBafundo** [comment]
@harrisj seems like we can close this since we can use the reported_flag: Y, N to determine if an agency has reported 12 months worth of data. right?

**Comment by harrisj** [comment]
Yes, my fear is that it would not be enough for agencies in places like Florida that report an entire year of data in a single month, but I am happy to report I am wrong and `reta_month.reported_flag` works for those as well.
