### ISSUE TITLE
Enable agency lookup by zip code

### ISSUE THREAD

**Issue by harrisj** [18F/crime-data-api#453]
We have explored several prototypes that allow people to look up agencies by location. Zip code is a good way beyond city name for users to identify a specific area they want to find agencies for. There is a good question is "search by zip" means "find agencies near this zip" (proximity) or "find agencies whose jurisdictions include this zip" (coverage). We have several ways we could implement this, which favor one or the other.

Note that the FBI does not provide us with zip codes for agencies. There is a crosswalk from the ICPSJ that does have such information, but it's unclear how many agencies it covers. There are several options we could try:

1. **Centroid Distance (proximity)**: Load a mapping of zip codes <-> lat/lng and use the lat/lng for agencies in the crosswalk to translate a zipcode to a lat/lng and find all agencies within N miles of that lat/lng. Note that this would only find geocoded agencies, but we could also use this for arbitrary "Agencies Near Me" queries.
2. **Exact Zip Match (coverage)**: use the zip codes in the crosswalk for agency addresses for an exact match. This would work best for small towns, but not work for cities where the police department would be in a different zip than another section of the city.
3. **County Mapping (coverage/proximity)**: the FBI gives us a mapping of agencies to counties and [it should be possible to map zip codes <-> county](https://www.huduser.gov/portal/datasets/usps_crosswalk.html), so we would translate zip to county and find all agencies in that county. This would be a bit weird in that it would include agencies from miles away up county, but might skip out on agencies less than a few miles away because they're in a separate county, but I suppose distance lookup can be weird too.

I'm inclined to try out the third option, but suggestions welcome. The first option is probably the next best approach, but I think we would also want to evaluate how good crosswalk coverage is too.

**Comment by LarryBafundo** [comment]
@harrisj the county mapping seems to make the most sense, but lets try to settle on a direction prior to the end of the current sprint. 

cc: @jeremiak, @amberwreed

**Comment by harrisj** [comment]
I wanted to see how technically feasible the third option was, so I wound up building it partially (https://github.com/18F/crime-data-api/pull/454). But let me go see some rough parameters on how many results it might return...

**Comment by harrisj** [comment]
One issue is that some counties do have a lot of agencies. Here are the 20 largest counties:

| state_name    | county_id   | county_name   |   count |
|---------------|-------------|---------------|---------|
| Illinois      | 722         | COOK          |     181 |
| Pennsylvania  | 2258        | ALLEGHENY     |     141 |
| California    | 215         | LOS ANGELES   |     120 |
| Missouri      | 1514        | ST LOUIS      |      88 |
| Massachusetts | 1203        | WORCESTER     |      81 |
| Massachusetts | 1198        | MIDDLESEX     |      78 |
| New Jersey    | 1924        | BERGEN        |      77 |
| Virginia      | 3668        | NOT SPECIFIED |      74 |
| Ohio          | 2073        | CUYAHOGA      |      67 |
| Pennsylvania  | 2296        | LUZERNE       |      64 |
| Michigan      | 1306        | OAKLAND       |      64 |
| Pennsylvania  | 2302        | MONTGOMERY    |      62 |
| Pennsylvania  | 2265        | BUCKS         |      61 |
| Pennsylvania  | 2262        | BERKS         |      61 |
| Pennsylvania  | 2271        | CHESTER       |      61 |
| Texas         | 2715        | HARRIS        |      60 |
| New Jersey    | 1935        | MONMOUTH      |      58 |
| Pennsylvania  | 2267        | CAMBRIA       |      58 |
| Pennsylvania  | 2292        | LANCASTER     |      58 |
| New York      | 2053        | WESTCHESTER   |      58 |

Since a zip-county mapping might pull in 1 or more counties, this could return a large list. Some additional filtering mechanism or sorting by descending population might work for most people though

**Comment by LarryBafundo** [comment]
hey @harrisj we're going to bring this up during sprint planning tomorrow with Cynthia & Sammy and get their opinion, but has your thinking on this changed since you first wrote up this issue? seems like in either case we're either looking at providing too narrow of a view or one that is too large with many results. so maybe that means we need a secondary qualifier to narrow the results? 

also, before we get into evaluating which approach to take we should first confirm that we can even get zipcodes for all of our agencies. 

cc: @amberwreed

**Comment by harrisj** [comment]
Well, the current approach I have is to translate zip code to 1 or more counties and then pull in all the agencies in those counties. This could lead to some unexpected behavior: if I enter my own zip code, it'll pull in country agencies 30 or more miles away but not include agencies just over the border in DC or Prince Georges' County. But it doesn't rely on mapping agencies to zip codes or lat/lng via the ICPSJ crosswalks (I did use a zip-county crosswalk from HUD though). And it wouldn't work for statewide agencies or NYPD

It's possible that the crosswalks would do pretty well for locating many agencies, I just haven't had a chance to evaluate how good it is. I've been told the coverage is pretty good however, so if they gave us clearance to use the ICPSJ crosswalks, I would be happy to explore it.

**Comment by harrisj** [comment]
Ooops, I meant the [ICPSR crosswalks](https://www.icpsr.umich.edu/icpsrweb/ICPSR/series/366)

**Comment by LarryBafundo** [comment]
should this still be in review? we're tabling agency search by zipcode for now...

**Comment by LarryBafundo** [comment]
@harrisj closing this as we're not supporting search by zipcode for this first iteration of the CDE and we have a user story along those lines in the backlog.
