### ISSUE TITLE
Need to recalculate NIBRS/SRS participation

### ISSUE THREAD

**Issue by harrisj** [18F/crime-data-api#456]
So, 100% NIBRS states are reporting only 80% NIBRS participation in my stats. Those statistics were calculated before I knew about `dormant_year` and agencies covering other ones. I need to reexamine a few things:

- [x] Does a covered agency get listed as reporting SRS or NIBRS?
- [x] Does a dormant_year agency get listed in `reta_month` and `nibrs_month` after it is dormant?
- [x] Do `0 population` agencies (that aren't covered or dormant) show up in reta_month for when they have no crimes?

My rates for participation are probably a bit low as a result. Rebuilding this would involve regenerating the following tables in sequence:

- `cde_annual_participation`
- `cde_participation_rates`
- `cde_agencies`

**Comment by harrisj** [comment]
Need to figure out #458 first

**Comment by harrisj** [comment]
Looks like dormant agencies sometimes show up in `reta_month` after going dormant, although always with `reported_flag=N`

**Comment by harrisj** [comment]
Okay, I've found some cases where an agency is listed as covered by another yet is also reporting a count. Will have to investigate

**Comment by harrisj** [comment]
Okay, after running some queries, it looks like I might want to use the following logic:

An agency participates in SRS for a month if:
1. It has `reta_month.reported_flag` set to `Y` for a given month
2. It is covered by another agency with `reta_month.reported_flag` set to `Y`

It reports to NIBRS if:
1. It has `nibrs_month.reported_status` set to `I` or `Z` for a given month
2. It is covered by another agency with `nibrs_month.reported_status` set to `I` or `Z`

Columns I want to add to `cde_agency_participation`:
1. `covered_by_id`
3. `covered_by_root_id`

Agencies should not be included in participation calculations for any year >= dormant_year.

**Comment by LarryBafundo** [comment]
just a note that this came up during testing today. one of the start UCR program staff we spoke with said their state has 100% and questioned our participation rates.

**Comment by harrisj** [comment]
I apologize for not detecting it earlier, but this is a point of these exercises I suppose.

**Comment by harrisj** [comment]
So, #458 has been merged and the flat covered_by table has been created so I am now rebuilding the participation tables

**Comment by LarryBafundo** [comment]
how's this coming @harrisj?

**Comment by harrisj** [comment]
I have been receiving some invaluable assistance from @cacraig on why this job kept stallng, and we might have it figured out now, but will look into it later.

**Comment by harrisj** [comment]
This will be resolved as part of #472

**Comment by harrisj** [comment]
Closing since this was merged
