### ISSUE TITLE
Load Estimated data into tables

### ISSUE THREAD

**Issue by harrisj** [18F/crime-data-api#464]
It doesn't look like we ever made an issue for this, but we'll need to load the estimated data into the database. This process will likely involve a few steps:

1. SQL to create the estimated data table (name?)
1. Saving XLS as machine-readable CSV files
2. Loader script to load a file into the tables
3. Script that runs the loader for all files

Separately, we will need an issue for the API endpoint that provides the estimated data

**Comment by LarryBafundo** [comment]
@harrisj is the plan to continue to use the unestimated arson counts alongside the estimated ones?

**Comment by harrisj** [comment]
I thought the FBI told us not to do that and that we would likely be removing arson as a sidebar

**Comment by LarryBafundo** [comment]
@harrisj copied you on an email asking for a decision on this. if the rationale is to not include arson because we want to match the CIUS reports, i'm not sure that's a good reason because we're going to have differences no matter what.

**Comment by LarryBafundo** [comment]
@harrisj moving this into in progress
