### ISSUE TITLE
Design solution for header content alignment for wide browsers

### ISSUE THREAD

**Issue by AvivaOskow** [18F/crime-data-api#465]
The "logo" doesn't align with the left content for the side nav in the explorer on wide browsers, ends up looking broken:

<img width="830" alt="screen shot 2017-04-11 at 1 38 35 pm" src="https://cloud.githubusercontent.com/assets/21244661/24930034/1e5ae956-1ed6-11e7-889f-2ebe0fe7700b.png">

"Logo" could always align with content of left nav (see "Location"), but need to design a solution for when the left nav isn't there, and where should the menu align to?

**Comment by AvivaOskow** [comment]
@brendansudol and I decided the logo should align with the left content of the side nav, and should use that same margin for the homepage and on the right for the menu.

**Comment by jeremiak** [comment]
@AvivaOskow This is deployed to crime-data-explorer.fr.cloud.gov and is ready for review. Not sure which PR it made it in ATM

**Comment by LarryBafundo** [comment]
this is ready for your review @AvivaOskow
