### ISSUE TITLE
Load ICPSR crosswalks into DB to promote agency search by zipcode 

### ISSUE THREAD

**Issue by harrisj** [18F/crime-data-api#468]
Note that since the terms of use for these datasets include the following terms:

> You agree not to redistribute data or other materials without the written agreement of ICPSR, unless:
>
> You serve as the OFFICIAL or DESIGNATED REPRESENTATIVE at an ICPSR MEMBER INSTITUTION and are assisting AUTHORIZED USERS with obtaining data, or
>
> You are collaborating with other AUTHORIZED USERS to analyze the data for research or instructional purposes.
>
> When sharing data or other materials in these approved ways, you must include all accompanying files with the data, including terms of use. More information on permission to redistribute data can be found on the ICPSR Web site.

we should only check in the loading scripts to the repo and not any data files. A lot of these caveats are for files that identify individuals (not these crosswalks), but the terms still apply.

**Comment by harrisj** [comment]
Just out of curiosity, I looked what was in the files for population and such too

|Label|2012|2005|2000|1996|
|-|-|-|-|-|
|State Code (alnum)||STATE|STATE|
|FIPS state code|FSTATE|FSTATE|FSTATE|FSTATE|
|FIPS county code|FCOUNTY|FCOUNTY|FCOUNTY|FCOUNTY|
|FIPS place code|FPLACE|FPLACE|FPLACE|FPLACE|
|FIPS state code (alphanum)|FIPS_ST|||
|FIPS county code (alphanum)|FIPS_COUNTY|||
|FIPS state-county code (alnum)|FIPS|||
|FIPS MSA Code||FMSA|FMSA|FMSA|
|FIPS MSA Name||FMSANAME|FMSANAME|FMSANAME|
|9-character ORI|ORI9|ORI9|||
|7-char ORI|ORI7|ORI7|ORI7|UORI|
|Agency Name|NAME|AGENCY|AGENCY|UAGENCY|
|State name|STATENAME|USTATENM|USTATENM|
|County name|COUNTYNAME|COUNTY|COUNTY|UCNTYNAME|
|Urban area name|UANAME|PLACENM|PLACENM|
|Agency is Part Of Another|PARTOF|||
|UCR covered by ORI||UCOVBY|UCOVY|UCORI|
|Agency Type|AGCYTYPE|AGENTYPE|AGENTYPE|
|Census Govt ID|GOVID|GOVIDNU|GOVIDNU|
|Census Govt Name|LG_NAME|GOVNAME|GOVNAME|
|Address Name|ADDRESS_NAME|||
|Address Street 1|ADDRESS_STR1|ADD1|ADD1|UADD1|
|Address Street 2|ADDRESS_STR2|ADD2,ADD3,ADD4,ADD5|ADD2,ADD3,ADD4,ADD5|UADD2,UADD3,UADD4|
|Address City|ADDRESS_CITY|||
|Address State|ADDRESS_STATE|||
|Address Zip|ADDRESS_ZIP|ZIPCODE,ZIPRANGE|ZIPCODE,ZIPRANGE|UADD5|
|ORI reported 1985-2012|REPORT_FLAG|||
|UCR numeric state code|U_STATENO|USTATENO|USTATENO|
|UCR county|U_CNTY|UCNTY1,UCNTY2,UCNTY3|UCNTY1,UCNTY2,UCNTY3|
|UCR population group|U_POPGRP|UPOPGRP|UPOPGRP|UPOPGRP|
|UCR total population|U_TPOP (2012)|UPOPTOT|UPOPTOT|UPOPTOT|
|Census population|LG_POPULATION (2010)|ULSTPOP1,ULSTPOP2,ULSTPOP3|ULSTPOP1,ULSTPOP2,ULSTPOP3|CPOP94|
|Comments|COMMENT|||
|Latitude|INTPTLAT|LAT|LAT|
|Longitude|INTPTLONG|LONG|LONG|
|Federal Judicial District Name|DISTNAME|UJDIST|UJDIST|

**Comment by harrisj** [comment]
Mainly, I was wondering if we could use the crosswalks for measuring actual population for agencies (although it wouldn't be updated as frequently). It looks like the populations for the crosswalks come from the following sources

|Crossswalk|Source|
|-|-|
|2012|2010 decennial census|
|2005|2000 decennial census, 2000 Census of State and Local Law Enforcement Agencies|
|2000|Census of State and Local Law Enforcement Agencies 2000|
|1997|Bureau of the Census 1994 population estimate|

I'm not sure this would work as a source of outside population data. The CSLLEA doesn't seem much better sadly.

**Comment by harrisj** [comment]
So for now, I think I'll just work on loading the 2012 one and seeing how it matches against all agencies

**Comment by harrisj** [comment]
Should I move this back into `in progress` and work on this next?

**Comment by LarryBafundo** [comment]
yes, @harrisj

**Comment by harrisj** [comment]
I  will hold off on this for now and work on agency summary counts with @cacraig and reworking the participation tables for agencies

**Comment by LarryBafundo** [comment]
this may be deprioritized altogether, as the current design doesn't allow for users to search for agencies by zipcode. however, we may find in future research sessions that this is necessary.

**Comment by harrisj** [comment]
Good point! I think in the future we might potentially want to have the mapping of agencies to specific FIPS places to allow people to better link to Census demographics, but it's not an immediate concern

**Comment by LarryBafundo** [comment]
this isn't something we'll likely tackle by launch, but deserves to be in the backlog for future consideration
