### ISSUE TITLE
Split reta_agency_offense_summary rape into legacy and revised?

### ISSUE THREAD

**Issue by harrisj** [18F/crime-data-api#473]
Right now the estimated data endpoint returns two distinct counts for rape (legacy definition and the revised definition since 2013). I don't think these are additive (ie, I don't think total rape for 2015 is the sum of those both). For the sake of consistency, we might want to provide a similar breakdown for the agency data. There are equivalent suboffenses for the SUM_RPE offense for legacy and revised definitions so we can compute this. But I guess at the Agency level, an agency would either report one or the other and switch during the year. Do we want to show this as two distinct counts for a single agency? Do we log a year where an agency made the switch?

**Comment by LarryBafundo** [comment]
@harrisj i think we have to break out the counts for the different definitions, otherwise we're not representing the data accurately. but defer to @amberwreed as to how this impacts the design.

**Comment by harrisj** [comment]
Well, it's a bit weird since let's say an Agency changes how it reports in June of 2014, we will have 6 months of counts for the old definition and 6 months for the new

**Comment by harrisj** [comment]
So, I checked the DB and it looks like agencies switch at the beginning of the year and don't thus report both legacy and revised in a single year. So, there is no need for this change and I have added a column to the cde_agencies table for the year switched in #457
