### ISSUE TITLE
Consistent representation of boolean fields

### ISSUE THREAD

**Issue by catherinedevlin** [18F/crime-data-api#48]
Many fields in UCR represent boolean data with a variety of one-character flags.  API should have a single consistent way to represent booleans.

(add examples)

**Comment by harrisj** [comment]
I would normally agree with this, but I fear it would cause problems for the front-end team at this point. So I think we should defer it for now, but I would offer a few suggestions:

1. We never make alterations to the original FBI tables. Instead, we should either do this as a custom deserialization step in the Marshmallow schema for a table or as part of denormalizing into our own tables.
2. We actually only do this for fields with `Y/N` values. For everything else we try to expand into longer strings via a similar process

That said, this seems more like a nice to have for a future release than something necessary for the MVP. This also seems like something that should be done after we version the API

**Comment by harrisj** [comment]
This would be deferred for a future release
