### ISSUE TITLE
What do "agency_status" and "agency_type_id" mean?

### ISSUE THREAD

**Issue by jeremiak** [18F/crime-data-api#493]
It would be nice to have a human readable description of some of these values, in particular the `agency_status` and the `agency_type_id` values.

From the following response it is hard for me to know where to look to determine the definitions of "A" and "1".

```
  "agency_status": "A",
  "agency_type_id": "1",
```

For what its worth, I like how this is handled for the population groups, with a `*_desc` key:

```
  "population_group_code": "7",
  "population_group_desc": "Cities under 2,500",
```

**Comment by harrisj** [comment]
What endpoint is this? I can add in `agency_type_desc`. I am thinking of removing `agency_status` since I haven't really gotten a good explanation of what it means.

**Comment by harrisj** [comment]
Here are the agency_type values by the way

|Code|Name|
|-|-|
|1|City|
|2|County|
|3|University or College|
|4|State Police|
|5|Other|
|6|Other State Agency|
|7|Tribal|
|8|Federal|
|99|Unknown|

**Comment by harrisj** [comment]
Also, the agency type should be in the response for the `/agencies/` and `/agencies/:ori` endpoint

**Comment by harrisj** [comment]
The `agency_status` has two possible values `A` for active and `L` for legacy (agencies included more for historical reasons)
