### ISSUE TITLE
What is the difference between the offenses and suboffenses endpoints?

### ISSUE THREAD

**Issue by jeremiak** [18F/crime-data-api#494]
What is the difference between these two endpoints in the data they return?

We were looking at this data to build the bar chart for the agency view with `reported` and `cleared` values. But these two endpoints return different keys. Both return `reported`, but the suboffenses endpoint returns `cleared` but not `covered`, while the offenses endpoint returns `covered` but not `cleared`.

**Comment by harrisj** [comment]
The difference is just the level of granularity. One aggregates counts on an annual basis at the suboffense level for a given agency and the other at the offense level (an offense might be one or more suboffenses). The table you were looking at was an experiment that has been removed. The actual structure of an offense call has records that look like this:

``` json
{
"id": 4598065,
"year": 2014,
"offense_name": "Murder and Nonnegligent Homicide",
"unfounded": 0,
"state_postal_abbr": "RI",
"ori": "RI0040200",
"reported": 2,
"agency_id": 17400,
"offense_id": 11,
"offense_code": "SUM_HOM",
"cleared": 0,
"juvenile_cleared": 0,
"pub_agency_name": "Cranston",
"actual": 2
}
```
