### ISSUE TITLE
Style API documentation to match general CDE aesthetic

### ISSUE THREAD

**Issue by jeremiak** [18F/crime-data-api#496]
Before we publicize the API, let's make it look a bit more like part of the broad product. I propose the following elements for the first pass, recognizing we can always improve after we publicize it:

- [ ] Matching fonts and sizing between API docs and CDE front end
- [ ] Matching colors used
- [ ] Applying the same border radii
- [ ] Using the same width container
- [ ] Adding the basics of the header and the footer

[Jacob here] I would like to add a few other things:
- [ ] Come up with a sensible set of top-level tags and put API methods in one and only one tag each.
- [ ] Define ordering of the API tags and if we want to show all methods fully expanded on load.
- [ ] See if we can figure out some design/messaging to make the "Authenticate" and "Try It Out" a little more obvious/intuitive for new users.

**Comment by LarryBafundo** [comment]
@jeremiak moving this up in the queue for this sprint based on our conversation about getting broader feedback on the API as early as next week.

**Comment by harrisj** [comment]
I think all of these should be doable. And I wonder if we should perhaps move the API documentation to within the frontend, since it just is JS that pulls JSON in from elsewhere (we might need to do some CORS fiddling) and it could reuse CSS elements defined in the CDE. That said, my biggest concerns about Swagger right now is its UX, which is more clever than good

**Comment by harrisj** [comment]
Here is a link to [documentation on customizing the Swagger UI](http://swagger.io/docs/swagger-tools/#customization-36)

**Comment by LarryBafundo** [comment]
hey @jeremiak, @harrisj considering that this issue is in review I'm assuming it's complete, but did we ever get to the sub tasks Jacob added at the bottom of the main description? if not, we can split those out and and create a new task for them.

**Comment by jeremiak** [comment]
Ya, the front end tasks are in review and being looked at, though not yet merged. I didn't address the first two points Jacob raised but I did take a first stab at adding some better auth UX including adding a default key so people can get going _right_ away.

+1 for pulling other the other tasks into separate issues.

**Comment by LarryBafundo** [comment]
done
