### ISSUE TITLE
Append " County" to agency names for county agencies?

### ISSUE THREAD

**Issue by harrisj** [18F/crime-data-api#497]
So, the FBI's agency names can sometimes be ambiguous when you have an agency for a city within a county that has the same name as its county (eg, both the LAPD and Los Angeles County Sheriff have the name "Los Angeles"). [This happens a fair amount](https://docs.google.com/spreadsheets/d/1v0wCD_UtmGK2T33meqz_MZZe12vwRoFbH8hCoYOUS0Y/edit#gid=0)

Even for non-ambiguous names (eg, Montgomery County in Maryland), it might be useful to have the name include the County on the end.

I am already building a table `cde_agencies` which is a denormalized view of agencies. I would like to add some logic so that if an agency is of the `County` agency_type that it appends `" County"` to the agency name in that table. Any objections?

**Comment by LarryBafundo** [comment]
I think this makes sense, but how does this affect how they present in a list as a selectable agency versus as the header for the page?

**Comment by harrisj** [comment]
Well, if we join against `cde_agencies` instead of `ref_agency` then it'll show up everywhere. The `/agencies/` endpoints are supposed to pull in from the `cde_agencies` table

**Comment by harrisj** [comment]
This was merged as part of #457
