### ISSUE TITLE
Sometimes the state value is supplied in the URL and other times as a query parameter

### ISSUE THREAD

**Issue by jeremiak** [18F/crime-data-api#499]
In the `/counts` endpoint the state is a query parameter but in other endpoints the state is part of the URL path.

For example, to get arson in Nevada the endpoint is `/counts?explorer_offense=arson&state=NV`. However, to get the estimated reported crime counts for Nevada we use `/estimates/states/NV`.

For what it is worth, I prefer passing in the state abbreviation as a URL path parameter preceded by `/states/:abbr`.

**Comment by LarryBafundo** [comment]
@jeremiak reminder to look into this and see if still necessary

**Comment by jeremiak** [comment]
@LarryBafundo and @harrisj  This is good to close now that we aren't using the `/counts` endpoint.
