### ISSUE TITLE
Identify five visualizations that are feasible within the CIUS reports

### ISSUE THREAD

**Issue by jeremiak** [18F/crime-data-api#5]
The CIUS report has data tables that represent the following types of information, published on a yearly basis. Many of these metrics also include a corresponding trend rate for the last few years.
1. Broad crime trends
2. Arson
   1. By population group (size of city/MSA)
   2. By property type
3. Murder
   1. Number of people involved
   2. Age, sex, ethnicity of offenders and victims
   3. Relationship between offenders and victims
   4. The circumstances under which the murder occurred (expanded homicide data table 11)
   5. The weapon used in the murder
4. Justified murders
   1. Killing of a felon by a law enforcement officer in the line of duty (expanded homicide data table 14)
   2. Killing of a felon by a private citizen (15)
5. Robbery
   1. Locations
   2. Weapons used
   3. Value of property stolen and retrieved
6. Arrests by state (Table 69)
   1. No traffic arrest data
   2. How many people are arrested in each state for what times of crimes?
   3. Rape count/methodology is a huge caveat in this table
   4. How many are under 18?
   5. How many law enforcement agencies were involved?
7. Crime at universities (Table 9)
8. Offenses known to law enforcement
   1. Type of offense
   2. Crime against persons/property
   3. By metro/non metro force
   4. By university, state, tribal
9. Law enforcement
   1. Full time employee counts by demographics
   2. Divided by
      1. Geographic region
      2. States
      3. Cities
      4. Per 1,000 inhabitants
      5. By metro & non metro counties
      6. Tribal, Federal or other

**Comment by jeremiak** [comment]
Here are some preliminary ideas about what we can show from the data:
0. [What does the broad crime trend for the US look like?](https://github.com/jeremiak/fbi-crime-data-explore/blob/master/crime_in_the_us.ipynb)
0. [Who gets murdered in the US?](https://github.com/jeremiak/fbi-crime-data-explore/blob/master/who_gets_killed.ipynb)
0. [What weapons are used in murders?](https://github.com/jeremiak/fbi-crime-data-explore/blob/master/murder_weapons.ipynb)

**Comment by LarryBafundo** [comment]
@jeremiak okay to close this?
