### ISSUE TITLE
Reported and months_reported are returning as NULL in cde_agencies tables

### ISSUE THREAD

**Issue by harrisj** [18F/crime-data-api#501]
This is my bug to fix. I think the issue is that `current_year` is being used to pull in participation, but the current year for agencies table is 2016 and the most recent data we have is from 2014. I should fix the current_year to ensure it uses reta_month and not what it is using.

cc @jeremiak

**Comment by harrisj** [comment]
There is a PR for this, but this should be fixed on production now. Can you confirm @jeremiak?

**Comment by jeremiak** [comment]
Looks good to me! I see that for ORI `NY0303000` we now have:

```
  "months_reported": 12,
  "nibrs_months_reported": 0,
```
