### ISSUE TITLE
What does the "aggregate_many" parameter mean?

### ISSUE THREAD

**Issue by jeremiak** [18F/crime-data-api#505]
There is no description for the `aggregate_many` parameter in some of the API endpoints, though it is a somewhat vague variable name. Can we define it in the API documentation?

For reference, I am specifically referring to the `/offenders/count/national/{variable}` endpoint.

**Comment by harrisj** [comment]
I don't know really what it does but it had something to do with CSVs. I think Colin probably has the answers

**Comment by cacraig** [comment]
I'm not sure if it still works anymore - but it was intended to aggregate the CSV rows. 

aggregate_many=false

Agency, Incident
(agency_1, incident_1)
(agency_1, incident_2)
(agency_1, incident_3)

aggregate_many=true

Agency, Count
(agency_1, 3)

**Comment by harrisj** [comment]
Any objection to me removing it then from documentation?

**Comment by cacraig** [comment]
No objections here @harrisj ! Although it may come up in the debates on where to go with the Incident endpoint. (aggregating vs. flattening)
