### ISSUE TITLE
Deprecate/restructure the reta_month_offense_subcat_summary table?

### ISSUE THREAD

**Issue by harrisj** [18F/crime-data-api#506]
In the earlier days of the API, Catherine Devlin built a table `reta_month_offense_subcat_summary` for rolling up the `reta_month` offenses from monthly offense counts into annual counts, with support for multiple levels of grouping. This allows users to potentially see counts for any combination of one or more fields: year, month, state, offense classification, offense, suboffense which makes for some powerful query options but also makes the table hard to generate and many rows.

We were using this table to feed data to the national and state trend charts for offenses, but those are now handled by the `/estimates` endpoints. Since arson is not included in the estimated data, that is the only part of the CDE that still uses this data publicly and of course it still is in the API for those users. But this seems to be a good time to ask some questions about future directions for this table, especially since we have a similar table for grouping crime into annual counts for a given agency. It seems like we have several options:

1. Keep the table. It needs some tweaks to the data it includes, so that it doesn't include some records it shouldn't, but it should hopefully be faster to generate than in the past because we have a bigger DB instance.
2. Merge/replace the functionality of this table with `reta_agency_subcat_summary` which is basically doing a similar thing at the agency level, but is also missing all of the wild grouping options.
3. Create a specialized arson table for the arson pages (bring back the `/arson` API) and drop the table entirely. This would mean we wouldn't support `/counts/` which is not our preference, but if we were asked to remove it.

The main question that might determine our course of action is if we want to support the various levels of grouping on the `/counts` endpoint that are currently possible. For instance, the same table can be queried to see the "number of homicides in Alaska in January 2013" and "all larceny in the database" or all sorts of other combinations ("annual counts of Property Crimes") or such. I think this is pretty powerful in some sense, but that power does come at a cost and if we don't need it, it might be better without it. We could remove some of the grouping options too...

And if we do decide to keep using this table, I would like to make the grouping options a bit more explicit by expanding out the `/counts/` endpoint with other path components to make it easer to group by and such. But let's decide if we need the functionality first.

cc @jeremiak @LarryBafundo @cacraig

**Comment by LarryBafundo** [comment]
is there a short-term and long-term view we could take here? for example, could we decide on a course of action through launch (mid june) and one that we might take post launch, depending on priorities?

**Comment by harrisj** [comment]
Not sure, I do have to regenerate the table to fix some things and I was wondering if it is worth it or not.

**Comment by harrisj** [comment]
Let's defer this for now
