### ISSUE TITLE
Can we add swagger validation to the CI process?

### ISSUE THREAD

**Issue by jeremiak** [18F/crime-data-api#509]
The current `swagger.json` doesn't validate. Using the online validator tool (https://online.swagger.io/validator/debug?url=https://crime-data-api-demo.fr.cloud.gov/static/swagger.json) I get the following error:

```
{
  "messages": [
    "attribute definitions.ParticipationRate.prvoperties is unexpected",
    "attribute .[by].default is not of type `string`"
  ],
  "schemaValidationMessages": [
    {
      "level": "error",
      "domain": "validation",
      "keyword": "additionalProperties",
      "message": "object instance has properties which are not allowed by the schema: [\"prvoperties\"]",
      "schema": {
        "loadingURI": "http://swagger.io/v2/schema.json#",
        "pointer": "/definitions/schema"
      },
      "instance": {
        "pointer": "/definitions/ParticipationRate"
      }
    }
  ]
}
```

Perhaps we can add swagger validation to the CI pipeline so that builds break when the JSON file has errors?

**Comment by jeremiak** [comment]
Just came across this swagger badge/validator concept which could be useful: https://github.com/swagger-api/validator-badge

**Comment by harrisj** [comment]
So there is validation on some API endpoints, and that would trigger some errors if the Swagger is malformed in some ways. But there are obviously cases where it doesn't quite work (and the issue here is that you could define Swagger schema objects that have no properties and match and that particular validator is being more strict than the one I am using I guess. 

Still, we don't have something that just validates the Swagger itself before running other tests

**Comment by jeremiak** [comment]
I think the problem here is that a key is misspelled as `prvoperties`. From the docs it looks like (not a proposal, just some quick research) we can `CURL` the document against a swagger validator. So using the `test: pre:` option in `circle.yml` we might be able to do something like `curl -X POST -d @crime_data/static/swagger.json -H 'Content-Type:application/json' -i http://online.swagger.io/validator/debug` and check for an error object but that might be a weird/brittle idea

**Comment by harrisj** [comment]
Well, we could put the badge on it regardless (might be good to add), but I will look into why the validator within my Swagger tester didn't find that...

**Comment by harrisj** [comment]
This was merged into production
