### ISSUE TITLE
Enable CORS on swagger.json file and endpoints

### ISSUE THREAD

**Issue by jeremiak** [18F/crime-data-api#510]
Swagger-UI makes all HTTP calls client side but currently chokes because we haven't yet enabled CORS on the API endpoints. Swagger-UI also makes a client side call for the `swagger.json` file so that resource to allow CORS as well.

Related to #496

**Comment by harrisj** [comment]
I want to enable CORS for the swagger.json so you can put the UI in the frontend if you need to, but does the CORS matter if we are proxying the endpoint through api.usa.gov? I honestly don't know...

**Comment by jeremiak** [comment]
Good question, from looking through the docs I see nothing that contradicts the idea that api.data.gov is mostly a transparent proxy and so if we add CORS support to our API, api.data.gov will forward that along to the client.

@gbinal is the above correct?

**Comment by gbinal** [comment]
@gui just answered over in Slack.  Crossposting here for convenience.  

> api.data.gov will pass along any CORS headers your API returns itself (as we do with any HTTP headers). Setting the CORS headers in the API itself is probably preferable, but if you're in a situation where the that's more of a hassle, then api.data.gov can allso add CORS headers at our layer (we sometimes use this to CORS-ify an existing API we're not in control of).

> If you want to set those at the api.data.gov layer, that can be done in the admin under API Backends > Global Request Settings > Default Response Headers (or Override Response Headers). Or if you want to only set it on specific endpoints, the same settings are available under the Sub-URL Request Settings.

**Comment by harrisj** [comment]
Thank you very much good sir. @jeremiak, is there any reason we should not enable CORS on all routes in the Flask application?
