### ISSUE TITLE
Add county information to the cde_agencies table

### ISSUE THREAD

**Issue by harrisj** [18F/crime-data-api#512]
We want to add the primary county for a given agency to the cde_agencies table. This involves a few little considerations:

1. Agencies may be in multiple counties, but let's pick the one they are mainly in to display (will have to see if some agencies are evenly split, but I assume most are usually in one county mostly)
2. County names in `ref_county` are capitalized, and there are some cases where we can't just titleize from DEKALB to Dekalb (it's actually DeKalb)
3. We currently have a county view for data that involves a bunch of inefficient queries and I've been meaning to fix.
4. Related, there is no easy means for a FIPS -> County search, since the FBI database splits FIPS into state and county tables.

So, I'm going to propose handling this in several steps:
1. Create a `cde_counties` table that has printable names for the counties, full five-character FIPS codes and other useful fields from the `CdeRefCounty` model.
2. Make CdeRefCounty use this as its base table (should be an easy fix)
3. Associate in the primary county and primary county FIPS into the cde_agencies table

**Comment by harrisj** [comment]
So, if we would prefer to list all counties an agency is located in, we can do that. I can also give you a count of counties, so you could say in the text "is located in X" vs. "is primarily located in X"

**Comment by LarryBafundo** [comment]
@harrisj we have a call with the CJIS technical team to talk about this, so let's update this after that.

**Comment by harrisj** [comment]
CJIS approved displaying a primary county for an agency and this will be in production once #514 is merged.
