### ISSUE TITLE
Create cde_states table

### ISSUE THREAD

**Issue by harrisj** [18F/crime-data-api#515]
As part of the work on #512, I created a denormalized `cde_counties` table instead. This allowed me to clean up the hackish code for CdeRefCounty. It might make sense to make a similar denormalized table for the CdeRefState model that pulls into a single table the data queried by the CdeRefState model

**Comment by harrisj** [comment]
This would be a necessary step if wanted to use our own separate API database distinct from the larger FBI database. I think it would be a good optimization step too.

**Comment by LarryBafundo** [comment]
thanks @harrisj, could you describe some of the potential optimization benefits here?

**Comment by harrisj** [comment]
Well, right now this is the only API endpoint that does multiple distinct queries against the database to get things like police staff or such. Would be quicker/less complicated to just inline that all into a single table.
