### ISSUE TITLE
Agency offenses endpoint needs to support classification and arson

### ISSUE THREAD

**Issue by harrisj** [18F/crime-data-api#529]
Currently the agency offenses endpoint does not work when passed the explorer_offenses of `property`, `violent` or `arson.` This will require a few fixes:

- [x] Mix in classification rollups to the data (or sum up as another table?)
- [x] Mix in arson data for the agency

**Comment by LarryBafundo** [comment]
@harrisj can you please provide an update on this ?

**Comment by harrisj** [comment]
1. Classification grouping work is done, but I need to generate a new backing table on production (going to start the job soon)
2. Arson grouping work needs to be done next.

**Comment by harrisj** [comment]
This was merged. Closing
