### ISSUE TITLE
Suppress unspecified counties in agencies table?

### ISSUE THREAD

**Issue by harrisj** [18F/crime-data-api#530]
Right now, if you make a request for an agency that is not in a real county (ie, a tribe or a state agency or a federal agency or NYC or DC), the primary county might look like this:

``` json
"primary_county": "Not Specified",
"primary_county_fips": "110-1",
```
This is because even things are aren't in counties are mapped to fake counties in UCR. (That FIPS is really bad too) I wonder if it would make more sense to assign these values to NULL which would make it easier to see if there is no real county. Thoughts?

**Comment by LarryBafundo** [comment]
hey @harrisj i've seen some counties listed as "not specified" and others as "unmapped." is there a difference between the two and could we consolidate them into a single category? 

see the list of agencies by county for New Jersey, for example: https://crime-data-explorer.fr.cloud.gov/explorer/state/new-jersey/robbery?agencySearch=true

**Comment by harrisj** [comment]
I'm not sure what exactly the difference is between the two, but I would guess there is some arcane answer buried deep within the FBI processes (it's not worth teasing out). I could indeed consolidate into something generic for any county that doesn't have a real FIPS identifier, but the question I would like to get some feedback from @jeremiak and @brendansudol for is if they would prefer:

a) Show the primary county as "Unspecified" or something and set the FIPS to `null`
b) Show the primary county as `null` and set the FIPS to `null`

This change would require rebuilding the `cde_counties` table, but that is pretty quick.

**Comment by jeremiak** [comment]
@harrisj My weakly held preference would be for both values to be `null` but setting the FIPS code to `null` sounds good to me.

**Comment by LarryBafundo** [comment]
@harrisj, @amberwreed, @RyanSibley are we all on the same page as to how we should handle agencies with unspecified counties in the agency overview text?
