### ISSUE TITLE
Add endpoint for retrieving cargo theft incidents in a state

### ISSUE THREAD

**Issue by harrisj** [18F/crime-data-api#546]
We currently just provide Cargo Theft data only as a bulk download, but it could potentially become its own type of page. Right now we have endpoints in front of the `ct_counts` and `offense_ct_counts` tables (the NIBRS-like details of types of property stolen, etc.) But we could also potentially share trends of cargo theft data for a given state based on individual incidents. We'd start by adding an API endpoint in front of the `ct_incident` table

**Comment by LarryBafundo** [comment]
thanks for adding @harrisj

**Comment by LarryBafundo** [comment]
Closing as we are going to focus this board on tasks related to the discovery effort; enhancements and new feature work will be tracked on the Jira board managed by CJIS
