### ISSUE TITLE
Regenerate CSV for human trafficking

### ISSUE THREAD

**Issue by harrisj** [18F/crime-data-api#549]
With the recent merger of #533, the new human trafficking tables are now live. It looks like we might need to regenerate the CSV though. We have two choices for the table:

1. The /ht/agencies endpoint gives an agency-level count of human trafficking statistics for agencies that have reported.
2. The /ht/states endpoint gives a state-level rollup of the human trafficking data.

We could potentially provide 2 different files of this. What do you think, Colin?

**Comment by LarryBafundo** [comment]
hey @harrisj, let's go with the state-level roll-up, since that approach is similar to the other downloads we provide on the page. Also, we have an API endpoint for human trafficking, so we make more granular perspectives available in other ways.

**Comment by amberwreed** [comment]
@harrisj Is the latest files on the crime data explorer? I don't understand why some states have so many months that they have reported.

![Screen Shot 2017-06-16 at 5.08.28 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/56393caf761ba64300ac16ef/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b77256455f56b7191a37df112234f5d575ecc3c4a4356bcbbd671f3e57862804e0ee584385b20c16f17aabf8b1ee901ba23824b81e7ea8c4dd2f42f67b6d5db1063474f4dcbed5727a29f41c95cff4ce7485da514376be3762431.png)

https://crime-data-explorer.fr.cloud.gov/downloads-and-docs

**Comment by harrisj** [comment]
Sorry for the confusion. That means that in 2014, 741 agencies in Illinois reporting 8739 total months of human trafficking reports (which is approx 11.79 months per agency). There is probably a better way to provide this statistic.

**Comment by LarryBafundo** [comment]
@harrisj should this still be in progress?

**Comment by harrisj** [comment]
No, this is done, but did you need me to edit the column names because of the confusion that @amberwreed pointed out?

**Comment by LarryBafundo** [comment]
@harrisj can we just rename that column "avg. months reported" and show the average of months reported for the number of agencies participating by year, rather than the aggregate that we show currently?

**Comment by harrisj** [comment]
This is done
