### ISSUE TITLE
Spike: test if significant performance improvements from bypassing Marshmallow

### ISSUE THREAD

**Issue by harrisj** [18F/crime-data-api#554]
It's looking like Marshmallow is becoming a bit of performance drag on the application. This is because rendering output means deserializing objects into Marshmallow objects and then rendering out JSON or CSV. It also adds a layer of code complexity. Given that the DB instance is now more powerful than the API instances and that Postgres can produce JSON and CSV (see [this library for calling COPY](https://github.com/jmcarp/sqlalchemy-postgres-copy), maybe we should just do that in the database layer?

We've discussed the idea of doing an engineering spike to just see how the API might perform without marshmallow. The idea would be to take a single endpoint that might be a bit large or slow and write an alternative version of it that doesn't use Marshmallow to serialize. We would then benchmark both versions to see the difference.

**Comment by LarryBafundo** [comment]
@harrisj, @cacraig can we please provide an update to this issue as part of the broader discussion around CDE readiness?
