### ISSUE TITLE
Add some overrides for some agency names?

### ISSUE THREAD

**Issue by harrisj** [18F/crime-data-api#556]
Since we have created our own separate table `cde_agencies` for doing agency lookup, it allows us to potentially override the names of agencies in the CDE database if they don't match what a user might look for. A prime case of this is the NYPD (ORI=NY0303000) which simply has the agency name  of "New York," making it all but impossible to find in the current agency search interface for New York state.

I'd recommend that we make a few edits to names in the database (will update if I find more):

|ORI|Default Name|Edited Name|
|-|-|-|
|NY0303000|New York|New York City|
|MO0956800|St. Louis|Clayton|

Additionally, if the frontend team were interested in supporting it, it might be nice to be able to define aliases for an agency that could also be searched. So, we would rename the agency to New York City but also define "NYPD" as another name for the agency. Similarly, we might not rename the Los Angeles police department, but could define "LAPD" as an alias. These would be implemented as delimited entries in a separate field on the table if the front-end search interface would be able to extract them.

**Comment by LarryBafundo** [comment]
CJIS doesn't want us to rename agencies on an ad hoc basis, but is considering whether or not we can use the crosswalk file to be more descriptive. closing this issue out in the meanwhile.
