### ISSUE TITLE
Considerations for arrest data 

### ISSUE THREAD

**Issue by harrisj** [18F/crime-data-api#566]
There are [41 tables for arrest statistics in Crime in the United States](https://ucr.fbi.gov/crime-in-the-u.s/2015/crime-in-the-u.s.-2015/persons-arrested/persons-arrested). I don't think we necessarily need to emulate all of these, but I think it would be good to have a few available for download:

- [ ] [Estimated Number of Arrests by Year](https://ucr.fbi.gov/crime-in-the-u.s/2015/crime-in-the-u.s.-2015/tables/table-29) But this seems to involve an [estimation process that we might not have data for](https://ucr.fbi.gov/crime-in-the-u.s/2015/crime-in-the-u.s.-2015/tables/table-29/table_29_estimated_number_of_arrests_united_states_2015.xls/@@template-layout-view?override-view=data-declaration)
- [ ] [Number and Rate of Arrests by Population Group](https://ucr.fbi.gov/crime-in-the-u.s/2015/crime-in-the-u.s.-2015/tables/table-31)
- [ ] [Arrests by Sex](https://ucr.fbi.gov/crime-in-the-u.s/2015/crime-in-the-u.s.-2015/tables/table-42)
- [ ] [Arrests by Race and Ethnicity](https://ucr.fbi.gov/crime-in-the-u.s/2015/crime-in-the-u.s.-2015/tables/table-43)
- [ ] [Arrests by State](https://ucr.fbi.gov/crime-in-the-u.s/2015/crime-in-the-u.s.-2015/tables/table-69)

Need to figure out how best to do this. Should I make one big table with multiple groupings or something else.

**Comment by LarryBafundo** [comment]
just a quick update: i sent an email to CJIS on Friday, June 16 asking for guidance here. Will update this issue once we know more.

**Comment by LarryBafundo** [comment]
closing this issue as we're going to discuss this during the technical check in on Thursday
