### ISSUE TITLE
Proposal for how to handle specific annotations

### ISSUE THREAD

**Issue by harrisj** [18F/crime-data-api#567]
I was thinking about annotations for specific data issues in the RETA database and how we might support overlaying comments at various levels of specificity:

* Annotations related to an entire state for a given year
* Annotations related to a specific offense in a state for multiple_years
* Annotations for a single agency
And so on...

I was thinking that we could support this with a database table named `reta_annotation` that lets people set some fields limit the contexts to how the annotation is applied

* start_year
* end_year (for multi-year annotations, inclusive end)
* state_postal_abbr
* agency ori
* reta_offense_code
* annotation

So for the examples above, you'd set the following fields:

* state_abbr=RI, start_year=1999, end_year=1999
* state_abbr=IL, offense=SUM_RPE, start_year=1960, end_year=2012
* agency_ori=ILCPD0000

Now we would probably map to specific agency_id and the like, but using the ORIs and other external and stable identifiers means that changes to DB identifiers won't ruin the table.

Not sure how to display, but might think of it as like coming from the inside of an onion (most specific annotations first, then more general ones). But they could also be at different places on the page

**Comment by LarryBafundo** [comment]
let's use this space as a place holder for potential ways of addressing agency-specific caveats and footnotes for future iterations of the CDE. for the initial release we will follow an approach where we make state-based footnotes available and reference those files at the agency level.

**Comment by harrisj** [comment]
I tried some data entry to see how I would record these things and it's clear I would need to add a few columns:

start_year
end_year (for multi-year annotations, inclusive end)
data type (estimated, raw)
state_postal_abbr
agency type (city, county)
agency name (would map to agency ORI)
agency ori
reta_offense_code
annotation

**Comment by harrisj** [comment]
I think we can close this, right?

**Comment by LarryBafundo** [comment]
yes closing.
