### ISSUE TITLE
Consistent simplification of field names

### ISSUE THREAD

**Issue by catherinedevlin** [18F/crime-data-api#57]
Many field names in UCR are needlessly ugly; translating to more human-friendly names would be good for the API, especially for the most commonly-used fields.  For example, `REF_STATE.STATE_ABBR` could simply be STATE.

The simplified field names should be consistently used everywhere - in the output as well as for filtering.

**Comment by cacraig** [comment]
What about things ending with _name. Should we shorten them?

ie:
city_name -> city
state_name -> state
ucr_agency_name -> agency

etc.

**Comment by catherinedevlin** [comment]
Well... I'd see that the "bare" name (city, state, agency, tribe, etc.) should be assigned to whatever field we think will be most-useful and most-used.  So that would often be `something_name`, but sometimes that will be claimed by something else, like `state_abbrev`; because we'd rather support `?state=RI` than `?state=Rhode+Island`.  

Is that too squishy of a criterion?

**Comment by LarryBafundo** [comment]
@cacraig is this still relevant?
