### ISSUE TITLE
Rename the crime-data-upload-db service to "crime-data-production-db", or similar

### ISSUE THREAD

**Issue by harrisj** [18F/crime-data-api#604]
Like maybe crime-data-production-db or something?

cc @cacraig

**Comment by cacraig** [comment]
@harrisj @LarryBafundo  - Yeah, I can probably pick this up today.

**Comment by LarryBafundo** [comment]
moving to the backlog

**Comment by jeremiak** [comment]
FWIW, I think we should still do this as the service names (and for that matter the cloud.gov space name, which is currently `prototype`) should be changed to be as accurate as possible to ease the cognitive load on future developers/maintainers for this project

**Comment by LarryBafundo** [comment]
@jeremiak, @jpwentz do you guys want to make an executive decision on what to name the upload service?
