### ISSUE TITLE
Downloads for SHR and ASR Tables

### ISSUE THREAD

**Issue by harrisj** [18F/crime-data-api#616]
This issues is for tracking what downloads might be made available from the ASR and SHR tables we have derived from the FBI database. There are a variety of downloads and endpoints that could potentially be enabled down the road.

## National Arrest Totals
National arrest data is estimated by the FBI and provided to us as a CSV that is in the `dba/after_load/ext` directory and loaded into the `asr_national` table with the `load_estimated.sh` script. This data dates back to 1995 and could be provided as a download. I have also added an `/arrests/national` endpoint if they wanted to use that.

## ASR Rollups and Crosstabs
The `asr_` tables in the FBI database contain monthly counts of arrests for various offenses broken down by age/sex and or race. Not all agencies report race and ethnicity for arrests but they must report age and sex. I have created a few rollup and crosstab tables that use the provided ASR tables to create annual rollups of arrests by various counts and crosstabs that transpose the summary tables into counts instead. All of these are created in the `dba/after_load/asr_summaries.sql` file and should exist on production already. Note that only agencies that have reported arrests for 12 months are counted for the annual counts. Also, please note that arrest offenses are distinct codes from return A offenses.

The `asr_age_suboffense_summary` and `asr_race_suboffense_summary` are the most granular rollups of months ASR data into annual counts back to 1980 (I picked an arbitrary cutoff). These could be used for generating annual counts of arrests at the state and national level but they aren’t particularly denormalized. These tables could also be modified to collect arrest data at the agency level.

For APIs, the `asr_offense_summary`  joins information about race and age  breakdowns into a single table for national counts with various groupings  to the year. Similarly, the `asr_state_offense_summary` provides a similar breakdown for states in a separate table.

From these tables, I have generated crosstab views where each row is a combination of /year, state_id, offense_code/ (state_id is NULL for national counts) and the columns are totals for various groupings: 
* total male/female
* totals for a specific age_range (like “Female 17”, “Male 34-39”)
* totals for a racial category (currently just white, black, asian_pacific_islander, american_indian)
* counts of agencies and their populations that reported 12 months

There are two crosstab tables `asr_adult_crosstab` and `asr_juvenile_crosstab`. These could be used for several types of reports:
* Annual nationwide breakdowns of juvenile and adult crosstabs for various offenses
* State-specific crosstabs for all offenses for the past 20 years
* Cross-state comparisons for single offenses (like homicide)

A few additional caveats:
* Even though the `asian_pacific_islander` race was split into `asian` and `pacific_islander` in 2013, both values have been accidentally carried forward into the `asian` category.
* Most numbers can’t be compared directly to Crime in the United States, since many states amend their reports after publication. I’ve been told that California doesn’t however and can be used as a good state for comparisons.

## Drug Offense Rollup
One special type of rollup exists for drug offenses. The `ASR_DRG` offense is broken down into two broad subcategories for possession and manufacturing, each of which in turn are divided into classes of drugs: opioids, marijuana, synthetics and others (*it would be good to get clarification of synthetic opioids like fentanyl would be*). The `asr_drug_crosstab` table provides a breakdown of drug offenses by state and nationally. This could be used to generate 1 or more files about drugs.

## SHR Rollups
Supplemental homicide reports provide additional information about homicides. Not all states participate fully; in 2014, Alabama filed only one SHR report for the entire year. But it lets us make some more crosstabs based on homicide data. There is no requirement that SHR reporting agencies need to report for 12 months to be counted. But there are cases where homicides should not be counted:
* If the `shr_incident.homicide_code` is anything but “A”
* If the `shr_circumstances.circumstance_code` is in `[’50’, ’51’, 52’, ’53’, ’59’, ’80’, ’81’] (various negligent manslaughter and justifiable homicide codes)

SHR offenses are linked to `nibrs_weapon_type` codes and `shr_circumstances` table. This lets us generate two other crosstabs for national and state-specific counts:
* `shr_weapon_crosstab` what was the cause of death for various homicides (with several subcategories for the type of gun)
* `shr_circumstance_crosstab`what was the circumstances of the homicide.

These tables don’t quite match some of the tables for California in Crime in the United States (ie, table 20), so I’m not sure if they are ready for use yet.

**Comment by LarryBafundo** [comment]
@cacraig let's sync up on this tomorrow. looks like we can include arrest data in the current sprint, but that we still have questions about the SHR, so that will likely need to wait until the next sprint.

**Comment by RyanSibley** [comment]
@harrisj's write up is wonderful. Thanks!

**Comment by LarryBafundo** [comment]
i'm going to move this into review since the arrest data is now available via the CDE; however, since the write-up is so great, i'm going to create a separate task for finishing off the SHR report and reference this.

**Comment by LarryBafundo** [comment]
we need to hold off on creating the SHR report until we're in a better  place with the 2015 update.
