### ISSUE TITLE
Offender and victim denormalizations go too far

### ISSUE THREAD

**Issue by harrisj** [18F/crime-data-api#639]
So, @jpwentz and I have been looking into issues where there are miscounts for total victims and offenders for a given state and we found two issues that seem to be causing problems in the rollups and undercounting things. The first one is here.

As a precursor to generating the rollup tables like offense_offender_counts or the like, our `after_load` scripts populate tables like `nibrs_offender_denorm` that denormalize the NIBRS offender and offense tables. We create these tables to counter how much NIBRS incidents are represented in normalized form across multiple tables.

A single NIBRS incident:
* Belongs to a single month/year of reporting for a single agency
* Can have 0..many offenses (each with a location type)
* Can have 0..many offenders (with codes for age, race type, ethnicity that must be dereferenced)
* Can have 0..many victims (same scenenrio as offenders)
* Can have 0..many properties associated with it (mapped to prop_type codes)

So, to look at an offender without denormialization would mean joining across 20+ tables which is pretty slow for an API. _Denormialization_ is the process of bringing in remote values like "race_code B=Black" into a column of the new table. It is much more redundant, but it's also much faster and works well. The problem is that we took it too far.

The schema for the  `nibrs_offender_denorm` table is like this

``` sql
create table nibrs_offender_denorm (
    offender_id bigint, -- nibrs_offender.offender_id
    incident_id bigint, -- nibrs_offender.incident_id
    agency_id bigint, -- ref_agency.agency_id
    state_id int, -- nibrs_incident.state_id
    county_id int,
    incident_date timestamp, -- nibrs_incident.date
    race_id int,
    year varchar(4),
    age_id int, -- nibrs_offener.age_id
    age_num int,
    sex_code varchar(1),
    race_code varchar(2), -- ref_race.race_code
    offense_type_id bigint,
    offense_name varchar(100),
    location_id int, -- nibrs_location.id
    location_code varchar(2),
    location_name varchar(100), -- nibrs_location_type.location_name
    property_id bigint,
    prop_desc_name varchar(100),
    property_desc_id int,
    property_loss_id int,
    age_code varchar(10), -- ref_age.age_code
    state_code varchar(2), -- ref_state.state_code
    PRIMARY KEY(offender_id)
);
```

Many of these fields are fine to denormialize, but there is an issue where a given incident might involve 1 or more offenders  and multiple offenses (ie, robbery and homicide). We only include the single offender record and pick only one of the offenses for that offender (similarly, only a single location or property). The problem is that `nibrs_offender_denorm` table is then used to build the `offense_offender_table` which does rollups of offenders who have committed homicide or robbery. This table loses all the cases where there is more than one offense associated with a nibrs_incident, meaning we have undercounts compared to data computed from the raw table.

There are two options for this:
1. Duplicate rows when there are multiple denorm values to map to the offender. So if the offender commits 3 offenses, they show up 3 times with 3 different offense_id values. The problem is they might also show up multiplied because they stole various types of property and we are using the offender_id as a primary key.
2. Remove the offense and location and property codes potentially and join to other tables for that. The issue is that we provide this table as a download and for a large number of NIBRS incidents, there is only a single offense. Should we provide it in those cases and make it NULL for multiple offenses? Should we have some mechanism for picking the "top offense" if multiple offenses? Should we have several offense columns?

In any event, we might want to consider making a basic denorm table that is used for building the other tables as well as the downloads...

**Comment by LarryBafundo** [comment]
thanks for the write-up @harrisj; let's talk through it during our meeting later today. we'll want to flesh out a recommendation and then run it by Cindy. 

but in reading your summary, i was curious about this: 

"We only include the single offender record and pick only one of the offenses for that offender (similarly, only a single location or property)." 

Are you saying that in cases where there are multiple offenses associated with an incident we just pick one? If so, how do we do that?

**Comment by harrisj** [comment]
So I have deferred on the `_denorm` tables for now, but we can regenerate those later to have multiple offenses in them. I didn't want to block later step by worrying about that format. Right now I have a table for offender_offenses_states I am building on master for @jpwentz to review with the following changes from the previous version:

1. We join against the `nibrs_offense` table to record every offender-offense pair combination in the table for grouping.
2. Columns with NULL values for all of the variables are removed from the counts. Right now for offenders and victims there are cases where race/ethnicity/age/sex are all NULL (when there is nothing known) as well as cases where age_num is NULL (ie, when the age is unknown). These cluttered up the table with all sorts of confusing counts.
3. I have then added the total counts of offenders for an offense by setting NULL for all columns.

It makes more sense to provide an example I suppose.

To get all the offenders for homicide in a state broken down by race, we can run

``` SQL
select * from offense_offender_counts_states_temp 
where year=2014 and state_abbr='RI' and race_code IS NOT NULL AND ethnicity IS NULL 
AND sex_code IS NULL AND age_num IS NULL and offense_code = '09A';
```

|   id |   year |   count |   ethnicity |   age_num | race_code   |   sex_code | offense_code   | offense_name                         |   state_id | state_abbr   |
|------|--------|---------|-------------|-----------|-------------|------------|----------------|--------------------------------------|------------|--------------|
|    1 |  2014 |       1 |      <null> |    <null> | A           |     <null> | 09A            | Murder and Nonnegligent Manslaughter |         44 | RI           |
|    3 |  2014 |      16 |      <null> |    <null> | B           |     <null> | 09A            | Murder and Nonnegligent Manslaughter |         44 | RI           |
|    5 |  2014 |       1 |      <null> |    <null> | U           |     <null> | 09A            | Murder and Nonnegligent Manslaughter |         44 | RI           |
|    7 |  2014 |      11 |      <null> |    <null> | W           |     <null> | 09A            | Murder and Nonnegligent Manslaughter |         44 | RI           |

To get the total, we can set all columns to NULL

``` SQL
select * from offense_offender_counts_states_temp 
where year=2014 and state_abbr='RI' and race_code IS NULL AND ethnicity IS NULL 
AND sex_code IS NULL AND age_num IS NULL and offense_code = '09A';
```
|    id |   year |   count |   ethnicity |   age_num |   race_code |   sex_code | offense_code   | offense_name                         |   state_id | state_abbr   |
|-------|--------|---------|-------------|-----------|-------------|------------|----------------|--------------------------------------|------------|--------------|
| 4,055 |  2,014 |      35 |      <null> |    <null> |      <null> |     <null> | 09A            | Murder and Nonnegligent Manslaughter |         44 | RI           |

Note that the totals above for race only equaled 29. that's because there were 6 offenders with no demographic information provided. We could potentially provide the total offenders in the API responses somehow, but it's here for future use.

**Comment by harrisj** [comment]
So here is the plan I'm proposing for this project:

1. Redefine the offense-specific offender, victim and offense views to use this corrected approach that doesn't denormalize offenses too much. While I am at it, I am going to add fields to these tables to include the offense_codes as well as names to make it easier to query by offense.
2. Alter the API endpoints that call these tables to also run a query to get the total number of victims/offenders for that offense and other conditions (see the approach above) and see if I can return as part of the API response.
3. Switch the offender_denrom and victim_denorm tables to not denormalize too much, but we need to determine beforehand which approach we want to use for multiple offenses:
  a. ;-delimited in a single column
  b. multiple columns for offenses (can be up to 10 per NIBRS incident)
  c. multiple rows for offenses (means repeating victim/offender data)

**Comment by LarryBafundo** [comment]
@harrisj when you have a chance, can you provide an update on this?

**Comment by harrisj** [comment]
Replacing this with #655

**Comment by harrisj** [comment]
Going to close this now that I have migrated things over to #655
