### ISSUE TITLE
offense_offender_count (and similar) rollups can't include NULL values

### ISSUE THREAD

**Issue by harrisj** [18F/crime-data-api#640]
When looking into #639, I found another issue that can affect how data is displayed on the NIBRS rollup tables. Right now we build rollup tables where a column is NULL except if it's relevant to the counts. So to get all counts for `sex_code` you'd include `sex_code IS NOT NULL` in your query to find the values.

The problem is that there are some cases where there is no information recorded about offenders and victims, so the totals for the rollups is often less than the total number of offenders. I'm not sure if we have actually put this in an issue, but I think it has come up in the past, but I can't seem to find it now. If not, I have several solutions to discuss.

cc @cacraig @jeremiak @LarryBafundo

**Comment by LarryBafundo** [comment]
@harrisj we've discussed this issue before, but i don't think we have the issue anymore. when you have a chance, can you outline your ideas here  and we can talk with Cindy about the path forward?

**Comment by harrisj** [comment]
This can be fixed as part of #646

**Comment by harrisj** [comment]
Closing since CJIS is taking over the generation of these views
