### ISSUE TITLE
Victim denormalizations should not include offender relationship

### ISSUE THREAD

**Issue by harrisj** [18F/crime-data-api#652]
Issue #639 already goes into some of the general problems with victim and offender denormalization related to an erroneous reduction of multiple offenses into a single offense (and how those offenders and victims would not be included in the counts for other offenses. There is a similar issue for offender-victim relationships currently captured in the `nibrs_denorm_victims` table that means such information should not be included in that table.

The `nibrs_victim_offender_rel` table allows NIBRS to capture the relationship between any offender and victim. So, for an incident with 2 offenses, 3 offenders and 4 victims:

a. The total number of offense-victim pairings would be 2 * 4 = 8 (to be in offense_offender_counts)
b. The total number of offense-offender pairings would be 2 * 3 = 6 (to be in offense_victim_counts)
c. The total number of offender-victim relationships would be 3 * 4 = 12 (to be in a new table?)

Based on this, it seems like we want to create a special table for representing offender-victim relationships in the database and returning that information to the API.

**Comment by harrisj** [comment]
Okay, this is frustrating, but I just wanted to double-check myself and looked at 2014 NIBRS reports for West Virginia

| Table | Rows |
|--|---|
| Offenders | 70,547 |
| Offenses | 69,139 |
| Victim-Offender Relationships | 19,391 |

It looks like for this state and year there are only 0.0003976% of all possible relationships specified (I get that most relationships might not be apparent at arrest time, but still, this is surprisingly low to me. I wonder if it's only recorded for certain offenses as well)

**Comment by harrisj** [comment]
Oh wait, my math is wrong. We don't want to know the relationships between all offenders and all victims for all NIBRS offenses. My bad!

Instead, let me add of the sum of all offenders * victims for each incident

``` sql
SELECT SUM(t.cnt) 
FROM (SELECT count(*) AS cnt 
             FROM nibrs_offender o
             JOIN nibrs_victim v ON o.incident_id = v.incident_id
             JOIN nibrs_incident ni ON ni.incident_id = v.incident_id
             JOIN nibrs_month nm ON nm.nibrs_month_id = ni.nibrs_month_id
             JOIN ref_agency ra ON ra.agency_id = nm.agency_id 
             JOIN ref_state rs ON rs.state_id = ra.state_id
             WHERE rs.state_postal_abbr = 'RI' AND nm.data_year = 2014) t;
```

And the result of all possible victim-offender relationships is **78,538** which means that for 2014, 24.6% of possible offender-victim relationships were specified

**Comment by LarryBafundo** [comment]
@harrisj just following up on your latest thinking here. are you still in favor of create a special table for offender-victim relationships?

**Comment by harrisj** [comment]
I don't really see how we can not do that, given that if there are M offenders and N victims there might be N*M relationships between offenders and victims. There already is a table in the CDE for just that named `nibrs_victim_offender_rel` and the only question is if there is anything else we really need to add to it or if that is enough.

Under this model if you wanted to know what percentage of homicides were among people who were acquainted you would have to do this

1. Get all offenses for homicides
2. Get all incidents associated with those offenses
3. Get all offenders associated with those incidents
4. Get all victims associated with those incidents
5. See which incidents involved an offender-victim relationship

So, it's a little bit circuitous, but it's also the only way to properly do this I think

**Comment by LarryBafundo** [comment]
@harrisj since we're not immediately pursuing a denormalization strategy for the bulk downloads, should i close this? i'm not sure if we'll push on this next sprint, or switch gears and just leave CJIS with a roadmap for a more denormalized approach for the bulk downloads , so i dont want to lose your notes.

**Comment by harrisj** [comment]
Closing since CJIS is taking over the generation of these views
