### ISSUE TITLE
Not all NIBRS victims are people

### ISSUE THREAD

**Issue by harrisj** [18F/crime-data-api#664]
So, one potential source of confusion specifically in regards to how expert users might count things differently from the general public is that not all NIBRS victims are people. From the NIBRS documentation we have this

> During a bank robbery, the offender pointed a gun at a teller, demanded, and received money. The robber also pistol-whipped a customer who stood in his way as he made his getaway from the bank. There were three victims: the bank (F = Financial Institution), the teller
(I = Individual), and the pistol-whipped customer (I = Individual). Therefore, agencies should enter the appropriate codes into their respective Victim Segments.

Indeed, when I look at the nibrs_victim table, I see the following breakdown of victim types for 2014:

| victim_type_code |    victim_type_name     |  count  |
|------------------|-------------------------|---------|
| B                | Business                |  881,129 |
| F                | Financial Institution   |   16,416 |
| G                | Government              |   69,065 |
| I                | Individual              | 3,873,256 |
| L                | Law Enforcement Officer |   14,889 |
| O                | Other                   |   14,868 |
| R                | Religious Organization  |    9,689 |
| S                | Society/Public          |  614,460 |
| U                | Unknown                 |   15,284 |

So, ~1.5 million of the victims are actually not people, which is a pretty sizeable percentage. It doesn't look like we copy this field over to the nibrs_victim_denorm table right now nor do we use it to reduce the victims included in that table.

**Comment by harrisj** [comment]
Under further investigation, it seems like there are no NIBRS incidents that don't include at least one victim. For instance, for the crime of Pornography, the single victim is 1 of type 8 "Society/Public"

**Comment by harrisj** [comment]
Two more notes: 

1. Non-people victims will not show up in our demographic breakdowns, since banks do not have race or ethnicity. But this is why reason why victim counts may be bigger than adding up all the victim demographics to a total.
2. Although one of the the offender_victim_relationship types is "Employer Of" I checked in the DB and it doesn't seem to be used for any non-people victims. So, if an offender burgles the store he works for, that isn't counted as an "Employer Of" relationship but if he mugs his actual boss at the store, then it is.

**Comment by harrisj** [comment]
One final comment on this issue from me. It seems like we could decide whether or not we want to include non-people victims in our bulk downloads. Pros and cons of each approach:

Include non-people victims:
1. Matches counts/mapping for NIBRS data as was submitted/recorded
2. Potential source of error if people count people victims by total lines without removing these entries

Do not include non-people victims:
1. Need some way for people to find crimes that affected particular institutions like banks or government (could be field added elsewhere). Is victim repeated if someone robbed 2 banks?

**Comment by LarryBafundo** [comment]
@harrisj we never got a judgement from CJIS about this during the call; but it sounds like we would recommend only counting persons as victims for the purposes of the CDE.

**Comment by harrisj** [comment]
So I think we should do the following:

1. For NIBRS-denorm tables we should keep all victims and include the victim_type as a string so that it's very clear when you scan the table that some victims are banks, etc. but if you wanted to find those offenses with victims, we should do that.

2. For the NIBRS-derived demographic visuals, I think actually we are unchanged because those victims would not show up in the racial breakdowns, etc. That said, we should compute the "true" victim count for just people for each offense/state/year or ORI/state/year so that we can say there were 124 robbery victims and it's just the people.

**Comment by harrisj** [comment]
Since CJIS is taking over the offense-specific counts, I guess this will ultimately be their call. Closing.
