### ISSUE TITLE
Add a Content Security Policy (CSP) header

### ISSUE THREAD

**Issue by jeremiak** [18F/crime-data-api#667]
We currently have no Content Security Policy set, but we should (refs [18f/crime-data-explorer#336](https://github.com/18F/crime-data-explorer/issues/336)). A CSP tells the browser which URLs it can load content/resources from, reducing the risk of a XSS attack by loading 3rd party code.

Considering that this application has no HTML returned for it, I think this should be pretty simple since we can just set the CSP to be the deployed URL.

18F guidance for [implementing a CSP is in the front end guide](https://github.com/18F/frontend/blob/1dfaf1bb1a8db8758654e5ddcc59159a51370104/pages/security/csp.md#usage)

**Comment by LarryBafundo** [comment]
@jeremiak what's the status of this ticket?

**Comment by jeremiak** [comment]
Just opened a PR to address this and then we should be able to close https://github.com/18F/crime-data-explorer/issues/336
