### ISSUE TITLE
Race count errors for arrest crosstabs

### ISSUE THREAD

**Issue by harrisj** [18F/crime-data-api#668]
From user feedback

> I have some questions and concerns about the arrest data files available on the Crime Data Explorer website (https://crime-data-explorer.fr.cloud.gov/downloads-and-docs).  For instance, the number of Asian/Pacific Islanders is often many times higher than the number of whites reported in many offense categories, and the annual totals seem quite low.  Is there an error in the interface that’s pulling the data, perhaps?  Are these rates and not counts?

**Comment by harrisj** [comment]
Confirmed I am definitely seeing this for the arrests_national_adults and arrests_national_juvenile CSV files. Next steps will be to check the source crosstab tables and the process to saving to CSV.

**Comment by harrisj** [comment]
The issue is in the DB source table sadly

| year | offense_code | white | black | asian_pacific_islander | american_indian |
------|--------------|-------|-------|------------------------|-----------------|
 |2014 | ASR_ARSON    |    32 |    38 |                    619 |            1815 |
 |2014 | ASR_AST      |   253 |   338 |                  10201 |           13285 |
 |2014 | ASR_AST_SMP  |  1291 |  1110 |                  46286 |           63598 |
 |2014 | ASR_BRG      |   297 |   407 |                  13558 |           18239 |
 |2014 | ASR_CUR      |   468 |   576 |                  19254 |           21715 |
 |2014 | ASR_DIS      |   830 |   458 |                  28905 |           34564 |

Which means it's probably something I did wrong, but it's also something we can just fix here and regenerate the files.

**Comment by harrisj** [comment]
I think I found the problem. The racial counts were being inserted in the wrong order. I'm not sure when this happened, but I should be able to rebuild the tables today.

**Comment by LarryBafundo** [comment]
@harrisj any updates on this?
