### ISSUE TITLE
`by` and `count` support for `/incidents/`

### ISSUE THREAD

**Issue by catherinedevlin** [18F/crime-data-api#72]
Right now the `/incidents/` endpoint, for NIBRS info, looks like:

        "results": [
            {
                "agency": {
                    "added_date": "1991-04-30T00:00:00+00:00",
                    "agency_id": 8411,
                    "agency_status": "A",
                    "agency_type": {
                        "agency_type_name": "State Police",
                        "default_pop_family": 4
                    },
                    "campus": null,
                    "change_timestamp": "2014-08-06T

I'm thinking about how to get summarized NIBRS data, and thinking 
that `count` and `by` keywords could do it, so that:

`/incidents/?offense_code=520&by=year,state&count=1`

would mean "Count of incidents with offense code 520, grouped first 
by year and then by state", and would produce results something like:

        "results": {
          2013: {
            'AK': 3823,
            'AL': 9146,
            .
            .
            .
          }

I don't think it would be very hard to write.

**Comment by harrisj** [comment]
Am I wrong or is this implemented now? (albeit with a separate `incidents/count` endpoint for counts)

**Comment by catherinedevlin** [comment]
What I've put in `/incidents/count/` is actually the RETA summary data; I wrote this ticket with the thought that we would want an endpoint that would actually do grouped record counts on the NIBRS records (the ones returned by `/incidents/`).  You could get that by taking the `['pagination']['count']` for each particular set of parameters you passed, but if (say) you want the count of every record per state (that matches all your other filters), you'd currently need to call `/incidents/?state=XX` once for each state.

This ticket was written as an idea, without being sure we would actually need it.  @jeremiak , what do you think?

**Comment by LarryBafundo** [comment]
@harrisj do we still need this?

**Comment by harrisj** [comment]
We removed the `/incidents` endpoint for now, so no. Closing
