### ISSUE TITLE
`/incidents/` age should reflect complex age rules

### ISSUE THREAD

**Issue by catherinedevlin** [18F/crime-data-api#73]
NIBRS record of ages is quirky around the edges.  I asked FBI by email:

> Tables like NIBRS_ARRESTEE, NIBRS_VICTIM, and NIBRS_OFFENDER all reference NIBRS_AGE, which contains the following categories.  I am guessing that these categories do not actually refer to the ages of offenders/victims/arrestees, unless our nation is suffering a worrisome epidemic of crimes by/against centenarians and neonates.  So... what am I missing?
>  
>  
> ```
> crime_data_api_dev=# select * from nibrs_age;
> 
>  age_id | age_code |     age_name      
> --------+----------+-------------------
>       5 | AG       | Age in Years
>       4 | 00       | Unknown
>       3 | BB       | 7-364 Days Old
>       2 | NB       | 1-6 Days Old
>       6 | 99       | Over 98 Years Old
>       1 | NN       | Under 24 Hours
> ```

FBI's reply:
 

> So NIBRS_AGE is a table containing age codes.  If you look, you will see that most of the age_id values are 5 meaning Age In years.  If the age_id is set to 5, you need to look at the AGE_NUM in the associated table to get the age of the individual.
> For example, a victim who is 25 (there is a little more to this) will have an age_num of 25 with an age_id of 5.  If they are a baby, newborn, unknown, or over 98 then the age_id is set to the appropriate value.  
>  
>  
> BONUS AGE INFO LEVEL:
>  
> When age information is sent it, the age allows the codes from NIBRS_AGE and numbers.  The Age is a 4 character field.  If you send  in 02_ _ then the person’s age is stored as 2.  If they send in 2030, the person’s age is stored as 25.  Yes, we store the average of the submitted ages.  This does not apply to the codes except when 99 is in the last position. So a submission of 2099  would be stored as 59.  Now, in the new system we have started storing all 3 numbers, but we don’t have the information for migrated years.
>  
>

**Comment by catherinedevlin** [comment]
Age in Years is the only category that corresponds with a number in AGE_NUM; all others correspond to NULL AGE_NUM.

To boil this down into a usable number, I suggest

1-6 Days Old  -> Age 0
7-364 Days Old -> Age 0
Over 98 Years Old -> Age 99 
Unknownn -> NULL (which is the literal meaning of the NULL value in any case)

This assumes that nobody really needs the difference between week-old neonates and older zero-year-old babies.

We could report 99 as a string "99+", but then it's no longer an integer field and you can't do math on it.

**Comment by harrisj** [comment]
So, this sounds good, but I have a few questions:

1. Is there some criminal offense category for which that distinction between newborn and older babies is important? If so, it'll probably be important to preserve that distinction.
2. I suppose in some sense, the risk of returning 99 for a 110-year-old victim is that it might affect averages/medians. More likely, it might just lead to some confusion if the victim is actually 99 or 99+

Are you planning to still present the original NBIRS_AGE codes as well for all these values? In such case, detailed analysis can always look to those. Otherwise, it might be necessary to parse the caveats for issues.

**Comment by catherinedevlin** [comment]
@harrisj : Good points.  Keeping the `age_code`, in case it's needed, but also reporting `age_num` as a math-able integer, should preserve all that information.

**Comment by cacraig** [comment]
This was fixed in #78 . - Closing.
