### ISSUE TITLE
Finalize learning objectives for sprint 

### ISSUE THREAD

**Issue by LarryBafundo** [18F/crime-data-api#88]
https://docs.google.com/document/d/1d38oci3mWYVIztr7Hu2mgI0FIaMdSneYPUN53Gh-eYg/edit

**Comment by nicoleslaw** [comment]
Reviewed these. @amberwreed wants to take one more pass.

**Comment by LarryBafundo** [comment]
i added some comments and a few more learning objectives for the CSV and API test areas. @jeremiak, please review and feel free to edit/add where necessary. Assuming these questions can serve as the basis for our testing on Thursday, we'll need to figure out what tasks are necessary to support the testing - like potential changes to our API documentation and additional CSV work.
