### ISSUE TITLE
Explore data for insights/opportunity areas for content & design 

### ISSUE THREAD

**Issue by LarryBafundo** [18F/crime-data-api#95]

**Comment by nicoleslaw** [comment]
Depends on #94

**Comment by jeremiak** [comment]
Here are some of the charts that I threw together with all of the NIBRS incidents I could get from the API for rape offenses in Ohio. I'm posting here so they're in a place that is available to everybody
![ohio-rape-location-bar](https://cloud.githubusercontent.com/assets/780941/20736915/9420c920-b677-11e6-8b37-75273b6d5287.png)
![ohio-rape-relationship-bar](https://cloud.githubusercontent.com/assets/780941/20736913/941e65e0-b677-11e6-9009-de31e8daa862.png)
![ohio-rape-victim-age-histogram](https://cloud.githubusercontent.com/assets/780941/20736914/941f12ba-b677-11e6-8b44-6c7d873870a5.png)

**Comment by ericronne** [comment]
thanks!

and wow, data is powerful stuff.
so cool we can do this
