### ISSUE TITLE
Develop copy for data snapshot 

### ISSUE THREAD

**Issue by LarryBafundo** [18F/crime-data-api#98]

**Comment by LarryBafundo** [comment]
@nicoleslaw when you have a chance, could you please update this issue with more specifics regarding the content we're developing for the data snapshot?

**Comment by nicoleslaw** [comment]
I can't fully answer this until I see what the data entails, but the kinds of things I've gathered so far for editing are sections about:

- The new and legacy rape definition
- How rape incidents are counted
- Why legacy rape incidents continue to be counted
- Methodology
- Estimations for national trend data
- Related links / further reading

**Comment by nicoleslaw** [comment]
Copy is here for review: https://docs.google.com/document/d/187bzDcm7Xu1XuypTV3PLCmiG_P8TWA7YM0_e-OJOMps/edit#

I need to sync with @ericronne though—this is a first pass.
